### ISSUE TITLE
TwilioVideoParticipantView is blank (White) No Video Just Audio both iOS and Android

### ISSUE THREAD

**Issue by pranong** [blackuy/react-native-twilio-video-webrtc#100]
### Steps to reproduce
1. git clone https://github.com/blackuy/react-native-twilio-video-webrtc.git
2. Move to the Example directory: cd Example
3. Install node dependencies: yarn install
4. Install objective-c dependencies: cd ios && pod install
5. Open the xcworkspace and run the app: open Example.xcworkspace

### Expected behaviour
Can make a simple Video call

### Actual behaviour
I'm getting the audio only, but TwilioVideoParticipantView is blank (White) on both iOS and Android

### Environment
- **Node.js version**: v9.10.0
- **React Native version**: 0.44.0
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: npm version or "master"

**Comment by pranong** [comment]
_onParticipantAddedVideoTrack do nothing npt even log some thing
I'm using this code
[](https://github.com/blackuy/react-native-twilio-video-webrtc/blob/master/Example/index.ios.js)
line 136

Thank you So much

**Comment by slycoder** [comment]
Are the other callbacks getting called?  And if so it would be useful to know what data they're reporting and in what sequence.

**Comment by somsin** [comment]
whats TwilioVideo sdk version you have in pod

**Comment by somsin** [comment]
iOS Pod: pod 'TwilioVideo', '~> 1.4.0'

 this is working

**Comment by Andresagustin** [comment]
Updated the pod to 1.4.0. Same issue. Also I have this Warning on the iPhone
![img_7093](https://user-images.githubusercontent.com/40077694/41187394-9353bfb2-6b7e-11e8-9cc4-0b9ca14a95af.PNG)

**Comment by slycoder** [comment]
Have you tried setting the `enabled` prop on your `TwilioVideoLocalView` component?

**Comment by hardikramoliya** [comment]
Same issue here.
After the room connected. There is not showing TwilioVideoParticipantView.

**Comment by vasan-emids** [comment]
I'm too facing similar issue, connected to the room, but the TwilioVideoParticipantView is not showing, both the participants are showing up in the TwilioVideoLocalView. And this is in Android. Any help would be appreciated. Thanks in advance!!

**Comment by slycoder** [comment]
Just to reiterate, does setting `enabled` allow the participant views to work?

**Comment by vasan-emids** [comment]
Thanks for your prompt attention, yes, I am setting enabled to the participant view, please find below the code snippet:

<View style={styles.videoViewParent}>
                <TwilioVideoLocalView enabled={true} style={styles.videoViewContainer} />
                <TwilioVideoParticipantView enabled={true} style={styles.videoViewContainer} />
            </View>

Let me know if this is not the right way to do it. Thanks in advance for your help on this, looking forward to your feedback.

Regards


Vasan Jagannathan
Architect
Cell: +919945219024
View Our Latest Insights
Our Values: People Growth • Customer Success • Innovation & Execution Excellence
DISCLAIMER: The information in this message is "emids Technologies" confidential and may be legally privileged. It is intended solely for the addressee. Access to this message by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, or distribution of the message, or any action or omission taken by you in reliance on it, is prohibited and may be unlawful. Please contact deliveryerror@emids.com immediately if you have received this message in error. Thank you.

**Comment by vasan-emids** [comment]
Thanks for your prompt attention, yes, I am setting enabled to the participant view, please find below the code snippet:

`
<View style={styles.videoViewParent}>
                <TwilioVideoLocalView enabled={true} style={styles.videoViewContainer} />
                <TwilioVideoParticipantView enabled={true} style={styles.videoViewContainer} />
            </View>
`
Let me know if this is not the right way to do it. Thanks in advance for your help on this, looking forward to your feedback.

**Comment by slycoder** [comment]
Hey, so we just upgraded master to use Twilio 2.x! Hopefully it'll resolve a bunch of issues people are seeing.  The README section now has a section on migrating from 1.x to 2.x to help you in that process; let me know if this is still an issue after the upgrading.

**Comment by vasan-emids** [comment]
Things are working fine after we wen through the migration to 2.x. Thanks a lot for your help on this, greatly appreciated!!

**Comment by slycoder** [comment]
Great to hear!  I'll go ahead and close out this issue then.

**Comment by sohamsuthar** [comment]
Facing issue in

**Comment by RadiaTechs-Gaganesh** [comment]
@slycoder , i am facing the same issue. TwilioVideoLocalView as well as TwilioVideoParticipantView is not showing any thing but transparent screen when room is connected. only buttons are shown which is end, mute and flip. On web i can see each and every thing from mobile cams.

--: My Code :---

import React, { Component } from "react"
import { TwilioVideoLocalView, TwilioVideoParticipantView, TwilioVideo } from "react-native-twilio-video-webrtc"
import { scale, verticalScale } from "../../../utils/Scale"
import * as Const from "../../../utils/Const"
import { Icon } from "../../../components"

import { AppRegistry, StyleSheet, Text, TextInput, View, Button, PermissionsAndroid, Platform, TouchableOpacity, Dimensions } from "react-native"

export default class VideoConference extends Component {
	constructor(props) {
		super(props)
		this.state = {
			isAudioEnabled: true,
			isVideoEnabled: true,
			status: "disconnected", // "connecting"
			participants: new Map(),
			videoTracks: new Map(),
			// videoTrack: {},
			roomName: "Room 1", //added new
			token: props.route.params.token,
		}
	}
	getAllPermissions = async () => {
		try {
			if (Platform.OS === "android") {
				const userResponse = await PermissionsAndroid.requestMultiple([PermissionsAndroid.PERMISSIONS.CAMERA, PermissionsAndroid.PERMISSIONS.RECORD_AUDIO, PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE])
				return userResponse
			}
		} catch (err) {
			console.log(err)
		}
	}
	async componentDidMount() {
		this.getAllPermissions()
		console.log("Video Conference MOUNT\nParams", this.props.route.params, "\nState", this.state)
		setTimeout(() => {
			this.twilioRef.connect({ accessToken: this.state.token })
		}, 1000)
	}

	componentDidUpdate() {
		console.log("Video Conference UPDATE\nParams", this.props.route.params, "\nState", this.state)
		console.log("this.twilioRef.setLocalVideoEnabled", this.twilioRef)
		if (this.state.status && (this.state.status === "failed" || this.state.status === "ended")) {
			this.props.navigation.goBack()
		}
	}

	_onConnectButtonPress = async () => {
		try {
			this.setState({ status: "connecting" })
			this.twilioRef.connect({
				roomName: this.state.roomName,
				accessToken: this.state.token,
			})
		} catch (error) {
			console.log(error)
		}
	}

	_onEndButtonPress = () => {
		this.twilioRef.disconnect()
		this.setState({ status: "ended" })
	}

	_onMuteButtonPress = () => {
		this.twilioRef.setLocalAudioEnabled(!this.state.isAudioEnabled).then((isEnabled) => {
			console.log("MUTE state", isEnabled)
			this.setState({ isAudioEnabled: isEnabled })
		})
	}

	_onFlipButtonPress = () => {
		this.twilioRef.flipCamera()
	}

	_onRoomDidConnect = () => {
		this.setState({ status: "connected" })
	}

	_onRoomDidDisconnect = ({ roomName, error }) => {
		console.log("Disconnect ERROR: ", error)
		this.setState({ status: "disconnected" })
	}

	_onRoomDidFailToConnect = (error) => {
		console.log("Fail to Connect ERROR: ", error)
		this.setState({ status: "failed" })
	}

	_onParticipantAddedVideoTrack = ({ participant, track }) => {
		console.log("onParticipantAddedVideoTrack: ", participant, track)
		this.setState({
			videoTracks: new Map([...this.state.videoTracks, [track.trackSid, { participantSid: participant.sid, videoTrackSid: track.trackSid }]]),
		})
	}

	_onParticipantRemovedVideoTrack = ({ participant, track }) => {
		console.log("onParticipantRemovedVideoTrack: ", participant, track)

		const videoTracks = this.state.videoTracks
		videoTracks.delete(track.trackSid)

		this.setState({ videoTracks: new Map([...videoTracks]) })
	}
	setTwilioRef = (ref) => {
		this.twilioRef = ref
	}
	render() {
		return (
			<View style={styles.container}>
				{this.state.status === "disconnected" ? (
					<View>
						<Text style={styles.welcome}>React Native Twilio Webrtc</Text>
						<TextInput style={styles.input} autoCapitalize="none" value={this.state.roomName} onChangeText={(text) => this.setState({ roomName: text })}></TextInput>
						<TextInput style={styles.input} autoCapitalize="none" value={this.state.token} onChangeText={(text) => this.setState({ token: text })}></TextInput>
						<Button title="Connect" style={styles.button} onPress={this._onConnectButtonPress}></Button>
					</View>
				) : null}
				{this.state.status === "connected" || this.state.status === "connecting" ? (
					<View style={styles.callContainer}>
						{this.state.status === "connected" && (
							<View style={styles.remoteGrid}>
								{Array.from(this.state.videoTracks, ([trackSid, trackIdentifier]) => {
									return <TwilioVideoParticipantView enabled={true} style={styles.remoteVideo} key={trackSid} trackIdentifier={trackIdentifier} />
								})}
							</View>
						)}
						<View style={styles.optionsContainer}>
							<TouchableOpacity style={styles.optionButton} onPress={this._onEndButtonPress}>
								<Text style={{ fontSize: 12 }}>End</Text>
							</TouchableOpacity>
							<TouchableOpacity style={styles.optionButton} onPress={this._onMuteButtonPress}>
								<Text style={{ fontSize: 12 }}>{this.state.isAudioEnabled ? "Mute" : "Unmute"}</Text>
							</TouchableOpacity>
							<TouchableOpacity style={styles.optionButton} onPress={this._onFlipButtonPress}>
								<Text style={{ fontSize: 12 }}>Flip</Text>
							</TouchableOpacity>
							<TwilioVideoLocalView enabled={true} style={styles.localVideo} />
							<View />
						</View>
					</View>
				) : null}
				<TwilioVideo ref={this.setTwilioRef} onRoomDidConnect={this._onRoomDidConnect} onRoomDidDisconnect={this._onRoomDidDisconnect} onRoomDidFailToConnect={this._onRoomDidFailToConnect} onParticipantAddedVideoTrack={this._onParticipantAddedVideoTrack} onParticipantRemovedVideoTrack={this._onParticipantRemovedVideoTrack} />
			</View>
		)
	}
}

const styles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: "white",
	},
	callContainer: {
		flex: 1,
		position: "absolute",
		bottom: 0,
		top: 0,
		left: 0,
		right: 0,
	},
	welcome: {
		fontSize: 30,
		textAlign: "center",
		paddingTop: 40,
	},
	input: {
		height: 50,
		borderWidth: 1,
		marginRight: 70,
		marginLeft: 70,
		marginTop: 50,
		textAlign: "center",
		backgroundColor: "white",
	},
	button: {
		marginTop: 100,
	},
	localVideo: {
		width: 125,
		height: 200,
		position: "absolute",
		right: 10,
		bottom: 400,
		borderRadius: 2,
		borderColor: "#4e4e4e",
	},
	remoteGrid: {
		flex: 1,
		flexDirection: "row",
		flexWrap: "wrap",
	},
	remoteVideo: {
		width: "100%",
		height: "100%",
	},
	optionsContainer: {
		position: "absolute",
		left: 0,
		bottom: 0,
		right: 0,
		height: 100,
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
	},
	optionButton: {
		width: 60,
		height: 60,
		marginLeft: 10,
		marginRight: 10,
		borderRadius: 100 / 2,
		backgroundColor: "grey",
		justifyContent: "center",
		alignItems: "center",
	},
})

**Comment by slycoder** [comment]
Hi @RadiaTechs-Gaganesh , thanks for the report.  Since it sounds like a new issue, let's continue this discussion in one of the other threads.

**Comment by nerdyalbs007** [comment]
So apparently what happens is that, there exists a connect button which is not visible, but when you click that button, the videocall should start.
It is somewhere around top-left of the screen.

**Comment by AireshBhat** [comment]
I'm facing the same issue as well. I'm able to see the participant on web and on iOS but on android the **onParticipantAddedVideoTrack** does not get called at all. Is there anything I can do that can help debug this issue? @slycoder . I'm using the latest version of the library as well.

**Comment by ch3tan03** [comment]
> 

Any update? did you solve the issue?

**Comment by ch3tan03** [comment]
> I'm facing the same issue as well. I'm able to see the participant on web and on iOS but on android the **onParticipantAddedVideoTrack** does not get called at all. Is there anything I can do that can help debug this issue? @slycoder . I'm using the latest version of the library as well.


Any update? did you solve the issue?

**Comment by thanhnvpk01168** [comment]
hi @ch3tan03  @slycoder 
did you solve the issue?

**Comment by sankparatkar** [comment]
@slycoder,

I am still facing this issue with 3.x version.
Can you please advise?

**Comment by ombogdanJoinToIt** [comment]
same problem

**Comment by devwithshahzaib** [comment]
I'm having the same problem... is there any solution??

**Comment by thanhnvpk01168** [comment]
hi @devwithshahzaib 
Why didn't you choose Zoom's video SDK and instead opted for Twilio's?
