### ISSUE TITLE
How to capture a frame from the local video stream?

### ISSUE THREAD

**Issue by sikloidz** [blackuy/react-native-twilio-video-webrtc#101]
Hi, I was wondering how can I capture a frame from the local video stream? 
With the twilio's android sdk, this is done with `CameraCapturer.takePicture(CameraCapturer.PictureListener)`, is this functionality available?

**Comment by bilby91** [comment]
@sikloidz We don't support screen capturing at this moment. We just moved to Twilio v2 so adding that should be pretty easy. 

Follow this issue => #62

**Comment by lylysunshinee** [comment]
any update here? We need support screen capturing
