### ISSUE TITLE
TwilioVideoLocalView black on Android

### ISSUE THREAD

**Issue by emin93** [blackuy/react-native-twilio-video-webrtc#102]
### Steps to reproduce
```typescript
import React, { Component } from "react";
import { PermissionsAndroid, Platform, StyleSheet, View } from "react-native";
import { TwilioVideo, TwilioVideoLocalView } from "react-native-twilio-video-webrtc";

export default class App extends Component {
 componentDidMount() {
    if (Platform.OS !== "android") {
      return;
    }

    PermissionsAndroid.requestMultiple([
      PermissionsAndroid.PERMISSIONS.CAMERA,
      PermissionsAndroid.PERMISSIONS.RECORD_AUDIO
    ]);
  }

  render() {
    return (
      <View style={styles.container}>
        <TwilioVideoLocalView enabled={true} style={styles.container} />
        <TwilioVideo ref={c => (this.twilioVideo = c)} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1
  }
});
```

### Expected behaviour
Should show a live view of the camera

### Actual behaviour
Shows a black screen while on iOS it shows the camera. No errors or anything else.

### Environment
- **Node.js version**: v8.11.2
- **React Native version**: 0.55.4
- **Android Gradle Settings**:
```
compileSdkVersion 26
buildToolsVersion "26.0.2"
minSdkVersion 16
targetSdkVersion 26

compile "com.android.support:appcompat-v7:26.1.0"
```

### react-native-twilio-video-webrtc
**Version**: "master"

**Comment by emin93** [comment]
Okay, found the issue. It seems like on Android the view somehow fails to load when the app starts too fast.

I added some async things in the componentDidMount and suddenly the view became visible.

**Comment by AnthonyMann** [comment]
Having this exact issue, 

On Android, the TwilioVideoLocalView only shows the local camera feed once connected (in our use-case the call won't always connect immediately) leaving the android user staring at a black screen, where on iOS it shows the camera feed.

What did you do to fix this @emin93 ?

**Comment by Deg5112** [comment]
So was this solved? What's the fix

**Comment by diegoacuna** [comment]
@slycoder Hi! today I tried the same example on the "Steps to reproduce" (first comment by @emin93 ) and I still see the black screen on Android. Is there anything else to do to be able to display a local view without being connected to a Room? thanks!

**Comment by slycoder** [comment]
@diegoacuna That's correct; I believe the backend doesn't create a camera capturer until connect is called.  I can see how this would be problematic for some use cases.  Do you have a suggested alternative approach?

**Comment by diegoacuna** [comment]
@slycoder what I ended up doing is to do a twilioVideo.connect with no token and no reacting to the disconnect callback. With this, I can have kind of like a "local preview" without being actually connected to a room.

I'm just getting familiarized with the Twilio Android library and react-native-twilio-video-webrtc (great job btw!) so for now.  I can't propose a real fix to this issue. Probably on the next days I'm going to have more insights on how this works, and try to propose a fix. Thanks!

**Comment by ombogdanJoinToIt** [comment]
same problem
