### ISSUE TITLE
(evaluating 'i.refs.twilioVideo.setLocalAudioEnabled(!i.state.isAudioEnabled).then')

### ISSUE THREAD

**Issue by hardikramoliya** [blackuy/react-native-twilio-video-webrtc#103]
### Steps to reproduce
1. Press **`Connect`** to Video Call
2. Press **`Mute`** Button
3.` undefined is not an object (evaluating 'i.refs.twilioVideo.setLocalAudioEnabled(!i.state.isAudioEnabled).then')`

### Environment
- **Node.js version**: v8.11.1
- **React Native version**: ^0.53.3
- **React Native platform + platform version**: Android 7.0 and 6.0

Any one have idea? Please help me out. Thanks

**Comment by slycoder** [comment]
Do you have any context here?  What does your code look like?  Do you have a <TwilioVideo /> instantiated somewhere with its ref set?

**Comment by hardikramoliya** [comment]
Hello @slycoder Thanks for your response.
Here is my code
```
 _onMuteButtonPress = () => {
          this.refs.twilioVideo.setLocalAudioEnabled(!this.state.isAudioEnabled)
            .then(isEnabled => this.setState({ isAudioEnabled: isEnabled }))
    }
```

**Comment by slycoder** [comment]
How are you creating the TwilioVideo component though?  A more complete view of the component would help.

**Comment by Shashank2406** [comment]
Found the issue, try using like this 

`_onMuteButtonPress = () => {
          this.refs.twilioVideo.setLocalAudioEnabled(!this.state.isAudioEnabled)
            
    }`

**Comment by slycoder** [comment]
Ah yes, on android this function is not a promise.

**Comment by bilby91** [comment]
@hardikramoliya This should be solved with the code in master now.
