### ISSUE TITLE
Android 27 release build crashes on video connect with `error during FindClass: org/webrtc/AudioTrack`

### ISSUE THREAD

**Issue by slvtrs** [blackuy/react-native-twilio-video-webrtc#104]
### Problem
On Android, a **signed APK** or a **Release Variant** build app crashes with this error as soon as video connects:
```
# Fatal error in ../../webrtc/sdk/android/src/jni/classreferenceholder.cc, line 159
# last system error: 88
# Check failed: !jni->ExceptionCheck()
# error during FindClass: org/webrtc/AudioTrack
```
#### Notes
* My app was built with expo and has been detached.
* I've gone through the various installation steps for Android and iOS.
* The video connects fine with no error on iOS and on Android in **Debug Variant** builds.

### What worked for me
Eventually, I was able to find a solution that worked for my release build.
I'll leave it here incase someone runs into a similar situation, or can explain the problem better:

Add these two lines to `proguard-rules.pro`:
```
  -keep class org.webrtc.** { *; }
  -keep class com.twilio.** { *; }
```

### Environment
- **Node.js version**: 9.3.0
- **React Native version**: "https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz"
- **React Native platform + platform version**: Android sdk 27

### react-native-twilio-video-webrtc
**Version**: master

**Comment by slycoder** [comment]
Thanks for pointing this out!  I'll add this to the readme.
