### ISSUE TITLE
Building iOS project fails -- 'trackID' not found on object of type 'TVITrack *'

### ISSUE THREAD

**Issue by mikesholiu** [blackuy/react-native-twilio-video-webrtc#107]
### Steps to reproduce
1. Install and link react-native-twilio-video-webrtc
2. Install TwilioVideo pod
3. Build project in Xcode

### Expected behaviour
Successful build in Xcode

### Actual behaviour
Build Failed -- `Property 'trackId` not found on object of type 'TVITrack *' in RCTTWSerialization.m`

### Environment
- **Node.js version**: 10.3.0
- **React Native version**: 0.55.4
- **React Native platform + platform version**: iOS 11

### react-native-twilio-video-webrtc
**Version**: master

When I try to build my project after adding this library and TwilioVideo to the Podfile, the build fails with the error:

`Property 'trackId' not found on object of type 'TVITrack *' in RCTTWSerialization.m`
 
<img width="823" alt="screen shot 2018-07-06 at 11 57 32 am" src="https://user-images.githubusercontent.com/3348222/42395851-2f759f46-8114-11e8-9260-de1adbe5cd0a.png">

TVITrack.h doesn't seem to contain any reference to a trackId.

Have tried reinstalling the Pod and relinking the library which result in the same error.

**Comment by slycoder** [comment]
What version of the twilio library is getting installed?

**Comment by mikesholiu** [comment]
2.2.1 I believe. I see that master doesnt support v 2.x. Is it possible to use the v2 branch? I don't see a .xcodeproj file in the ios folder.

**Comment by slycoder** [comment]
I'm not sure what the state of that is at the moment.  Are there any 2.x features in particular you're looking to use?  Maybe I can just put some quick shims in for the time being to get things working.

**Comment by slycoder** [comment]
If you're interested I've put up #108 and would love your feedback.

**Comment by slycoder** [comment]
2.x is now supported on master.  Closing this out.
