### ISSUE TITLE
Is there plans to support TwilioVideo 2.0+ and RN 0.55 with this wrapper?

### ISSUE THREAD

**Issue by mjaffa-figure** [blackuy/react-native-twilio-video-webrtc#110]
Is there plans to support TwilioVideo 2.0+ and RN 0.55 with this wrapper? Anyone done work on this? That works on both iOS and Android

**Comment by slycoder** [comment]
As far as I know, RN 0.55 should work fine.

As for 2.0+ support, check out #109  and #108

**Comment by slycoder** [comment]
2.x is on master.
