### ISSUE TITLE
Compile errors with ReactNative 0.55 and this project 1.0.1

### ISSUE THREAD

**Issue by mjaffa-figure** [blackuy/react-native-twilio-video-webrtc#111]
These are some of the compile errors, but all relate to React Native redefinitions once I include react-native-twilio-video-webrtc into my react native project:

Typedef redefinition with different types ('struct (anonymous struct at ../../react-native/React/BBBase/RCTBridgeModule.h:52:16)' va 'struct RCTMethodInfo')

Or when I try to compile the project on its own, this library I get this compile error:

'React/RCTComponent.h' file not found in UIView+REact.h included by one of this projects .m and .h files.

### Expected behaviour
Should compile just fine

### Actual behaviour
Compile errors

### Environment
- **Node.js version**:
- **React Native version**: 0.55
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: npm version or "master"
1.0.1

**Comment by slycoder** [comment]
Try using master.  Also are you using podfiles for this package?  If so are you also using podfiles for RN?

**Comment by mjaffa-figure** [comment]
I got it working. But now I am not getting any notifications when other participants have joined the room...

**Comment by slycoder** [comment]
As a reference to others could you post what the solution was to get it working?

Are you also not getting `onParticipantAddedVideoTrack` notifications?

**Comment by mjaffa-figure** [comment]
The problem was I first downloaded all the v2 branch and included the files directly in my project, so Xcode has compiled them. I then decided to go through the react native package. So cache had the experimental v2 classes cached. I deleted my derived data and cache and recompiled and it worked.


Yes I am also not getting the onParticipantAddedVideoTrack notification. Even after are web app has joined the conversation. Could it be that our web app is using H264 streams and the V1.0 TwilioVideo api doesn't support them??

**Comment by slycoder** [comment]
That's totally possible.  If you join via web first then via the app, do you see the remote participant in the `participants` field of `onRoomDidConnect`?

**Comment by mjaffa-figure** [comment]
This is basically what I do. I call our backed to connect. I get back an access token, I then call:

this.twilioVideo.connect({ roomName: 'Test', accessToken: accessToken });
        this.setState({ isOpen: true });

I have this as my TwilioVideo rn code:

<TwilioVideo
            ref={(el) => { this.twilioVideo = el; }}
            onRoomDidConnect={ this._onRoomDidConnect }
            onRoomDidDisconnect={ this._onRoomDidDisconnect }
            onRoomDidFailToConnect= { this._onRoomDidFailToConnect }
            onParticipantAddedVideoTrack={ this._onParticipantAddedVideoTrack }
            onParticipantRemovedVideoTrack= { this.onParticipantRemovedVideoTrack }
            onParticipantDidConnect={this._onParticipantDidConnect}
          />

_onRoomDidConnect = ({roomName, participants}) => {
        console.log('Connected with participants: ' + JSON.stringify(participants) + ' And Room: ' + roomName);
      }
    
      _onRoomDidDisconnect = ({roomName, error}) => {
        console.log("ERROR: ", error)
    
        this.setState({status: 'disconnected'})
      }
    
      _onRoomDidFailToConnect = (error) => {
        console.log("ERROR: ", error)
    
        this.setState({status: 'disconnected'})
      }
    
      _onParticipantAddedVideoTrack = ({participant, track}) => {
        console.log("onParticipantAddedVideoTrack: ", participant, track)
    
        this.setState({videoTracks: { ...this.state.videoTracks, [track.trackId]: { ...participant, ...track }}})
      }
    
      _onParticipantRemovedVideoTrack = ({participant, track}) => {
        console.log("onParticipantRemovedVideoTrack: ", participant, track)
    
        const videoTracks = this.state.videoTracks
        videoTracks.delete(track.trackId)
    
        this.setState({videoTracks: { ...videoTracks }})
      }

      _onParticipantDidConnect = ({roomName, participant}) => {
        console.log("onParticipantDidConnect: ", participant, roomName);
      }

And these are the only logs I get:

Connected with participants: []


Any help would be awesome.

Thanks!

**Comment by mjaffa-figure** [comment]
Ok So an update. Our remote web app is getting my video feed from the phone. I can see my localView on the phone. I just can't see the remote person on the phone cause I never get onParticipantDidConnect or Participant added video track. And when I connect to TwilioVideo I don't see any participants already on...

Anything I can do?

**Comment by mjaffa-figure** [comment]
Ok so I get participant did connect calls and didConnect callback also says I have one participant. But no where in the participant does it say they have a video track. When I call getStats, I get a localAudioTrack, localVideoTrack, audioTrack, but no videoTrack...

**Comment by slycoder** [comment]
Hey, so we just upgraded master to use Twilio 2.x!  Hopefully it resolves a bunch of issues around track events.  If you're still running into issues, could you give that a try?  The README section now has a section on migrating from 1.x to 2.x to help you in that process.
