### ISSUE TITLE
Compile Errors, rn 0.55.2, rntvw 1.0.2

### ISSUE THREAD

**Issue by cristiandley** [blackuy/react-native-twilio-video-webrtc#116]
### Steps to reproduce
1. add package with yarn
2. Podfile >>> pod 'react-native-twilio-video-webrtc', path: '../node_modules/react-native-twilio-video-webrtc'
3. pod install
4. Add the XCode project to XCode project's "Libraries" directory
5. Add libRNTwilioVideoWebRTC.a to your XCode project target's "Linked Frameworks and Libraries".
6. react-native run-ios

### Expected behaviour
Compile...

### Actual behaviour
```
** BUILD FAILED **



The following build commands failed:
        CompileC /Users/cristianleyes/proyectos/app-rn/ios/build/Build/Intermediates.noindex/RNTwilioVideoWebRTC.build/Debug-iphonesimulator/RNTwilioVideoWebRTC.build/Objects-normal/x86_64/RCTTWSerializable.o RCTTWSerializable.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

```

### Environment
- **Node.js version**: 8.9.0
- **React Native version**: 0.55.2
- **React Native platform + platform version**: iOS 11.0

### react-native-twilio-video-webrtc
**Version**: master branch

**Comment by slycoder** [comment]
I'll close this issue then and debug in #55

**Comment by bilby91** [comment]
Closing as @slycoder said. Focus for this issue will be in #55
