### ISSUE TITLE
Video/Audio freezes on iOS device auto locking (iPhone & iPad)

### ISSUE THREAD

**Issue by vasan-emids** [blackuy/react-native-twilio-video-webrtc#120]
### Steps to reproduce
1. git clone https://github.com/blackuy/react-native-twilio-video-webrtc.git
2. Follow the Readme.md instruction for iOS
3. Join video chat in iPhone
4. Once iPhone/ipad gets locked after sometimes
5. Unlock the phone

### Expected behaviour
Video chat should resume once the phone is unlocked using pattern or other means as applicable. 

### Actual behaviour
The chat view (both local and participant) freezes. We need to leave the room and rejoin. Interestingly this works as expected in Android devices, having issue only on Mac devices - iphone and ipad

### Environment
Node.js version: v9.10.0
React Native version: "^0.55.4
React Native platform + platform version: iOS 9.0

### react-native-twilio-video-webrtc
Version: npm version or "master"

Both audio and video freezes once the phone/tab gets locked, and none of the events are triggered, I tried to add logging/alerts in almost all the events, but none of the event is getting triggered. Any help would be greatly appreciated!!

**Comment by vasan-emids** [comment]
Is this issue something unique to me? I was thinking this could be a common problem that everyone is facing. 

@slycoder, can you please share your thoughts?

**Comment by slycoder** [comment]
Hm, for what it's worth I haven't tried running it behind the lock screen very often.  I tried just now and I realized that that doesn't happen in my app because I'm also using callkit.

**Comment by vasan-emids** [comment]
Interesting, are you saying the react native twilio app is using callkit?



Vasan Jagannathan
Architect
Cell: +919945219024
View Our Latest Insights
Our Values: People Growth • Customer Success • Innovation & Execution Excellence
DISCLAIMER: The information in this message is "emids Technologies" confidential and may be legally privileged. It is intended solely for the addressee. Access to this message by anyone else is unauthorized. If you are not the intended recipient, any disclosure, copying, or distribution of the message, or any action or omission taken by you in reliance on it, is prohibited and may be unlawful. Please contact deliveryerror@emids.com immediately if you have received this message in error. Thank you.

**Comment by slycoder** [comment]
The example app in this repo is not, but the production app I'm working on which uses this library also incorporates react-native-callkit for a more legit calling experience on iOS.

**Comment by vasan-emids** [comment]
That's cool, sorry to bug you on this, we are at a point that we need to decide whether to proceed with Twilio, and this issue is going to make or break the deal. Any help would be huge for us now.

I am very curious to understand how are you using react-native-callkit with this repo. can you please give me some inputs on this? And in case we are able to crack this, that would be terrific.  Thank you.

**Comment by vasan-emids** [comment]
Thanks, am trying out the above options, will revert back soon.

**Comment by uguryilmaz-noxarc** [comment]
check for:

![image](https://user-images.githubusercontent.com/45939777/50141772-6c424b00-02b9-11e9-8ee1-27a621427f92.png)

**Comment by Balasnest** [comment]
@Bang9 How did you manage to get it to work? I am also facing the same issue.

**Comment by Balasnest** [comment]
Fixed auto-lock issue by using **react-native-keep-awake**. 
**Quick fix:** Activate Idle Timer on `connect` and Deactivate on `disconnect` delegate. 

we can do this directly on native code instead of in RN.

**Comment by workprotocol** [comment]
> Fixed auto-lock issue by using **react-native-keep-awake**.
> **Quick fix:** Activate Idle Timer on `connect` and Deactivate on `disconnect` delegate.
> 
> we should do this directly on this package instead of in RN. will raise PR soon for this
> 
> @slycoder FYI ^

Works like a charm!
Would request this solution to be integrated into Twilio webrtc library itself.
