### ISSUE TITLE
IOS build fail

### ISSUE THREAD

**Issue by farrukhhashmi-novatore** [blackuy/react-native-twilio-video-webrtc#122]
On running getting these 2 errors:
1. /Users/macbookpro/Projects/loopedProject/loopedapp/node_modules/react-native-twilio-video-webrtc/ios/RCTTWSerializable.h:21:12: Cannot find interface declaration for 'TVITrackPublication'
2.  Property 'trackSid' not found on object of type 'const __strong id'

### react-native-twilio-video-webrtc
**Version**: "master"

**Comment by slycoder** [comment]
What version of twilio video are you using?

**Comment by farrukhhashmi-novatore** [comment]
Thanks for you reply, that my pod configuration
`
platform :ios, '8.1'

target 'TARGET_NAME' do
    pod 'TwilioVideo', '~> 1.0'
end`

**Comment by slycoder** [comment]
Please use a 2.x version of TwilioVideo.  (See the example app for a working version).

**Comment by farrukhhashmi-novatore** [comment]
@slycoder  Thanks I got success but now the issue is that I want to apply my own styles or want to expand the video of other person to full screen. How can we implement our own style or change the preview of videos . Second help I want from you is that I am creating  a video call app with this twilio video. Is there any way to show a calling screen on other persons mobile that this person is call you. Click to join the call . Any way to implement this by using twilio video. For example like whatsapp and messenger video calls.

**Comment by slycoder** [comment]
Hi, if you are interested in showing a calling screen you can look into using react-native-callkit.
