### ISSUE TITLE
Support Config for twilioVideo.connect

### ISSUE THREAD

**Issue by carlmagumpara** [blackuy/react-native-twilio-video-webrtc#123]
How can i add config like video set to false or audio

**Comment by slycoder** [comment]
If you are trying to enable/disable local audio/video, there's no parameter for connect, but you can call setLocalVideoEnabled or setLocalAudioEnabled before calling connect.

If you are trying to toggle remote video, you can set enabled={false} on the TwilioVideoParticipantView.

**Comment by tyleralves** [comment]
@slycoder I'm having difficulty trying to get `enabled={false}` to work with TwilioVideoParticipantView.

`<TwilioVideoParticipantView
        enabled={false}
        key={track.trackSid}
        trackIdentifier={track}
      />`

Can you confirm that this works with the new Twilio 2.0 changes?

**Comment by slycoder** [comment]
Oh you're totally right, enabled only works on the local preview.

Does it behave correctly if you don't render the participant's view?

**Comment by tyleralves** [comment]
@slycoder I wasn't rendering the TwilioVideoParticipantView at all. Just tried it to accomplish muting the TVIRemoteAudioTrack **locally**.

**Comment by slycoder** [comment]
Ah, I see yeah there's no easy way to mute the remote audio tracks.

PRs are definitely welcome!

**Comment by tyleralves** [comment]
@slycoder What about something like this?

```
RCT_EXPORT_METHOD(muteRemoteAudio:(NSString *)participantSid audioTrackSid:(NSString *)audioTrackSid) {
    TVIRemoteParticipant *participant = [self.room getRemoteParticipantWithSid:participantSid];
    TVIRemoteAudioTrack *remoteAudioTrack = participant.remoteAudioTracks[0].remoteTrack;
    [remoteAudioTrack setPlaybackEnabled:NO];
}
```
