### ISSUE TITLE
iOS build fails with library not found error

### ISSUE THREAD

**Issue by sarikabhimre18** [blackuy/react-native-twilio-video-webrtc#127]
clang: error: no such file or directory: '/Users/mac/Desktop/react-native-twilio-video-webrtc/Example/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c'
clang: error: no input files

** BUILD FAILED **

The following commands produced analyzer issues:
        Analyze Base/RCTModuleMethod.mm
        Analyze Modules/RCTUIManager.m
(2 commands with analyzer issues)

The following build commands failed:
        CompileC /Users/mac/Desktop/react-native-twilio-video-webrtc/Example/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Yoga.build/Objects-normal/x86_64/YGNodeList.o /Users/mac/Desktop/react-native-twilio-video-webrtc/Example/node_modules/react-native/ReactCommon/yoga/yoga/YGNodeList.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
        CompileC /Users/mac/Desktop/react-native-twilio-video-webrtc/Example/ios/build/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/Yoga.build/Objects-normal/x86_64/Yoga.o /Users/mac/Desktop/react-native-twilio-video-webrtc/Example/node_modules/react-native/ReactCommon/yoga/yoga/Yoga.c normal x86_64 c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)

Installing build/Build/Products/Debug-iphonesimulator/Example.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/Example.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

### Environment
- **React Native version**: 0.53.3
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: 1.0.1

**Comment by slycoder** [comment]
Please make sure you're running master.

**Comment by sarikabhimre18** [comment]
Yes, @slycoder I have run mater branch

**Comment by slycoder** [comment]
Did you run npm or yarn install in the example directory?  It looks like you're missing a react native file which should be there

**Comment by sarikabhimre18** [comment]
yes in have run npm install cmd on example directory, I have checked this file is available in xCode.

**Comment by slycoder** [comment]
Oh, I wonder if it's due to casing changes with yoga.

Maybe you need to change the Yoga line to 

```
pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
```

You might need to have a fresh checkout because of the way the mac filesystem handles case changes.
