### ISSUE TITLE
Android build fail

### ISSUE THREAD

**Issue by sarikabhimre18** [blackuy/react-native-twilio-video-webrtc#129]
### Expected behaviour
Run app successfully

### Actual behaviour
Build fail

![screen shot 2018-08-28 at 2 57 13 am](https://user-images.githubusercontent.com/29194144/44687330-9227b380-aa6e-11e8-92d7-dd79e6ad325c.png)

### Environment
- **React Native version**: 0.53.3
- **React Native platform + platform version**: Android 23.0.1

### react-native-twilio-video-webrtc
**Version**: master

can anyone help me on this issues, thanks in advance

**Comment by slycoder** [comment]
Looks like now you'll need to include the maven repo in your build file.

https://stackoverflow.com/questions/46023971/failed-to-resolve-com-android-supportsupport-annotations-26-0-1

**Comment by sarikabhimre18** [comment]
Thanks, @slycoder for help.

**Comment by sarikabhimre18** [comment]
@slycoder after changes I am still facing this issue

**Comment by slycoder** [comment]
You don't seem to have the public maven anywhere in there?

**Comment by sarikabhimre18** [comment]
@slycoder not understand what you say

**Comment by slycoder** [comment]
You need to have a public maven repo included; right now the only maven repo you have is local so gradle is not able to resolve the files it needs.

**Comment by sarikabhimre18** [comment]
![screen shot 2018-09-10 at 1 55 39 pm](https://user-images.githubusercontent.com/29194144/45285635-46124f80-b501-11e8-99a8-5e93b351bb48.png)
now I am facing this issue you have any idea about it @slycoder

**Comment by slycoder** [comment]
It sounds like you're linking against an older (i.e. really old, ~0.12) version of react-native.  Can you confirm that you have things set up in a way so that you're resolving a recent react native (e.g. you're not pulling jars from some location that doesn't have the latest versions published)?
