### ISSUE TITLE
Any event / method to return total number of participants before joining video room.

### ISSUE THREAD

**Issue by farrukhhashmi65** [blackuy/react-native-twilio-video-webrtc#131]
Is there Any method that will us total number of participants before connecting to that room. Actually I want to set the limit of persons in a room that can be dynamic according to requirement. So before joining, I want to check the total number of participants that already exist in the room.

**Comment by slycoder** [comment]
I don't know of any way offhand to do this.  Is this functionality even exposed in the underlying twilio video api?

**Comment by slycoder** [comment]
I see, for some reason this is not exposed on the iOS/Android layers:
https://twilio.github.io/twilio-video-ios/docs/latest/

**Comment by slycoder** [comment]
However, you should be able to just call the rest api via a `fetch`
