### ISSUE TITLE
Build failing on themedReactContext.getCurrentActivity(): Cannot find symbol

### ISSUE THREAD

**Issue by nileshd** [blackuy/react-native-twilio-video-webrtc#135]
### Steps to reproduce
1. Followed steps in instructions for Example App
2. When i am trying to build it for android, it fails with the following error
```
/opt/WORK/GREENMARINE/react-native-twilio-video-webrtc/Example/node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java:155: error: cannot find symbol
        if (themedReactContext.getCurrentActivity() != null) {
                              ^
  symbol:   method getCurrentActivity()
  location: variable themedReactContext of type ThemedReactContext
/opt/WORK/GREENMARINE/react-native-twilio-video-webrtc/Example/node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java:156: error: cannot find symbol
            themedReactContext.getCurrentActivity().setVolumeControlStream(AudioManager.STREAM_VOICE_CALL);
                              ^
  symbol:   method getCurrentActivity()


```
3.

### Expected behaviour
Build should pass

### Actual behaviour
Build fails

### Environment
- **Node.js version**: v8.11.4
- **React Native version**: react-native: 0.44.0 (same as in original example)
- **React Native platform + platform version**: Android

### react-native-twilio-video-webrtc
**Version**: npm version or "master"

I am not really sure what's the problem - Can you someone point me in the right direction on how do I fix this problem?

**Comment by slycoder** [comment]
Can you confirm in your android build that you're pulling in the correct version of react-native?  You can do something like this:

gradlew -q :app:dependencies > dependencies.txt

**Comment by nileshd** [comment]
here's my dependencies.txt 

```
➜  android git:(master) ✗ cat dependencies.txt|grep react-native
+--- com.facebook.react:react-native:+ -> 0.20.1
\--- project :react-native-twilio-video-webrtc
     \--- com.facebook.react:react-native:+ -> 0.20.1 (*)
+--- com.facebook.react:react-native:+ -> 0.20.1
\--- project :react-native-twilio-video-webrtc
     \--- com.facebook.react:react-native:+ -> 0.20.1 (*)
+--- com.facebook.react:react-native:+ -> 0.20.1
\--- project :react-native-twilio-video-webrtc
     \--- com.facebook.react:react-native:+ -> 0.20.1 (*)
+--- com.facebook.react:react-native:+ -> 0.20.1
\--- project :react-native-twilio-video-webrtc
     \--- com.facebook.react:react-native:+ -> 0.20.1 (*)
+--- com.facebook.react:react-native:+ -> 0.20.1
\--- project :react-native-twilio-video-webrtc
     \--- com.facebook.react:react-native:+ -> 0.20.1 (*)

```
I am not sure how react-native v0.20.1 is installed in there. I tried to clean, rebuild and refresh dependencies and it's still at 0.20.1

while in the package.json, it's 		
```
"react": "16.0.0-alpha.6",
"react-native": "0.44.0"
```
Might you know what's causing it?

**Comment by slycoder** [comment]
The android build pulls in react native as a package from one of the maven repos.  How are the repos set up in your gradle?  Most likely you are pointing to a repo that has not been mirroring react native for a long time...

**Comment by nileshd** [comment]
Ah.. I had to add this repository to solve for another missing dependency.

            url 'https://maven.google.com'

I think before I added that, it was breaking with this

```
Could not resolve all dependencies for configuration ':react-native-twilio-video-webrtc:_debugPublishCopy'.
         > Could not find com.android.support:support-annotations:26.1.0.
```

Adding the maven.google.com solved the support-annotations missing dependency.

Would you know a better maven repo that might have the required package and also a newer version of react?

Sorry for all the basic questions. I am a newbie in this technology and slowly learning.

**Comment by slycoder** [comment]
Yeah, you need to have that.  But you can have multiple maven commands to include more repos.

I have the following but YMMV:

```
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
```

**Comment by shamilovtim** [comment]
same problem but on androidX and latest expo
