### ISSUE TITLE
Need response after connect ? Need ROOM SID

### ISSUE THREAD

**Issue by farrukhhashmi65** [blackuy/react-native-twilio-video-webrtc#137]
We need Room SID after connect, we need this to perform recording. 

>  this.refs.twilioVideo.connect

What should we do after connect to get SID of that room ? 
I don't want to use  _onParticipantAddedVideoTrack, nor it is useful.

**Comment by slycoder** [comment]
Interesting.  I'll add the room sid to onRoomDidConnect. Will that work?

**Comment by farrukhhashmi65** [comment]
Yup that will work.

**Comment by farrukhhashmi65** [comment]
Try to update other senerios too.. that sdk provide.
