### ISSUE TITLE
Issues when releaseing the app to Testflight

### ISSUE THREAD

**Issue by viktorlarsson** [blackuy/react-native-twilio-video-webrtc#139]
### Steps to reproduce
1. Initiate a video meeting room and start the video using local development (should be working)
2. Archive the app and ship it to Testflight or something similar and start a video (doesn't work)

### Expected behaviour
Should be able to make a video call

### Actual behaviour
I've been trying to figure out why it refuses to work when shipping it to testflight. The app can see the recievers video (web app), but local video doesn't show up on the app and recievers doesn't get any video or audio. This is only happening on testflight or archived app.  Is it stripping out something that I need?

### Environment
- **Node.js version**: v8.11.4
- **React Native version**: 0.56
- **React Native platform + platform version**: iOS 9.0: iOS 11

### react-native-twilio-video-webrtc
**Version**: npm version or "master" yarn,  master branch

**Comment by slycoder** [comment]
Does this only happen with testflight, or does it also happen if you sideload a production bundle to your device?

**Comment by viktorlarsson** [comment]
I'm on a deadline, and a bit amazed if this is the issue but we are using your example:

https://github.com/blackuy/react-native-twilio-video-webrtc/blob/b5210f7c2efb0b6a0ed05ab02ec240d4e66da1a7/Example/index.js#L140-L143

Everything works fine and dandy, but it breaks (without errors) in production build. Seems to be related to Map. I'm gonna investigate this further.

**Comment by slycoder** [comment]
Sorry for not replying earlier, but in production bundles, you may have to add the relevant polyfills, e.g.,

`
require('core-js/es6/map');
`

These issues are usually deducable from the device logs though.
