### ISSUE TITLE
this.refs.twilioVideo.connect() not working on android

### ISSUE THREAD

**Issue by stanshivam** [blackuy/react-native-twilio-video-webrtc#142]
### Steps to reproduce
1. Simply following the example app
2. Get the access_token from server 
3. trigger this.refs.twilioVideo.connect() //using room name and token

### Expected behaviour
Sould connect the room

### Actual behaviour
The below function gets executed
```
_onRoomDidFailToConnect = (error) => {
    console.log(`Error: ${error}`);
    this.setState({ status: 'disconnected' });
  }
```

### Environment
- **Node.js version**: v8.9.4
- **React Native version**:  0.53.3
- **React Native platform + platform version**: Android 8 (oreo)

### react-native-twilio-video-webrtc
**Version**: master

What couId possibly be doing wrong?

```
_onConnectButtonPress = async () => {
      this.refs.twilioVideo.connect({ roomName: this.state.roomName, accessToken: this.state.token });
      this.setState({ status: 'connecting' });
  }
```
```
_onRoomDidFailToConnect = (error) => {
    console.log(`Error: ${error}`); // giving {reason: ''}
    this.setState({ status: 'disconnected' });
  }
```

**Comment by zasyadev** [comment]
Same issue. Whats going wrong?

**Comment by stanshivam** [comment]
Rooms were not getting created automatically, I have created the room from server and the used connect function, I worked So I am closing the issue

**Comment by weezyboyaxy** [comment]
> Rooms were not getting created automatically, I have created the room from server and the used connect function, It worked So I am closing the issue

can you give a snippet of your code .....
because in my case , the participants are getting connected first time , but second time they are not able to connect after disconnecting from first call.
