### ISSUE TITLE
Show incoming call screen when push notification is recieved

### ISSUE THREAD

**Issue by stanshivam** [blackuy/react-native-twilio-video-webrtc#143]
Hi @blackuy

I have successfully implemented programable video using your library and I used Twilio notify with fcm to send push notification, everything works really good and thank you very much for great library.
Now I have a problem,  **how to show incoming call screen** when I recieve push notification. Do I need to include any external library for the same.

**Comment by viktorlarsson** [comment]
You need to implement https://github.com/ianlin/react-native-callkit for iOS and follow this guide https://hashnode.com/post/belka-we-build-digital-products-callkit-for-android-in-react-native-cj7ci2jug009fu8wug947c9cd

**Comment by viktorlarsson** [comment]
@stanshivam Yep!

**Comment by joshwinter** [comment]
@stanshivam Did you have any luck getting something working? I'm trying to work through this too. Thanks!

**Comment by saikiranoptisol** [comment]
@stanshivam  have done this. need help how to get notified when we get video call. If i check above framework for call kit they are using  only phone numbers to do. but i cant call using phone  number in my app

**Comment by AarshApple** [comment]
Did any of you guys  have any luck getting callkit working?
