### ISSUE TITLE
Remote Video isn't appearing after Integration of react-native-twilio-video-webrtc in react Native application

### ISSUE THREAD

**Issue by emphilip** [blackuy/react-native-twilio-video-webrtc#145]
### Steps to reproduce
1. Follow steps for: "If you do NOT use CocoaPods to manage your react native packages."
2. Create a Twilio Access Token to join a room from mobile
3. Separate Client Application (Web) joins the room, then mobile joins

### Expected behaviour
- Local and Remote Video appears on both clients (iOS using 'react-native-twilio-video-webrtc')
- Audio from both sides appears without a problem

### Actual behaviour
- Remote Video from desktop doesn't appear on iOS client
- Audio works fine
- Client on Web Application can see video from mobile application

### Environment
- **Node.js version**: 8.12.0
- **React Native version**: 0.57.1
- **React Native platform + platform version**:  react-native-cli: 2.0.1  targetting: iOS 10.0

### react-native-twilio-video-webrtc
**Version**: npm version

**Comment by slycoder** [comment]
Do you see the remote track being added on the iOS side?

**Comment by emphilip** [comment]
@slycoder sorry for the delay, I did, but I wasn't receiving the video from the feed.  However, I'd added my own bridging to header and implemented the video call natively to get this to work now. 

I'm wrapping a few things up but I'll jump back on this thread to provide more details, and if necessary, make a PR for you to check out in a couple weeks.

Thanks

**Comment by slycoder** [comment]
Thanks.  A PR would be welcome!  Really curious to hear what the underlying issue was.

**Comment by stevelizcano** [comment]
> @slycoder sorry for the delay, I did, but I wasn't receiving the video from the feed. However, I'd added my own bridging to header and implemented the video call natively to get this to work now.
> 
> I'm wrapping a few things up but I'll jump back on this thread to provide more details, and if necessary, make a PR for you to check out in a couple weeks.
> 
> Thanks

Hi emphilip,

Was this ever merged? I am having the same issue.

Video shows on the web/desktop version, but not showing up on the device.
