### ISSUE TITLE
onParticipant{Enabled,Disabled}VideoTrack not being called?

### ISSUE THREAD

**Issue by quachsimon** [blackuy/react-native-twilio-video-webrtc#150]
### Environment
- **React Native version**: v0.55.4

### react-native-twilio-video-webrtc
**Version**: 1.0.2

I may be approaching this the wrong way so correct me if I am wrong.

When a participant joins a twilio call, the `onParticipantAddedVideoTrack` is called and I set up the corresponding `participantSid` and `videoTrackSid` which shows the video properly. 

However, when the participant disables their local video (`setLocalVideoEnabled`), should the `onParticipantDisabledVideoTrack` be called and `onParticipantEnabledVideoTrack` when they enable their video? It isn't quite clear to me how these two are called from the docs (unless I am missing something). 

From the source code for onParticipantEnabledVideoTrack: 
```
Called when a video track has been enabled
```

I guess my question is how do we enable/disable video tracks properly? Is it similar to add/remove or are they handled differently?

Any insight would be great.

**Comment by slycoder** [comment]
I'd first make sure you're using master (1.0.2 is quite old). 

And just to be clear, are you asking about enabling/disabling of the local participant's tracks, or receiving events about remote participants enabling/disabling their tracks?

**Comment by quachsimon** [comment]
@slycoder, thanks for the prompt response.

The latter, I'm asking about receiving events about remote participants enabling/disabling their tracks (more specifically, their video track so when they turn on/off their camera). 

Just to clarify, the local track is simply calling something like `setLocalVideoEnabled` correct?

How do I get on master? I followed the docs and did: 
```yarn add https://github.com/blackuy/react-native-twilio-video-webrtc```

Thanks!

**Comment by quachsimon** [comment]
Interesting, so by calling `setLocalVideoEnabled` on the local device, it does trigger the `onParticipant{Enabled,Disabled}VideoTrack` now.  I am not sure why it was not working prior... this can be closed now (:

**Comment by naro-hooli** [comment]
It seems that onParticipantEnabledVideoTrack is not being called when calling setLocalVideoEnabled. Instead, onParticipantAddedVideoTrack is called. Is this issue just on my end or is it a new implementation on the package?
