### ISSUE TITLE
Is there any way to check whether the LocalView Camera is using the rear facing camera vs front facing camera?

### ISSUE THREAD

**Issue by varuncarkey** [blackuy/react-native-twilio-video-webrtc#159]
Did not find any reference to this in the docs. From what I can see, flipCamera() doesn't return any sort of state to check for which camera is currently in use. Any help would be appreciated, thanks!

**Comment by slycoder** [comment]
There's currently no way to get this explicitly.  The camera almost always starts out front-facing so if you keep track of the number of flips it should hopefully be a close-enough approximation.

**Comment by varuncarkey** [comment]
Thanks! That's not a bad approach.
