### ISSUE TITLE
Android: Illegal number of arguments for 'updateHotspot' command

### ISSUE THREAD

**Issue by rajesh1158** [blackuy/react-native-twilio-video-webrtc#16]
I installed the master branch which has the latest android merge by @slycoder. My app itself successfully compiles, and I managed to get the UI up. I see connect and disconnect buttons (blue color). When I click on the connect button, I get an error `Illegal number of arguments for 'updateHotspot' command`. I was expecting that the video call will start.

Digging more into the code, it appears that the react native codebase has the above error message defined in 2 files: RCTViewManager.java and ReactViewManager.java. And it happens because the receiveCommand() annotated as overridden in the CustomTwilioVideoViewManager.java is somehow not getting overridden. What could be the issue?

**Comment by slycoder** [comment]
Hi, thanks for reporting this.  I'll be working on getting the example app up and running either later today or tomorrow so stay tuned.  But if you have a patch it is definitely welcome!

**Comment by bilby91** [comment]
@rajesh1158 Can you check if the problem is still present with master branch ?

**Comment by rajesh1158** [comment]
I checked with master branch only. I got an error when I clicked on connect
button. Some issue related to overriding of receiveCommand() function.

On Jul 15, 2017 23:56, "Martín Fernández" <notifications@github.com> wrote:

@rajesh1158 <https://github.com/rajesh1158> Can you check if the problem is
still present with master branch ?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/blackuy/react-native-twilio-video-webrtc/issues/16#issuecomment-315552883>,
or mute the thread

**Comment by slycoder** [comment]
I have a guess for what might be going on but I don't have a local repro.  @rajesh1158 do you have a minimal example you can share?

**Comment by rajesh1158** [comment]
@slycoder  I do not have the repo on github, but below is the sample js code I used to use this module:

    `
    import React, { Component } from 'react'
    import {
      View,
      Button
    } from 'react-native'

    import {
      TwilioVideoParticipantView,
      TwilioVideoLocalView,
      TwilioVideo
    } from 'react-native-twilio-video-webrtc'

    export default class VideoTry extends Component {
      startCall = ({accessToken}) => {
      this.refs.twilioVideo.startCall({accessToken});
    }

    endCall = () => {
      this.refs.twilioVideo.endCall();
    }

    _onConnectButtonPress = () => {
      this.startCall({accessToken: "ACCESS TOKEN STRING HERE"});
    }

    _onDisconnectButtonPress = () => {
      this.endCall();
    }


    render() {
      return (
      <View style={{ flex: 1 }}>
        <TwilioVideo ref="twilioVideo" />

        <TwilioVideoLocalView style={{flex: 1, backgroundColor: '#FFFF00'}} />

        <TwilioVideoParticipantView style={{flex: 1, backgroundColor: '#FF00FF'}} />

        <Button
          title="Connect"
          style={{fontSize: 20, padding: 10, color: 'green'}}
          onPress={this._onConnectButtonPress} />

        <Button
          title="Disconnect"
          style={{fontSize: 20, padding: 10, color: 'red'}}
          onPress={this._onDisconnectButtonPress} />

      </View>
    );
    }
    }
`

**Comment by bilby91** [comment]
@rajesh1158 Have tried using this branch #20 ?

**Comment by rajesh1158** [comment]
@bilby91 @slycoder  I tried it today. It gives the same error: Illegal number of arguments for 'updateHotspot' command.

**Comment by rajesh1158** [comment]
@bilby91  @slycoder It actually worked. My bad, I forgot to setup the project in my app's <app_path>/android/settings.gradle and <app_path>/android/app/build.gradle. After I did that, the video chat worked.

We still have to put the action buttons for muting audio and hiding video.

**Comment by slycoder** [comment]
That's great to hear!

setLocalVideoEnabled and setLocalAudioEnabled should already be in working order.
