### ISSUE TITLE
Not showing video on Safari

### ISSUE THREAD

**Issue by graphee-gabriel** [blackuy/react-native-twilio-video-webrtc#160]
### Steps to reproduce
1. Set up a `group` room
2. Join it with a safari browser
3. Join it from a react native app (testing currently with an iOS device)

### Expected behaviour
Both device should send and receive video from each other.
I should see the iPhone user in the safari window, and vice versa.

### Actual behaviour
I only see the Safari user on the iPhone screen.
I don't see the iPhone user on the Safari screen.
I do see the iPhone video preview, but it does not seem then to arrive on the Safari screen.

### Environment
- **Node.js version**: v10.10.0
- **React Native version**: https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz
- **React Native platform + platform version**: iOS 12.0
- Safari Version 12.0.1 (14606.2.104.1.1)

### react-native-twilio-video-webrtc
**Version**: git "master"

It seems that i am not sending the video in h264 for the Safari browser to be able to render it (as stated here: https://twilio.com/docs/video/developing-safari-11).
Is there a way to force the mobile app to use h264 when streaming, so that safari receives the video?

Thank you for your help

**Comment by slycoder** [comment]
I would imagine the app to just use whatever the room is set to.  Are you sure you've set up the videoCodecs property when setting up the room?

**Comment by graphee-gabriel** [comment]
Hello, we forced the rooms to use h264, and it seems that it resolves the issue.
I'll close it then, thank you!
