### ISSUE TITLE
Allow video component to be resized by source proportions

### ISSUE THREAD

**Issue by Praxey** [blackuy/react-native-twilio-video-webrtc#163]
### Steps to reproduce
1. Create a usable instance of TwilioVideoParticipantView or TwilioVideoLocalView
2. Attempt to style it with resizeMode: contain or cover
3. See that it doesn't change

---
It seems the default sizing for these video components is "cover" - meaning the video is scaled to completely fill the window, even if that requires cropping on the vertical or horizontal end.

However, sometimes it is necessary to resize the video so the original proportions are showing (even though the entire containing window is not filled). In normal react, this is done by object-fit: "contain" in a video element. My understanding is that react native uses resizeMode for the same.

I am trying to figure out if something similar is possible with TwilioVideoParticipantView or TwilioVideoLocalView, and if not, request this upgrade.

1. How can I use styling to resize the video (cover, contain, stretch, etc...)?
2. How can I at least least get the original video dimensions on the fly? (which would allow customization of the window size.)

React Native .57
All mobile environments.

**Comment by slycoder** [comment]
1.) `resizeMode` is only applicable to react native `Image`.  It shouldn't be too hard to implement here however (let me know if that's something you'd be interested in helping out on; I'm pretty slammed at the moment).
2.) You can get the dimensions via `getStats` (note that dimensions can change depending on various factors, e.g. if the remote side rotates their device, due to network connections, etc.).

**Comment by Praxey** [comment]
Hi - thanks for the response. Unfortunately, adding this feature would be beyond my current skill level. 

Regarding your second point... when I attempt to call getStats, (this.refs.twilioVideo.getStats()), I receive an object back with localAudioTrackStats, localVideoTrackStats, remoteAudioTrackStats, and remoteVideoTrackStats.

Since it is a one to one call, each of these has one entry. However, neither the local video track stats, nor the remote video track stats show the video dimensions. Both instead show simply: height: 0, width: 0.

Any thoughts?

**Comment by Praxey** [comment]
I figured this out. The object in the console was resetting after the call, showing the zeros. However, when I look at the console during an active call it does show the correct dimensions. 

Unfortunately, I am not able to use the dimension stats in the way I had hoped, since the rendering dimensions have already been set in the native component, so any resizing of the containing view (in react native) just obfuscates more of the window (instead of resizing the actual image).

I am going to try to figure out how to implement a resizing feature on the package.

**Comment by Praxey** [comment]
Hi slycoder - I ultimately did figure this out. I made a new prop called scaleType which takes "fit" to alter the stream to fit inside the containing boundaries without cropping. Or, by default, it keeps the "fill" variable (which is the current default). Everything is working well, both IOS and Android.  Happy to submit my changes if you'd like, but not sure how...

**Comment by slycoder** [comment]
That's awesome.  If you get all your commits on a fork of this repo, then you should be able to just open up a PR in github and then we can review and merge your changes in!

**Comment by Praxey** [comment]
Thanks! Yeah I'm a total novice, but I decided to suck it up and work my way through it so I could learn. I tried to do the pull just now. Let me know what you think.

**Comment by josefpohl** [comment]
Hi @Praxey , Did this ever get merged into the master? I am having a similar issue where a screen share element is being cut off.  I didn't see a prop setting for this in the current master.  But I might be looking in the wrong place.
Thanks,
Joe

**Comment by josefpohl** [comment]
@Praxey , never mind... Being a bit more awake this morning I did find it.  Works great.  
@slycoder can I write up a quick statement for the documentation on this?
Thanks!
Joe

**Comment by slycoder** [comment]
Sure thing, thanks @josefpohl

**Comment by aliabbasmalik8** [comment]
@slycoder is there any update regarding this issue?

**Comment by slycoder** [comment]
This has been in master for a while; you can just set the scaleType prop.

**Comment by krisbaum74** [comment]
hi, are there any docs outlining the full set of props supported? just found this looking through the PR's...

**Comment by slycoder** [comment]
Yeah sorry about that; the docs have fallen behind features that have been added over time =(.

**Comment by josefpohl** [comment]
And @slycoder , I apologize I have not had the time to get the documentation PR put together for the issues that I know about.  I will commit to getting this to you ASAP.

**Comment by slycoder** [comment]
no worries, you rock @josefpohl .
