### ISSUE TITLE
Audio State remains on 'Call' after un-mounting the view

### ISSUE THREAD

**Issue by graphee-gabriel** [blackuy/react-native-twilio-video-webrtc#164]
### Steps to reproduce
The issue is on both android and ios, but i'll write how to reproduce it easily on android:
1. Open your app and push the volume button. You should have normal volume control (notifications volume for example)
2. Start a call using `<TwilioVideo />`
3. Change the volume, it should now control the "Call" volume
4. Exit the current screen, un-mounting the `<TwilioVideo />` component. Call `.disconnect()` on your screen's `componentWillUnmount()` function.
5. The call stops. Press the volume button. You are still controlling the 'Call' Volume. It still ducks/stops any other audio media playing.
6. Press home button to exit the app. Press volume. You are now out of the 'Call' state an control again the notifications volume (normal state)
7. Go back to the app, You are back in 'Call' state, it stops your current music playing for instance (even if you are not connected to the twilio room anymore).

### Expected behaviour
Disconnecting from a Twilio Room should notify the system that the call is over in order for it to update the app's current audio state.

### Actual behaviour
The phone still think you are in a call whenever the app is on foreground

### Environment
- node js v10.10.0:
- "react-native": "https://github.com/expo/react-native/archive/sdk-30.0.0.tar.gz",
- Android 8.1.0 and iOS 12.1

### react-native-twilio-video-webrtc
"react-native-twilio-video-webrtc": "github:blackuy/react-native-twilio-video-webrtc#master",

**Comment by YuePing1104** [comment]
Hello, how did you realize video call on react-native-webrtc? Do you have a demo you wrote to share

**Comment by graphee-gabriel** [comment]
Hey @slycoder, I kinda struggled for a long time, tried different things, it's better, in the sense that it clearly switches mode after i called my updated version of audio focus, but still the volume controller remain on calling mode (phone icon), even tough android says we switched back from audio mode `IN_COMMUNICATION` to `NORMAL`.
The good thing is that if I go out of the app, the volume is back in normal mode (ringtone setting), but when i come back in the app, the volume is back on the phone icon.
Being on 8.1.0, I also implementend the > SDK 26 way in case. It's better than before, but i wouldn't say perfect.

Would be worth checking it on a < SDK 26, should work as before but at least to be sure.

Also i didn't have time to check why we have the same problem on iOS. Would you have some time to look into it ?

Thank you have a great day !

```

private AudioFocusRequest audioFocusRequest;
private AudioAttributes playbackAttributes;
private Handler handler = new Handler();

public void disconnect() {
    if (room != null) {
        room.disconnect();
    }
    if (localAudioTrack != null) {
        localAudioTrack.release();
        localAudioTrack = null;
    }
    if (localVideoTrack != null) {
        localVideoTrack.release();
        localVideoTrack = null;
    }
    setAudioFocus(false);
}

private void setAudioFocus(boolean focus) {
    if (focus) {
        previousAudioMode = audioManager.getMode();
        // Request audio focus before making any device switch.
        if (android.os.Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
            audioManager.requestAudioFocus(this,
                    AudioManager.STREAM_VOICE_CALL,
                    AudioManager.AUDIOFOCUS_GAIN_TRANSIENT);
        } else {
            playbackAttributes = new AudioAttributes.Builder()
                    .setUsage(AudioAttributes.USAGE_VOICE_COMMUNICATION)
                    .setContentType(AudioAttributes.CONTENT_TYPE_SPEECH)
                    .build();
            audioFocusRequest = new AudioFocusRequest
                    .Builder(AudioManager.AUDIOFOCUS_GAIN_TRANSIENT)
                    .setAudioAttributes(playbackAttributes)
                    .setAcceptsDelayedFocusGain(true)
                    .setOnAudioFocusChangeListener(this, handler)
                    .build();
            audioManager.requestAudioFocus(audioFocusRequest);
        }
        /*
         * Use MODE_IN_COMMUNICATION as the default audio mode. It is required
         * to be in this mode when playout and/or recording starts for the best
         * possible VoIP performance. Some devices have difficulties with
         * speaker mode if this is not set.
         */
        audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION);
        audioManager.setSpeakerphoneOn(!audioManager.isWiredHeadsetOn());
        getContext().registerReceiver(myNoisyAudioStreamReceiver, intentFilter);

    } else {
        if (android.os.Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
            audioManager.abandonAudioFocus(this);
        } else {
            audioManager.abandonAudioFocusRequest(audioFocusRequest);
        }

        audioManager.setSpeakerphoneOn(false);
        audioManager.setMode(previousAudioMode);
        try {
            getContext().unregisterReceiver(myNoisyAudioStreamReceiver);
        } catch (Exception e) {
            // already registered
        }
    }
}

```

**Comment by graphee-gabriel** [comment]
here you go for PR, i kinda messed up and am not so used to git, so it's in 2 PR
https://github.com/blackuy/react-native-twilio-video-webrtc/pull/180
https://github.com/blackuy/react-native-twilio-video-webrtc/pull/181

First one is the updated code, the second one is the build.gradle updated to necessary SDK 27

**Comment by reinhardholl** [comment]
Related to https://github.com/blackuy/react-native-twilio-video-webrtc/issues/397

**Comment by slycoder** [comment]
Thanks for the pointer @reinhardholl .  I'll close this issue out and we can focus the discussion on #397.
