### ISSUE TITLE
Android version doesn't support participant's added/removed audio callbacks

### ISSUE THREAD

**Issue by sergeylaptev** [blackuy/react-native-twilio-video-webrtc#168]
### Steps to reproduce
1. Provide `onParticipantAddedAudioTrack` or `onParticipantRemovedAudioTrack` props to the `TwilioVideo` component
2. Join the room on android device and wait while someone else join
3. Whether opponent has enabled microphone or not Android user won't get invoked respective callbacks. `onParticipantEnabledAudioTrack` and `onParticipantDisabledAudioTrack` callbacks works just fine (when opponent toggles his mic while staying in the room)

### Expected behaviour
`onParticipantAddedAudioTrack` and `onParticipantRemovedAudioTrack` callback should get invoked whenever room participants adds/removes his microphone

### Actual behaviour
Android completely ignores `onParticipantAddedAudioTrack` and `onParticipantRemovedAudioTrack` props

### Environment
- **Node.js version**: v11.2.0
- **React Native version**: v0.57.8
- **React Native platform + platform version**: iOS 12.0

### react-native-twilio-video-webrtc
**Version**: "master"

**Comment by slycoder** [comment]
Oops, this is an oversight.  Sorry about that.  I can try to fix this later today.

**Comment by Blackening999** [comment]
Thank you @slycoder !!

**Comment by slycoder** [comment]
Can you guys try the attached PR and see if that works for you?

**Comment by sergeylaptev** [comment]
Yup, will check tomorrow. Thank you

**Comment by sergeylaptev** [comment]
The app crashes on start call. onParticipantAddedVideoTrack fires and in a couple seconds this crash occurs
![image](https://user-images.githubusercontent.com/5740795/51699528-01093880-201e-11e9-9a3e-3b252effbd44.png)

**Comment by slycoder** [comment]
My bad, fix coming shortly,

**Comment by slycoder** [comment]
I just pushed a commit to the branch which should fix it.

**Comment by sergeylaptev** [comment]
@slycoder Now it works, thank you! Looking forward to get this from the master branch
