### ISSUE TITLE
Upgrade package to Android 3x

### ISSUE THREAD

**Issue by Praxey** [blackuy/react-native-twilio-video-webrtc#172]
Hello,

Currently, this package is using Twilio Video Android v. 2.1.0, released May of last year. 

Unfortunately there is a significant bug which prevents calls between this version and firefox:
https://github.com/twilio/twilio-video.js/issues/402. The room connects, but no streams are transmitted.

I contacted Twilio, and apparently the new version: Android 3x solves this issue. 

This is the guide to upgrade from 2x to 3x: https://www.twilio.com/docs/video/migrating-2x-3x-android-30 

Can someone upgrade the package? I spent a few hours messing around with it today, but couldn't figure it out.

**Comment by Praxey** [comment]
actually I was able to implement the upgrade myself. Please let me know if you would like me to submit a pull with this upgrade. It's relatively easy.

**Comment by slycoder** [comment]
Sure, a PR would be very welcome!
