### ISSUE TITLE
TwilioVideoPreviewManager.java:33: error: unclosed character literal 

### ISSUE THREAD

**Issue by carlmagumpara** [blackuy/react-native-twilio-video-webrtc#175]
### Steps to reproduce
1. Update react-native-twilio-video-webrtc to newest version
2. yarn run android

### Expected behaviour
Tell us what should happen

### Actual behaviour
Error on bundle

### Environment
- **Node.js version**: v8.11.1 
- **React Native version**: 0.58.3
- **React Native platform + platform version**: Android *

### react-native-twilio-video-webrtc
**Version**: "master"

Heres my logs

/home/carlmagumpara/Desktop/lexmeet-mobile-app-v1/node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/TwilioVideoPreviewManager.java:33: error: unclosed character literal
      if(scaleType.equals('fit')) {
                          ^
/home/carlmagumpara/Desktop/lexmeet-mobile-app-v1/node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/TwilioVideoPreviewManager.java:33: error: ')' expected
      if(scaleType.equals('fit')) {
                            ^
/home/carlmagumpara/Desktop/lexmeet-mobile-app-v1/node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/TwilioVideoPreviewManager.java:33: error: unclosed character literal
      if(scaleType.equals('fit')) {
                              ^
/home/carlmagumpara/Desktop/lexmeet-mobile-app-v1/node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/TwilioVideoPreviewManager.java:33: error: ';' expected
      if(scaleType.equals('fit')) {
                                ^
/home/carlmagumpara/Desktop/lexmeet-mobile-app-v1/node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/TwilioVideoPreviewManager.java:35: error: 'else' without 'if'
      } else {
        ^
/home/carlmagumpara/Desktop/lexmeet-mobile-app-v1/node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/TwilioRemotePreviewManager.java:29: error: unclosed character literal
      if(scaleType.equals('fit')) {
                          ^
/home/carlmagumpara/Desktop/lexmeet-mobile-app-v1/node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/TwilioRemotePreviewManager.java:29: error: ')' expected
      if(scaleType.equals('fit')) {
                            ^
/home/carlmagumpara/Desktop/lexmeet-mobile-app-v1/node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/TwilioRemotePreviewManager.java:29: error: unclosed character literal
      if(scaleType.equals('fit')) {
                              ^
/home/carlmagumpara/Desktop/lexmeet-mobile-app-v1/node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/TwilioRemotePreviewManager.java:29: error: ';' expected
      if(scaleType.equals('fit')) {
                                ^
/home/carlmagumpara/Desktop/lexmeet-mobile-app-v1/node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/TwilioRemotePreviewManager.java:31: error: 'else' without 'if'
      } else {
        ^
10 errors

**Comment by carlmagumpara** [comment]
i think change all scaleType.equals('fit') to scaleType.equals("fit")

**Comment by slycoder** [comment]
There's a PR already #174

**Comment by slycoder** [comment]
I can't approve my own PR; if you pull my branch and put it up as a PR I can approve and merge it.
