### ISSUE TITLE
TwilioRemotePreviewManager.java:32: error: package RendererCommon does not exist

### ISSUE THREAD

**Issue by carlmagumpara** [blackuy/react-native-twilio-video-webrtc#176]
### Steps to reproduce
1. Update react-native-twilio-video-webrtc to newest version
2. yarn run android

### Actual behaviour
Error on bundle

### Environment
- **Node.js version**: v8.11.1
- **React Native version**: v8.11.1
- **React Native platform + platform version**:  Android *

### react-native-twilio-video-webrtc
**Version**: "master"

LOGS:
/home/carlmagumpara/Desktop/lexmeet-mobile-app-v1/node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/TwilioRemotePreviewManager.java:30: error: package RendererCommon does not exist
        view.setScalingType(RendererCommon.ScalingType.SCALE_ASPECT_FIT);
                                          ^
/home/carlmagumpara/Desktop/lexmeet-mobile-app-v1/node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/TwilioRemotePreviewManager.java:32: error: package RendererCommon does not exist
        view.setScalingType(RendererCommon.ScalingType.SCALE_ASPECT_FILL);
                                          ^
Note: /home/carlmagumpara/Desktop/lexmeet-mobile-app-v1/node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/carlmagumpara/Desktop/lexmeet-mobile-app-v1/node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/CustomTwilioVideoViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

missing 
import org.webrtc.RendererCommon;

**Comment by slycoder** [comment]
Just pushed a commit to that same PR. #174
