### ISSUE TITLE
Can’t Example app Open iOS simulator

### ISSUE THREAD

**Issue by Parthasarath** [blackuy/react-native-twilio-video-webrtc#177]
### Steps to reproduce
`1.	git clone https://github.com/blackuy/react-native-twilio-video-webrtc.git`
`2.     cd Example`
`3.	npm install `
`4.     cd ios && pod install`
5.	open Example.xcworkspace
6.     run the app Xcode(App installed successfully, but i got error index.ios.js file not found)

### Expected behaviour
Execute the example without errors

### Actual behaviour
I get error:
Can’t find entry file index.ios.js in any of the roots:[my location path]
![example_app](https://user-images.githubusercontent.com/45994320/51971663-b7966e80-249f-11e9-8124-0bcf04021cfe.png)
### Environment
 •	Node.js version:v11.4.0
	•	React Native version: 0.44.0
	•	React Native platform + platform version: iOS 10.14.2

### react-native-twilio-video-webrtc
**Version**: npm version or "master"

**Comment by carlmagumpara** [comment]
change 
jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
to
jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
in AppDelegate.m

**Comment by Parthasarath** [comment]
> change
> jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index.ios" fallbackResource:nil];
> to
> jsCodeLocation = [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
> in AppDelegate.m

Thanks for your response,now it works fine,But i got new issue  #[https://github.com/facebook/react-native/issues/13390](url), i have changed react and react-native latest version but still above issue not fixed,Do you know how to fix this one?@carlmagumpara
