### ISSUE TITLE
ERROR: In <declare-styleable> VideoView, unable to find attribute overlaySurface

### ISSUE THREAD

**Issue by prameetc** [blackuy/react-native-twilio-video-webrtc#183]
I am getting this error while building on android

`ERROR: In <declare-styleable> VideoView, unable to find attribute overlaySurface`

My gradle 

```
compileSdkVersion 26
    buildToolsVersion "26.0.2"

    defaultConfig {
        applicationId "com.sprung"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 68
        multiDexEnabled true
        versionName "0.0.13"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
```

The Build fails because of this error

### Environment
- **Node.js version**: 8.11.3
- **React Native version**: 0.53.3

### react-native-twilio-video-webrtc
**Version**: npm version or "master"

**Comment by slycoder** [comment]
Can you try updating your gradle file per the instructions here: 

https://github.com/blackuy/react-native-twilio-video-webrtc/pull/179

And see if that fixes it?  If so I'll update the docs/example.

**Comment by slycoder** [comment]
Actually, I'm not at all sure how you'd run into this since `declare-styleable` is not used by us anywhere.

**Comment by rupalpatel0008** [comment]
I removed `android.enableAapt2=false` from my gradle.properties and added following to the app/buil.gradle:
`
android: {
   ...
   compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
    dexOptions {
        jumboMode true
    }
}
`
Now I am not getting this error.

**Comment by prameetc** [comment]
Updating to API 28 solved the issue, closing

**Comment by lidio601** [comment]
In my case I solved this by add a file here `android/app/src/main/res/values/attrs.xml`

```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <attr name="overlaySurface" format="boolean" />
</resources>
```

as suggested here https://github.com/twilio/video-quickstart-android/issues/479
