### ISSUE TITLE
cannot run the app in iOS

### ISSUE THREAD

**Issue by AarshApple** [blackuy/react-native-twilio-video-webrtc#185]
### Steps to reproduce
1.Clone the repo and cd Example
2.npm install and pod install
3.Open Example.xcworkspace and run the app 

### Expected behaviour
The app should be installed and run correctly

### Actual behaviour
The app installed in the device but does not run and gives me npm error 

EMFILE: too many open files, watch
{"errno":-24,"syscall":"watch","code":"EMFILE","filename":null}
Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28) 

### Environment
- **Node.js version**:v10.14.1
- **React Native version**:0.44.0 (as in the example/package.json)
- **React Native platform + platform version**: iOS (greater than 9.0)

**Comment by slycoder** [comment]
This sounds like a potential problem with your environment.  See here:

https://github.com/facebook/create-react-app/issues/4540

Make sure you have watchman installed.

**Comment by AarshApple** [comment]
Yes that was the problem and so closing this issue now. I just had to install watchman.!
