### ISSUE TITLE
Cannot run the application in any of my system

### ISSUE THREAD

**Issue by AarshApple** [blackuy/react-native-twilio-video-webrtc#190]
### Steps to reproduce
1. react-native init Example --version react-native@0.57.7
2. npm add https://github.com/blackuy/react-native-twilio-video-webrtc and keep the code of index.js file
3.Run the app by react-native-run-android

### Expected behaviour
The app should run without any error and the video call should work

### Actual behaviour
I am getting the error while building the app stating " Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/name/.gradle/caches/transforms-1/files-1.1/video-android-3.2.1.aar/6f252e01e1ce7ed9959098b8950ea772/jars/classes.jar "

### Environment
- **Node.js version**: 10.14.1 and 10.14.2
- **React Native version**: 0.57.7
- **React Native platform + platform version**: Android 8.1.0

### react-native-twilio-video-webrtc
**Version**: As i did npm add https://github.com/blackuy/react-native-twilio-video-webrtc I guess I am using the master version

**Comment by AarshApple** [comment]
Though i was able to run the app, being a newbie in react native i do not have much knowledge about requireNativeComponents and how to use it and it seems i am stuck at that error.

**Comment by slycoder** [comment]
Can you verify that you have

```
android {
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
}
```

in your `build.gradle`?

**Comment by AarshApple** [comment]
Yea that did the trick somehow thank you so much now i am able to run the app but the console shows me an error of invalid access token. Can you brief me on how can i generate a token?

**Comment by slycoder** [comment]
It would probably behoove you to familiarize yourself with the twilio video docs.

https://www.twilio.com/docs/video/getting-started#2-get-an-api-key
