### ISSUE TITLE
Show incoming call screen when notification is recieved ?

### ISSUE THREAD

**Issue by AarshOza** [blackuy/react-native-twilio-video-webrtc#193]
Hi @blackuy

I have successfully implemented programable video using your library, everything works really good and thank you very much for great library.
Now I have a problem, how to show incoming call screen when I recieve push notification.

**Comment by hspindell** [comment]
https://www.npmjs.com/package/react-native-callkit

**Comment by jedabero** [comment]
react-native-callkit is iOS only

**Comment by ntvinhit** [comment]
Twilio is build for video conference, not video call.
So if you want it acts like video call, you need to set it up yourself.

How?
iOS: Callkit (like above)
Android: Firebase message + Deeplink (Fire a message, then open a link to open your app), or you can choose another method to open your app.

**Comment by Balasnest** [comment]
@AarshOza Did you manage to get it to work? Let me your thoughts and challenge if it's converted into VoIP call.

**Comment by AarshOza** [comment]
@Balasnest I indeed managed to make it work with a combination of this package as @hspindell mentioned RN Callkit it turned out to be a great combination.
