### ISSUE TITLE
Call echo when Pixel2 or Pixel2 XL phones are on the call.

### ISSUE THREAD

**Issue by paul-apacio** [blackuy/react-native-twilio-video-webrtc#194]
### Steps to reproduce
Run a call via a Pixel 2 or Pixel 2 Excel

### Expected behaviour
Clear two way calling

### Actual behaviour
The pixel produces echos on the other device. The echo is not evident when the devices do not include a Pixel 2 or XL

There is a suggested fix for this for the android version, but as far as I can tell, no way to fix this via the RN plugin: https://github.com/twilio/video-quickstart-android/issues/221

**Comment by slycoder** [comment]
You can call `disableOpenSLES` on the twilioVideo ref.

**Comment by paul-apacio** [comment]
Do you have an example of how to call this? Do I call it on the participant view ref?

**Comment by slycoder** [comment]
You can call it on the `<TwilioVideo>` component's ref.
