### ISSUE TITLE
build failures using CocoaPods 

### ISSUE THREAD

**Issue by josefpohl** [blackuy/react-native-twilio-video-webrtc#196]
**Steps to reproduce**.  
Here are the pertinent details:
React: 16.8.3
React-Native: 0.59.8
Xcode: 10.2.1
react-native-twilio-video-webrtc: 1.0.2 (pulled from repository)

The issues are covered in a number of different issue reports here and the error messages vary.  None exactly covered what I was seeing.
After several false starts I think I got my pod file correct.
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PROJECTNAME' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PROJECTNAME
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    'RCTVibration',
    'RCTSettings',
    'RCTAnimation',
    'RCTLinkingIOS',
    'RCTImage'
    ]
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'react-native-twilio-video-webrtc', path: '../node_modules/react-native-twilio-video-webrtc'

  target 'PROJECTNAME' do
    inherit! :search_paths
    # Pods for testing
  end

end

```

I am using cocoa pods do NOT try to manually add the library and search paths. Simply do the pod install.

After doing this though I was still getting a link error. This is from `react-native run-ios` but the error is the same in Xcode.
```
info ld: library not found for -lTWReactNativeTwilioVideoWebrtc

info clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I am not sure if this was an Xcode error/bug or not.  The library appeared to have been added to the list of libraries.  But it was odd that there was no content under that particular listing.
To resolve this, I removed the library and then re-added the Xcode project from the node_modules directory, react-native-twilio-video-webrtc.

I then rebuilt and every thing seemed to build initially but subsequent Xcode builds failed with the same linker error.  As did `react-native run-ios`.   
This is very similar to the #68  except that it only seemed to work once in my case.
** Expected behaviour **
App would build and launch
** Actual behavior **
See above linker error.

I have tried doing the library several times, this is also my second go around for this with similar results.  (wiping out derived data for instance did not work) 

Does anyone have any thoughts on other things I might try? Sadly I am woefully new at working with cocoa pods. Thanks!

**Comment by josefpohl** [comment]
Hi there,
I am not convinced that I have resolved this issue at this point but a little more optimistic.
I removed and re-added the library RNTwilioVideoWebRTC.xcodeproj again.  But then got an error stating that there were duplicate symbols.  This reminded me of #121 which saw a similar issue.
I started digging around in the linked frameworks and libraries and sure enough libRNTwilioVideoWebRTC.a had been added.  I removed it, added lib react-native-twilio-video-webrtc.a again and it has built and run out of both Xcode and the CLI.  

Again not positive (I will re-address this if I have future issues) but optimistic.  Hopefully this helps someone.

Thanks!

**Comment by slycoder** [comment]
Glad to hear you got this working.

Yeah, this seems to be one of those weird pod / xcode things that I haven't been able to get to the bottom of.  But happy to have this log here in case anyone else runs into the same problem and do let me know if you ever get any more insights.

**Comment by josefpohl** [comment]
Yes, there seems to many variants of the same/similar issue.  I truly appreciate all your work on this project!

**Comment by firofame** [comment]
This hack worked for me:
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
  pod 'react-native-twilio-video-webrtc', path: '../node_modules/react-native-twilio-video-webrtc'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
```
