### ISSUE TITLE
Problem resuming call in Android

### ISSUE THREAD

**Issue by anicoli-kubik** [blackuy/react-native-twilio-video-webrtc#200]
### Steps to reproduce
1. Start a video conference
2. Minimize the app
3. Foreground the app

### Expected behaviour
The call should resume normally

### Actual behaviour
The video gets frozen, both local and remote

### Environment
- **Node.js version**: v10.15.3
- **React Native version**: 0.56.0
- **React Native platform + platform version**: Android 8.1

### react-native-twilio-video-webrtc
**Version**: master

### Code
```javascript
export default class VideoCallComponent extends Component {
  twilioVideo = React.createRef();
  state = {
    status: 'disconnected',
    participants: new Map(),
    videoTracks: new Map(),
    participantType: '',
  };

  _onParticipantAddedVideoTrack = ({ participant, track }) => {
    const { participantType } = this.state;
    this.setState({
      videoTracks: new Map([
        ...this.state.videoTracks,
        [ track.trackSid, { participantSid: participant.sid, videoTrackSid: track.trackSid } ]
      ]),
    });
  }

  _onParticipantRemovedVideoTrack = ({ participant, track }) => {
    const { participantType } = this.state;
    const videoTracks = this.state.videoTracks;
    videoTracks.delete(track.trackSid);
    this.setState({ videoTracks: new Map([ ...videoTracks ]) });
  }

  render() {
    return (
      <TwilioVideo
         ref={this.twilioVideo}
         onParticipantAddedVideoTrack={this._onParticipantAddedVideoTrack}
         onParticipantRemovedVideoTrack={this._onParticipantRemovedVideoTrack}
      />
    );
  }
}
```

Thank you very much for your time and hope you can give me a hand. **IMPORTANT**: This is not happening in iOS, only Android.

**Comment by jedabero** [comment]
Also happens if you lock the device.
I recommend you check if componentWillUnmount fires when minimizing the app or if componentDidMount fires when the app comes back

**Comment by anicoli-kubik** [comment]
Figured out what the issue was (not an issue actually, rather expected behavior). I'll close the issue but in case it helps anyone I'll leave an explanation. In iOS it is either too smooth or not a problem at all to have the camera be used by many apps at once, in Android (check native code, file CustomTwilioVideoView.java, lines 230-281) it is necessary to release the camera in order for it to be usable by other apps. Commenting the code within those two methods (onHoseResume and onHostPause) results in the call going on even when the activity goes into background mode, it returns seamlessly to the foreground as well. However, as you may have guessed, that prevents your app from using the camera for other purposes at the same time as the call is going on or even from taking pictures with the camera app. It is not okay to prevent our users from accessing their camera just because we don't want to lose our calls but there you go, if you still wanna do it have it your way. Hope this helps someone with the same question :)

**Comment by slycoder** [comment]
Thank you so much for the detailed investigation and explanatino, @anicoli-kubik !

**Comment by Balasnest** [comment]
@slycoder Even though the lifecycle was written correctly (onHostResume and onHostPause) why this kinda issue coming?
Should I comment onHostPause code as @anicoli-kubik said it?
