### ISSUE TITLE
Record video

### ISSUE THREAD

**Issue by QuevedoIB** [blackuy/react-native-twilio-video-webrtc#202]
Hello, I'm new to React Native and I'm trying to add a conference feature to my app, the video/audio feature of the sample app in the repo looks good but I'd like to know if would it be possible to record it and be able to download at the end of the video call. Any help will be appreciated, thanks in advance!

**Comment by slycoder** [comment]
Twilio does support room recordings, but this is a property of the room:

https://www.twilio.com/docs/video/api/recordings-resource

Wherever you are creating rooms/access tokens should be were you set the recording params.
