### ISSUE TITLE
Change to docs for setLocalVideoEnabled

### ISSUE THREAD

**Issue by ThomasLarge** [blackuy/react-native-twilio-video-webrtc#203]
I can't see anything in the docs for `setLocalVideoEnabled` do you want me to do a PR and add in the details?

**Comment by slycoder** [comment]
Oh that must've been an oversight on my part.  A PR would be very welcome!

**Comment by ThomasLarge** [comment]
@slycoder No problem I will make a PR today!

**Comment by ThomasLarge** [comment]
@slycoder create PR https://github.com/blackuy/react-native-twilio-video-webrtc/pull/204
