### ISSUE TITLE
Clarify instructions for "add the xcode project to libraries"

### ISSUE THREAD

**Issue by quantumpotato** [blackuy/react-native-twilio-video-webrtc#206]
```
Add the XCode project to your own XCode project's "Libraries" directory from:

node_modules/react-native-twilio-video-webrtc/ios/RNTwilioVideoWebRTC.xcodeproj
```

What is this actually telling me to do?
Is this a separate step from adding the search paths?

I have Xcode open, I have the Libraries folder open in Xcode. How do I "add the Xcode project"?

**Comment by slycoder** [comment]
You can either ctrl click and choose "Add files" to add that file, or you can drag and drop that file into the libraries folder in Xcode.

**Comment by quantumpotato** [comment]
I skipped this step and it's compiling.. haven't tried to run the Twilio code yet.
When I try to add the Xcode project in this way
<img width="447" alt="Screen Shot 2019-06-19 at 10 14 16" src="https://user-images.githubusercontent.com/433852/59773116-1015af00-927b-11e9-9d1a-71919efff3d7.png">
