### ISSUE TITLE
iPhone XR Video is distorted

### ISSUE THREAD

**Issue by CaptainJeff** [blackuy/react-native-twilio-video-webrtc#209]
### Steps to reproduce
1. Start / accept video conference with another twilio user from iphone XR

### Expected behaviour
The video should be portrait mode and in the proper aspect ratio

### Actual behavior
When I first join the room my video is distorted (small video with my reflection) it is rotated 90 degrees and stretched as to fill the entire height. If I click on this box then it rotates properly but the other feed does this (the person I am conferencing with). One or the other has a rotated and stretched video feed. This is only happening for iphone XR

### Environment
- **Node.js version**:v10.15.3
- **React Native version:**: 59.9
- **React Native platform + platform version**: iOS 12.3.2

### react-native-twilio-video-webrtc
**Version**:1.0.2

**Comment by slycoder** [comment]
Hm, sounds reminiscent of https://github.com/twilio/video-quickstart-ios/issues/326

Are you running master?

**Comment by slycoder** [comment]
Sorry, hit the close button by mistake.
