### ISSUE TITLE
Not able to connect other user 

### ISSUE THREAD

**Issue by tusharnetset** [blackuy/react-native-twilio-video-webrtc#210]
### Steps to reproduce
1.I am not able to connect another user and also can you please provide proper documentation for this.
2which method would be called on incoming call from another user?
3.

### Actual behaviour
first user is unable to call another user. 'onParticipantAddedVideoTrack' method only call when i click on 'CONNECT" button from both sides.

### Environment
- **Node.js version**:10.12.0

- **React Native version**:0.59.9
- **React Native platform + platform version**:Android

### react-native-twilio-video-webrtc
**Version**: git+https://github.com/blackuy/react-native-twilio-video-webrtc.git

**Comment by slycoder** [comment]
Hi, in order to initiate the session you have to invoke the connect method.  If you want to receive calls, you'd have to do that separately, for example by using `react-native-callkit`.
