### ISSUE TITLE
Build failed 'TwilioVideo/TwilioVideo.h' file not found when using fastlane

### ISSUE THREAD

**Issue by Abhishek9634** [blackuy/react-native-twilio-video-webrtc#211]
'TwilioVideo/TwilioVideo.h' file not found

#import <TwilioVideo/TwilioVideo.h>

this error  when we try to build,.
the work around is do pod install manually then rebuild then it works

Can anyone assist???

**Comment by CaptainJeff** [comment]
Is your podfile.lock updated? Seems like the versioning might be different than what is committed

**Comment by anje89** [comment]
@Abhishek9634 I encountered the same issue. I noticed that after running `(cd ios && pod install)` the TwilioVideo pod generated code under a **Build** folder and build folders are not checked into our repo.

I just updated our project's **.gitignore** file with `!ios/Pods/TwilioVideo/Build/` to allow the TwilioVideo pod install changes to be checked into the repo (i.e. now Jenkins/fastlane doesn't need to run pod install).

**Comment by TaraSinghDanu** [comment]
> @Abhishek9634 I encountered the same issue. I noticed that after running `(cd ios && pod install)` the TwilioVideo pod generated code under a **Build** folder and build folders are not checked into our repo.
> 
> I just updated our project's **.gitignore** file with `!ios/Pods/TwilioVideo/Build/` to allow the TwilioVideo pod install changes to be checked into the repo (i.e. now Jenkins/fastlane doesn't need to run pod install).

@anje89 Adding !ios/Pods/TwilioVideo/Build/ to .gitignore works!!!
