### ISSUE TITLE
No events on remote user disconnected ( Internet connection / app closing suddenly)

### ISSUE THREAD

**Issue by codemeall** [blackuy/react-native-twilio-video-webrtc#214]

**Comment by codemeall** [comment]
onParticipantRemovedVideoTrack is triggering after 120 seconds, any way to reduce the time to second.

**Comment by slycoder** [comment]
It sounds like iOS 3.0 beta addresses this: https://github.com/twilio/video-quickstart-ios/issues/99 but I think we should wait until it's fully baked before incorporating here.
