### ISSUE TITLE
Can this repo be installed via NPM? 

### ISSUE THREAD

**Issue by bimix** [blackuy/react-native-twilio-video-webrtc#215]
### Steps to reproduce
1. npm install blackuy/react-native-twilio-video-webrtc
I tried but it throws 'spawn git ENOENT' error as if it doesnt contains package.json

**Comment by slycoder** [comment]
It sounds like you don't have git installed:

https://stackoverflow.com/questions/42545885/vs-code-error-spawn-git-enoent
