### ISSUE TITLE
Question about CPU

### ISSUE THREAD

**Issue by bsiddiqui** [blackuy/react-native-twilio-video-webrtc#22]
I've been using my own implementation of video streaming with [react-native-webrtc](https://github.com/jitsi/react-native-webrtc) and the it has really high CPU (70-80%) on iOS. 

I've been thinking about switching to twilio and using this module but wanted to see how your CPU usage/battery life has been with this module. Any info would be super helpful!

**Comment by bilby91** [comment]
@bsiddiqui I didn't benchmark CPU usage. Maybe @gastonmorixe did something. If that is not the case I can do some investigation here.

**Comment by bsiddiqui** [comment]
@bilby91 looks like CPU usage is very high. Minimum of 60-80% and many times over 100%. Would be great to know if this is a react native thing or if the core twilio module is similar.

<img width="1284" alt="screenshot 2017-07-28 18 29 23" src="https://user-images.githubusercontent.com/2721959/28741033-b71f9ea2-73c2-11e7-89bf-d4971386a146.png">

**Comment by slycoder** [comment]
This appears to be an issue with the underlying twilio implementation.  There's a thread about that here:

https://github.com/twilio/video-quickstart-swift/issues/88

**Comment by bsiddiqui** [comment]
Sounds good, will subscribe to that issue

**Comment by jagdeepChicmic** [comment]
Some time my app hang due to high usage of CPU
