### ISSUE TITLE
Android: TwilioVideoPreviewManager cannot be cast to ViewGroupManager

### ISSUE THREAD

**Issue by mfkrause** [blackuy/react-native-twilio-video-webrtc#224]
I've implemented this library in our project successfully now, it works like a charm on iOS. However when I try to open the screen containing this library on an Android device, I get this error:
com.twiliorn.library.TwilioVideoPreviewManager cannot be cast to com.facebook.react.uimanager.ViewGroupManager

This is our code (removed some stuff like API Calls):
```
import React from 'react';
import { StyleSheet, View, Image, ImageBackground, Text, Dimensions, Alert, TouchableOpacity, TouchableWithoutFeedback } from 'react-native';
import { Button } from 'react-native-elements';
import Icon from 'react-native-vector-icons/FontAwesome';
import { Permissions, Constants } from 'expo';
import * as SecureStore from 'expo-secure-store';
import {
  TwilioVideoLocalView,
  TwilioVideoParticipantView,
  TwilioVideo
} from 'react-native-twilio-video-webrtc'
import { API_URL } from 'react-native-dotenv';

export default class VideoCallScreen extends React.Component {

  static navigationOptions = ({ navigation }) => {
    const { state: { params = {} } } = navigation;
    return {
      title: params.title || 'Aktiver Videoanruf'
    };
  }

  constructor(props) {
    super(props);
    this.state = {
      buttonsDisabled: true,
      isAudioEnabled: true,
      isVideoEnabled: true,
      status: 'disconnected',
      participants: new Map(),
      videoTracks: new Map(),
      roomName: 'general'
    }

    this._connect = this._connect.bind(this);
    this._onParticipantAddedVideoTrack = this._onParticipantAddedVideoTrack.bind(this);
  }

  async componentDidMount(){
    [... getting twilio token]
  }

  componentWillUnmount(){
    if(this.state.status == 'connected' || this.state.status == 'connecting') this.refs.twilioVideo.disconnect();
  }

  async _connect(){
    const { status } = await Permissions.askAsync(Permissions.CAMERA);
    if (status !== 'granted') {
      Alert.alert("Leider haben Sie uns keine Berechtigung gegeben, um auf Ihre Kamera zuzugreifen. Bitte gestatten Sie den Zugriff in Ihren Telefoneinstellungen.");
    }else{
      const { status } = await Permissions.askAsync(Permissions.AUDIO_RECORDING);
      if (status !== 'granted') {
        Alert.alert("Leider haben Sie uns keine Berechtigung gegeben, um auf Ihr Mikrofon zuzugreifen. Bitte gestatten Sie den Zugriff in Ihren Telefoneinstellungen.");
      }else{
        [... connecting]
      }
    }
  }

  [... events]

  render() {
    return (
      <View style={{flex: 1}}>
        {
          this.state.status === 'connected' &&
          <TwilioVideoLocalView style={styles.fullArea} enabled={true}>
          <TwilioVideoParticipantView
            style={styles.upperRightArea}
            key={this.state.videoTrackSid}
            trackIdentifier={this.state.videoTrackObject}
          />
          </TwilioVideoLocalView>
        }
        {
          this.state.status !== 'connected' &&
          <View style={{flex: 0.9}} />
        }
        <View style={styles.bottomArea}>
            <View style={styles.row}>
                <TouchableOpacity style={styles.box} onPress={() => this._onPressHangup()}>
                    <Icon name='phone' size={30} color="#ff0000" style={{transform: [{ rotate: '135deg'}]}}/>
                </TouchableOpacity>
            </View>
            <View style={styles.row}>
                <TouchableOpacity style={styles.box} onPress={() => this._onPressFlip()}>
                    <Icon name='refresh' size={30} color="#222"/>
                </TouchableOpacity>
            </View>
        </View>

        <TwilioVideo
          ref="twilioVideo"
          onRoomDidConnect={ this._onRoomDidConnect }
          onRoomDidDisconnect={ this._onRoomDidDisconnect }
          onRoomDidFailToConnect= { this._onRoomDidFailToConnect }
          onParticipantAddedVideoTrack={ this._onParticipantAddedVideoTrack }
          onParticipantRemovedVideoTrack= { this._onParticipantRemovedVideoTrack }
        />
      </View>
    );
  }
}

var screenWidth = Dimensions.get('window').width;
const styles = StyleSheet.create({
    fullArea: {
      flex: 1,
      backgroundColor: '#555'
    },
    upperRightArea: {
        flex: 0.2,
        backgroundColor: 'rgba(85, 85, 85, 0.9)',
        width: '50%',
        alignSelf: 'flex-end',
        marginRight: 10,
        marginTop: 10
    },
    bottomArea: {
        flex: 0.1,
        flexDirection: 'row',
        backgroundColor: 'rgba(255, 255, 255, 0.6)'
    },
    text: {
        textAlign: 'center',
        color: 'white',
        fontSize: 17,
        fontFamily: 'poppins'
    },
    button: {
        borderRadius: 25,
        backgroundColor: '#f0f0f0',
        paddingHorizontal: 25,
        marginTop: 10
    },
    boxButton: {
        borderRadius: 10,
        backgroundColor: '#41ace3',
        width: screenWidth / 2 - 25,
        marginTop: 30,
    },
    row: {
        flex: 1,
        backgroundColor: 'transparent'
    },
    box: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative'
    },
    settingsLink: {
        position: "relative",
        right: 10,
        borderRadius: 25,
        backgroundColor: '#f0f0f0',
        paddingHorizontal: 10,
        marginTop: 10
    },
    logo: {
        width: screenWidth * 0.8,
        height: screenWidth * 0.8 * 0.269
    }
});
```

It gets the chat token successfully and joins the room + sends the video stream (I can see the person connecting from the Android phone on the other end), so the problem is only that the two Participant Views can't get rendered on the Android phone.

### Environment
- **Node.js version**: v10.15.1
- **React Native version**: 0.59.8
- **React Native platform + platform version**: Android 9.0

### react-native-twilio-video-webrtc
**Version**: master

**Comment by slycoder** [comment]
Interesting.  Can you try not making the participant view a child of the local view (e.g. make them siblings) and see if that fixes it?

**Comment by mfkrause** [comment]
Yep, that was it indeed. One other problem occurred then: I'm trying to make the local view the primary view (the "big" view), the participant view should be on top of it on the very top right. I tried to do this via zIndex, that didn't seem to work though (that's why I made that weird setup with the child view).
I now "fixed" this by changing line 21 in TwilioVideoPreview.java on the Android version from
`this.getSurfaceViewRenderer().applyZOrder(true);`
to
`this.getSurfaceViewRenderer().applyZOrder(false);`

Now the participant view successfully renders above the local view. I haven't tried it on iOS though, will have to do so today and see if I need to change something in the iOS source, too.
I don't know too much about native programming in conjunction with React Native unfortunately, otherwise I'd try and find a proper fix in order to get zIndex working like it should.

**Comment by slycoder** [comment]
Yep, great spotting that error.  This was noticed in #219 and it sounds like a fix might be in the works there.

**Comment by mfkrause** [comment]
I don't know if this is exactly related to my changes in the native source, but since the chances are pretty high I'll just comment that here.
I'm now experiencing another, really weird, error/crash. On debug mode (which needs "expo start" to pull the JS files), the app works fine on both iOS and Android. However, when I try the release-channel app (signed IPA/APK), it only works on iOS. When I run the signed release APK, the app crashes as soon as I open the screen that imports this library. Since it simply crashes on release mode, I don't get to see any error logs (device isn't rooted - don't know if I can get the crash logs somewhere?). I've narrowed it down by removing elements and code snippets - the crash occurs when any Component of this library is loaded, like <TwilioVideo> or <TwilioVideoLocalView>. When I remove all components from the render() function (but leave the other code from this library in), it doesn't crash (but obviously doesn't work).
I can't seem to wrap my head around why it only crashes on the release-version APK.

**Comment by VladCodeCare** [comment]
I want to place 3 remote previews on one big background remote preview. But the large preview is redrawn and hides the small views, being layer higher. zIndex, elevation and applyZOrder (false) do not help solve the problem with overlapping layers. Is there a way to set the layer level?

**Comment by slycoder** [comment]
This is tricky, you'll want to set applyZOrder to the smaller windows, but *not* on the big background preview.
It might be worth creating a new prop and using that to determine whether to call applyZOrder on a particular preview view.

**Comment by slycoder** [comment]
Ok, I'll prioritize working on a fix and hopefully I'll have time in the next week or so.  If anyone else feels like hopping in, let me know and I can guide you through it.

**Comment by slycoder** [comment]
@mfkrause  @VibhutiPatel93 @VladCodeCare  - I've added a draft PR which adds a new prop which should allow things to work the way you want them to.  Can you pull down the branch and let me know if it works for you?

**Comment by cdomingopuig** [comment]
@slycoder I had the same issue as @mfkrause, making the local video as the primary one, and your draft works perfectly! 🎉

**Comment by ibtisamasif** [comment]
I tried applyZOrder(false); on android and it worked. What to do on iOS. Which file and line do i need to change exactly.
PS: I have experience in android as well but not in ios.
