### ISSUE TITLE
Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs

### ISSUE THREAD

**Issue by ThomasLarge** [blackuy/react-native-twilio-video-webrtc#229]
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.
After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.

Is there any update on this package to see if you guys are going to update this to use wkwebview https://developer.apple.com/documentation/webkit/wkwebview

This was seen today when uploading a app to test-flight, I'm also more than happy to test this out when any changes have been made 👍

**Comment by slycoder** [comment]
I wasn't aware that we were using this API.  Do you happen to know where it is (perhaps it's in a dependency, e.g. an old version of react native?)

**Comment by shahanaahmad** [comment]
Is there any update on this?

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information. After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to App Store Connect.
> 
> Is there any update on this package to see if you guys are going to update this to use wkwebview https://developer.apple.com/documentation/webkit/wkwebview
> 
> This was seen today when uploading a app to test-flight, I'm also more than happy to test this out when any changes have been made 👍

Is there any update on this issue?. I am also facing the same issue.
