### ISSUE TITLE
Android: Video Track added through Safari (VP8 WebRTC) doesn't get added/shown

### ISSUE THREAD

**Issue by mfkrause** [blackuy/react-native-twilio-video-webrtc#231]
Old problem, see edit2 for updated problem: (Sorry for the confusing title, couldn't find a better wording. My problem is that, on Android, somehow only two video/audio tracks get added (the local one and the one of the first remote participant that joined). When a second remote participant joins the room, the tracks never get added. I'm checking this through the onParticipantAddedVideoTrack callback - it does get called on the first remote participant that joins, however not when the second remote participant joins.

If that somehow matters (couldn't test otherwise yet): Our app always creates the room, so the local participant is always the first one in the room. Once a remote participant joins, the room starts. Afterwards, a second remote participant might join the in-process room.

On iOS, everything works as expected. All two remote participants (three with the local participant) get registered and displayed.

Any idea what could be causing that? I did some changes to the native Android code (see issue #224), however that probably shouldn't be relevant here since the problem is that the participant doesn't get registered at all, not just not displayed.

/**edit**: Okay, gotta correct myself on one thing: The audio track of the second remote participant **does** get added. I can hear the participant, but the video track doesn't get added (so, onParticipantAddedVideoTrack doesn't get called as well, onParticipantAddedAudioTrack does though). Even weirder.)

/**edit2**: I think I found the problem. The problem is not in relation to being the third participant. The video track doesn't get added when the participant joined through Safari. So, there seems to be some kind of problem with the WebRTC codec (Safari 12.1.2, my version, seems to use VP8 or something?). Don't know if this has to do with this library or Android itself though.

### Environment
- **Node.js version**: v10.15.1
- **React Native version**: 0.59.8
- **React Native platform + platform version**: iOS 12.1

### react-native-twilio-video-webrtc
**Version**: master

**Comment by slycoder** [comment]
See https://www.twilio.com/docs/video/managing-codecs

**Comment by mfkrause** [comment]
> See https://www.twilio.com/docs/video/managing-codecs

Thanks. The section "Codec interoperability in P2P Rooms" explains this issue quite well. Seems to be a codec issue indeed then, not related to this library. We'll have to think of some error handling for this then probably in order to real-time notify users of unsupported codecs when they are trying to join a room.
Will close this issue. Thanks!
