### ISSUE TITLE
UI freezes while calling .connect() on iOS release build

### ISSUE THREAD

**Issue by ooca-big** [blackuy/react-native-twilio-video-webrtc#233]
By using example code from README running on debug build everything work perfectly. But, not for release build. 
On release build, UI components becoming not responsible when calling `this.refs.twilioVideo.connect(...)`. This might take more than 30sec before UI components become responsible and TwilioVideo become functional again.

 I tried to remove this line and UIs work just fine.

### Testing environments:
**devices**: iPhone 6s, iPhone 7, iPhone 7 Plus, iPhone 8, iPhone 8 Plus , iPad Mini 4th gen, iPad Air 2019
**OS**: iOS10, iOS12, iOS13

#### react-native info
```bash
System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 66.43 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    Yarn: 1.12.1 - ~/.yarn/bin/yarn
    npm: 6.11.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 24, 25, 26, 27, 28
      Build Tools: 23.0.1, 23.0.3, 25.0.0, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.2, 28.0.3
      System Images: android-27 | Google Play Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: 19.2.5345600
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.5 => 0.60.5 
  npmGlobalPackages:
    create-react-native-app: 2.0.2
```

**Comment by slycoder** [comment]
Do you have anything in the logs you might be able to share?

**Comment by ooca-big** [comment]
> Do you have anything in the logs you might be able to share?

thank you for reply,
I'm trying to get some logs which might be help. But, there's nothing related. Actually, there's no log printed from the app while the UI still freeze. 

Any suggestion to get trace?

**Comment by ooca-big** [comment]
what i've tried. 

- put `.connect(...)` into `setTimeout(...)`
- put `.connect(...)` into async function
- replace main dispatch queue in Obj-C  with custom queue created with `DISPATCH_QUEUE_SERIAL` 
- turn off `Optimization` in `Build Settings`
- turn off `Dead Code Stripping` in `Build Settings`

**Comment by slycoder** [comment]
What's the last thing you see in the log?

**Comment by ooca-big** [comment]
> What's the last thing you see in the log?

just a Firebase Analytics initialization
