### ISSUE TITLE
When changing the camera, the local view flips using the same camera

### ISSUE THREAD

**Issue by ThomasLarge** [blackuy/react-native-twilio-video-webrtc#234]
### Expected behaviour
When pressing the button to change the camera this should change to front or back camera. 

### Actual behaviour
When pressing the button the localview flips the camera so it's inverted. 

### Environment
- **React Native version**: 0.59.8
- **React Native platform + platform version**: iOS 9.0 + Android 7 +

### react-native-twilio-video-webrtc
**Version**: "master"

### Code
```js
_onFlipButtonPress = () => {
    this.twilioVideo.flipCamera();
  };
```

**Comment by slycoder** [comment]
Strange, we're just calling the underlying switchCamera function.

Two questions:
1.) Is there anything in the adb logs that might be related?
2.) Are you receiving an onCameraSwitched event (and if so is `isBackCamera` getting toggled)?

**Comment by ThomasLarge** [comment]
@slycoder I haven't seen anything in there? I will have to test the second point and get back to you
