### ISSUE TITLE
Cant run yarn add https://github.com/blackuy/react-native-twilio-video-webrtc

### ISSUE THREAD

**Issue by fergMauricio** [blackuy/react-native-twilio-video-webrtc#236]
None of this is working for me: 

yarn add https://github.com/blackuy/react-native-twilio-video-webrtc
npm install https://github.com/blackuy/react-native-twilio-video-webrtc --save

This is what i get (Android):
-------------
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t https://github.com/blackuy/react-native-twilio-video-webrtc.git
npm ERR! 
npm ERR! dyld: Library not loaded: @rpath/libswiftCore.dylib
npm ERR!   Referenced from: /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
npm ERR!   Reason: image not found
npm ERR! git: error: unable to locate xcodebuild, please make sure the path to the Xcode folder is set correctly!
npm ERR! git: error: You can set the path to the Xcode folder using /usr/bin/xcode-select -switch
npm ERR! 
npm ERR! exited with error code: 71

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mac/.npm/_logs/2019-09-23T20_31_52_560Z-debug.log
------------------

the android folder is not been created:

node_modules/react-native-twilio-video-webrtc/android

Please help me, thanks!

**Comment by slycoder** [comment]
Strange.  What version of xcode do you have installed?

**Comment by slycoder** [comment]
When you run the underlying command on its own, does it work?

/usr/bin/git ls-remote -h -t https://github.com/blackuy/react-native-twilio-video-webrtc.git

If not then you might not have the basic xcode tools installed on your machine.
