### ISSUE TITLE
TwilioVideoParticipantView crashing app on iOS 13 (& 13.1)

### ISSUE THREAD

**Issue by slvtrs** [blackuy/react-native-twilio-video-webrtc#238]
### Steps to reproduce
1. Using device on iOS 13+
2. Connect video
3. Render `<TwilioVideoParticipantView />`

### Expected behaviour
Remote video should display as normal.
This same build is still working fine on iOS 12.2

### Actual behaviour
App crashes, throwing this exception in Xcode:
```
Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
```
Pointing to this line in `ios/app/Supporting/main.m`:
```
return UIApplicationMain(argc, argv, nil, NSStringFromClass([AppDelegate class]));
```

### Environment
- **Node.js version**: v10.16.0
- **React Native version**: 0.58.9
- **React Native platform + platform version**: iOS 13+

### react-native-twilio-video-webrtc
**Version**: "master"

**Comment by slycoder** [comment]
Looks like we'll need to upgrade our underlying library:

https://github.com/twilio/twilio-video-ios/blob/Releases/iOS-13-Migration-Guide.md

**Comment by slvtrs** [comment]
Thanks for the quick reply.
Supporting iOS 13 is a big priority for us currently.
Is there a drop-in reference to the twilio SDK version somewhere that I can try updating?

**Comment by slvtrs** [comment]
Update: I changed the TwilioVideo dependency from `~> 2.7.0` to `~> 2.10.1` in `./react-native-twilio-video-webrtc.podspec` and rebuilt my pods, but unfortunately I'm still hitting the exact same issue even though 2.10.1 is confirmed as working with iOS 13 in the official Twilio Video migration link above.
Any other thoughts on what to try?

**Comment by slycoder** [comment]
What version of xcode are you using and what's your target version set to?

**Comment by slvtrs** [comment]
Xcode 11.1 targeting iOS version 13.1

I just came across this from twilio:
```
The SDK will crash when rendering decoded H.264 video, or any other frames in the TVIPixelFormatYUV420BiPlanarVideoRange or TVIPixelFormatYUV420BiPlanarFullRange formats when using Xcode 11.0 and an iOS 13.0 simulator.

Resolution: Update Twilio Video to 3.0.0-beta4, or 2.10.2 (coming soon). Use an older simulator model for testing if your deployment target is earlier than 13.0.
```

I then tried using `'TwilioVideo', '~> 3.0.0'` but now my `pod install` fails with:
```
None of your spec sources contain a spec satisfying the dependency: `TwilioVideo (~> 3.0.0)`.
```

**Comment by slycoder** [comment]
You might have to be explicit about pulling in beta versions.

**Comment by slvtrs** [comment]
You are correct, pulling in `3.0.0-beta4` did in fact complete `pod install`, but it seems that upgrading from 2.x to 3.x will require some internal refactoring.

I received these errors when building in Xcode:

<img width="270" alt="Screen Shot 2019-09-25 at 1 43 54 PM" src="https://user-images.githubusercontent.com/14077311/65625969-c84da480-df9a-11e9-886f-28d6d2d88c01.png">

**Comment by slvtrs** [comment]
The twilio migration doc makes it sound like it may be only the iOS **Simulator** that 2.10.1 crashes on, so I'm currently working on testing on an actual device running iOS13 (I don't have direct access to one myself so this will take me a few hours to confirm/deny).

**Comment by slvtrs** [comment]
Success!
Thanks for working with me today @slycoder 
We were finally able to confirm that although 2.10.1 does not work on a simulator running ios 13, it does in fact work on an actual device running ios 13.

The upgrade details from twilio sound like some features may be missing still, but for our needs this is sufficient so we'll be using a forked version for the time being.

**Comment by slycoder** [comment]
Great to hear that it worked out.  If you wanna throw up a PR for that fork, I can take a look and get it into master.

**Comment by FrenchMajesty** [comment]
Hey @slvtrs , would you mind sharing that fork?

**Comment by slvtrs** [comment]
@FrenchMajesty that fork was actually [merged into master](https://github.com/blackuy/react-native-twilio-video-webrtc/pull/240)
