### ISSUE TITLE
Invariant Violation: Native module cannot be null.

### ISSUE THREAD

**Issue by ch4rlesyeo** [blackuy/react-native-twilio-video-webrtc#239]
Hi,

I'm trying to use React native Twilio video webrtc in an ejected Expo React Native project but encountered this error "Invariant Violation: Native module cannot be null." when loading TwilioVideo from the library.
![image](https://user-images.githubusercontent.com/8202917/65813230-f9311200-e204-11e9-9ae6-0bc739c0202d.png)

I'm using expo cli to initiate the project and ejected it after that.

### Steps to reproduce
https://github.com/ch4rlesyeo/twilio-video-webrtc-nativemodule-cannotbenull

### Expected behaviour
TwilioVideo imported screen view should load normally.

### Actual behaviour
Error: "Invariant Violation: Native module cannot be null." was thrown.

### Environment
- **Node.js version**: 10.16.0
- **React Native version**: https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz
- **React Native platform + platform version**: iOS 10.0

### react-native-twilio-video-webrtc
**Version**: master

**Comment by slycoder** [comment]
Hi, thanks for the detailed repro! 

I pulled down the repo and built it and was not able to reproduce the issue.  Here are the steps I followed:

1.) cloned repo.
2.) yarn install
3.) pod install
4.) Run `expo start --ios`
5.) Opened up the xcworkspace in xcode.
6.) Hit run to build it and run it on my simulator.

I saw the message and no warnings about being unable to load the library.

**Comment by ch4rlesyeo** [comment]
ahh my bad, i was running the project in my device's expo app, it works fine after using xcode. appreciate for the look out @slycoder

**Comment by marcos-mercuri-tw** [comment]
Hi, I had the same problem and effectively it works if run using xcode. I'm new to React Native and expo and I was wondering, @slycoder, if you could explain me (or give me some pointers) as to why it doesn't work on Expo but it does in xcode (I understand it has something to do with the fact that the library uses native features), and if that means that this library cannot be used with Expo. 
I'm not sure if here is the right place for this question, but I appreciate any help!

**Comment by slycoder** [comment]
I'm not sure I can be of much help here, I've never used expo so I don't have a lot of insight on how it works and how to integrate packages with native code into it =(.  

If anyone else does, tips would be welcome!

**Comment by marcos-mercuri-tw** [comment]
Thanks for the quick reply!
Let's see of someone else can help, then :)

**Comment by marcos-mercuri-tw** [comment]
Leaving this here in case someone else needs it:
I've done some further research and seems that Expo is not supporting WebRTC (which is used by Twilio). There's a request for adding this: https://expo.canny.io/feature-requests/p/webrtc.
You can use the new [Bare Workflow](https://docs.expo.io/versions/v37.0.0/bare/exploring-bare-workflow/) to use this library, or just plain vanilla React Native.
