### ISSUE TITLE
Disable video tracks and use audio only

### ISSUE THREAD

**Issue by Skywriter-MD** [blackuy/react-native-twilio-video-webrtc#253]
Hi there,
I am trying to assure that video tracks from the device do not get published and use audio only.  Similar to js SDK which has something along these lines:
  let connectOptions = {
      name: this.state.roomName,
      audio: true,
      video: false //{ width: 640 }
    };

I am publishing from a device (in this case iOS solely) to a react web component, not from device to device.  I can disable the video using setLocalVideoEnabled but it still seems to publish the tracks existence.  (I call setLocalVideoEnabled prior to connect, which may not be the correct spot.) 

I have tried different variants of isVideoEnabled in connect but none seem to make a difference (Sorry I do not have the code for this.) And have set enabled to false on the TwilioVideoLocalView, but I suspect this is not addressing the issue I am concerned with.

My primary concern here is that even when I am turning off the video via setLocalVideoEnabled and disabling any video component on the web side, iOS is requiring that I set the NSCameraUsageDescription and prompts for allowing it. For privacy and compliance reasons I cannot have the system prompt for this. Oddly, it only seems to be an issue on the actual device and not on the simulator.  

If anyone has any thoughts on how to disable this proactively would be appreciated.
Thanks -- Joe  

### Environment
- **React Native version**: 0.59.8
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: 1.0.2

**Comment by josefpohl** [comment]
Hi there, I just thought I would check to see if anyone had an idea about if this was possible or another issue reference that I might have missed.

Thanks -- Joe

**Comment by slycoder** [comment]
Sorry about taking so long to reply.  It looks line in componentWillMount in TwilioVideo.ios.js we are always initializing local video.  

Can you peeps try commenting that line out and seeing if it resolves your issue?  If so we can come up with a a systematic approach to gate that line.

**Comment by josefpohl** [comment]
Hi there, no worries about the delay. I will do this check ASAP and let you know the results. Sounds like a relatively easy fix if it works for me. Thanks and I will be in touch. Joe

**Comment by AzrulSudarmin** [comment]
Hi there, is there any updates about this issue?

**Comment by josefpohl** [comment]
My apologies about the updating this so slowly.  By commenting out the 'this._startLocalVideo()' line in TwilioVideo.ios.js I was able to keep the request for permission from being shown.  But now that I say this, I realize I still have the info.plist Camera Usage statement still in the file.  I will try it again with out that.

**Comment by josefpohl** [comment]
Hi there, 
I updated the library yesterday and came across the fact that I had wiped out my own change.  How can I assist in getting this into the master branch? (i.e. I am willing to create a PR but might need a bit of guidance.) Thanks again, Joe

**Comment by slycoder** [comment]
@josefpohl If you put up a PR I'd be happy to help you shepherd this in!

**Comment by Balasnest** [comment]
@josefpohl Hi is your changes merged into master? I'm also looking into this.

What I did is:
1. connect with a room
2. disable Local video immediately after connect

Other parties in web js, they are getting participant to connect and video track subscribed. but there is no event trigged for the disabled.


But in

**Comment by Balasnest** [comment]
@slycoder Please review [#347](https://github.com/blackuy/react-native-twilio-video-webrtc/pull/347)

**Comment by josefpohl** [comment]
Hi @Balasnest 
Thanks so much.  Sadly I have been a bit occupied with other aspects to get back to those changes.  Mine were always temporary. 

I did try setLocalVideoEnabled to false in "onRoomDidConnect()" but it did not seem to have the affect I wanted.  (Still had the video track published.) 

Still not sure why my previous fix is not working now (The one mentioned here in 253 is not working now, per #342.) 

@slycoder , what would it take to check out this solution?
Thanks,
Joe

**Comment by slycoder** [comment]
Let's get both of those PRs merged and see where we're at 🤞 .

Totally understand what it's like when day care is closed 👶

**Comment by josefpohl** [comment]
@Balasnest , I did not get back this yesterday, my apologies.  Can I confirm that the syntax is connect({accessToken: ... , enableVideo: <bool>, enableAudio: <bool>, ...}) ?
Thanks,
Joe

**Comment by Balasnest** [comment]
@josefpohl Try with this structure:

```this.refs.twilioVideo.connect({
      roomName: this.state.roomName,
      accessToken: this.state.token,
      enableVideo: false | true,
      encodingParameters: {
        enableH264Codec: true,
        audioBitrate: 16,
        videoBitrate: 1200
      }
    });
```
Note: `encodingParameters` is for iOS only.

**Comment by josefpohl** [comment]
@Balasnest 
Thank you so much for this.  It seems to be working as expected. (I finally got it to build properly... mostly my mistakes).  One caveat that I will note, but I am not sure if is a valid concern.  The first time I tried it I was still getting the video screen and the prompt for the Camera usage.  I went in and set the default on enableVideo to false (line 228 connect in TwilioVideo.ios.js) and then re-ran it on a clean install onto a device (iOS 13.5.1) and then it seemed to work fine.  I went back and reset the default to true, re-built and everything seemed to be good on a clean install again.  It was probably a "state" issue on my end, but just wanted to note it. 

Thanks!  Sorry it took me so long to take a look at this.  And @slycoder, thanks for your support on this as well.  I have to say @Balasnest 's solution was much more elegant than mine would have ever been.  My eyes roll whenever I look at Obj C but I am trying to get comfortable.
Thanks again,
Joe

**Comment by Balasnest** [comment]
@josefpohl Thanks mate for your reply. Yeah. Its bit hard to be focused with `javascript -> typescript -> objective-c -> node_modules` :)

**Comment by zuhairnaqi** [comment]
This issue is still occuring on android.
I block camera permission and try to connect audio call.
It's giving me error of local video.
Also @Balasnest did update IOS only in his PR, Kindly fix this issue on android as well

Thanks

**Comment by remigijusbalc** [comment]
Hey, I added pr which fixes android https://github.com/blackuy/react-native-twilio-video-webrtc/pull/496

**Comment by josefpohl** [comment]
Hi there,
Did this get reverted at some point?   I finally got back to this project and pulled the latest version:
(fc13008410b034102dd5d57371928026f5f7a8ee) and noted that, while I had the enableVideo: false flag set in the connection options I was still getting a "video" track published from the local device.  

I have only checked this on iOS and I will note that the issue does not occur on the simulator but I do get the following error: 
`ERROR:Twilio:[Platform](0x11193cdc0): Failed to create a camera source, no capture sources are available on a simulator.`

I can also saw an issue that using
`setLocalVideoEnabled(false);`
does disable the audio. (Similar to #356) 

Thanks!

**Comment by josefpohl** [comment]
I was able to turn the default video (automatic enable) by commenting out the line at 165:
`this._startLocalVideo()` 
as was initially suggested.  Any thought on why this feature became disabled? Or did I mess something up? 
(FWIW, I do still have the NSCameraUsageDescription key in the Info.plist file.  I have not tried taking it out as it was in my previous version as well.)
Thanks,
Josef

**Comment by remigijusbalc** [comment]
startLocalVideo in ios setups camera and it's track which results to adding local participant video track to twilio room after succesful connection. This could be changed by passing additional params in connect and based on them enabling tracks, but that may result in breaking changes

**Comment by slycoder** [comment]
I think I accidentally broke the previous behavior in #403.  The reason for that is because of other complaints around certain behaviors.  

I think I may just add a prop to the component which prevents initialization.

**Comment by josefpohl** [comment]
Thanks @slycoder and @remigijusbalc , Obviously I missed that change.  As always I appreciate the work.  Commenting out startLocalVideo works for me for the moment, but more solid method would be great!
Thanks!

**Comment by slycoder** [comment]
@josefpohl  Check out #505 and see if that works for you.

**Comment by josefpohl** [comment]
@slycoder I will check that out.  Looks like it broke something and had not been merged yet. But I have those changes staged in TwilioVideo.ios.js. 

On another note, did setLocalAudioEnabled get removed as well.  I know there has been some discussion about it but it too has seemingly stopped working for me.  

```
  const muteCall = () => {
    console.log(`Muted changes from ${muted} to ${!muted}`);
    twilioRef.current.setLocalAudioEnabled(muted).then((isEnabled) => {
      console.log(`Audio is now enabled: ${isEnabled}`);
      setMuted(!muted);
    });
  };
```

**Comment by slycoder** [comment]
What did #505 break for you? 

Do you have more information on the issue with setLocalAudioEnabled?

**Comment by josefpohl** [comment]
Hi @slycoder,
Actually I have not put any of that code in as of yet. This was an issue straight from the last build. With the exception that I did comment out the startLocalVideo() from the TwilioVideo.ios.js file.

**Comment by josefpohl** [comment]
Sorry, @slycoder, 
I was a bit pre-occupied when I responded last night.  So this was an issue that seemingly occurred right out of the box for me. My test was on a clean pull from the repo referenced above (fc13008) except that I did remove the line in the componentDidMount(), this._startLocalVideo().
```
 componentDidMount () {
    this._registerEvents()
    //this._startLocalVideo()
    this._startLocalAudio()
  }
```

I did make the modifications as prescribed in #505 and the mute functionality did seem to work.  I am not sure what the difference is necessarily and maybe I was just imagining things. Both stop the invocation of the startLocalVideo method. So, ignore what I said I guess.  

Any idea when 505 will get merged?  
Thanks, as always!

**Comment by slycoder** [comment]
Went ahead and merged #505 .

**Comment by josefpohl** [comment]
Thanks @slycoder!

**Comment by esteban199** [comment]
i need to disable local camera so i did this:

 _onDisableVideoButtonPress = () => {
    this.refs.twilioVideo.setLocalVideoEnabled(!this.state.isVideoEnabled)
      .then(isEnabled => this.setState({ isVideoEnabled: isEnabled }))
  }
