### ISSUE TITLE
Activate the flashlight?

### ISSUE THREAD

**Issue by mfkrause** [blackuy/react-native-twilio-video-webrtc#254]
Does this library have any native hook to support activating the flashlight on demand? Or any other idea on how we could achieve this?

**Comment by slycoder** [comment]
I’m not aware of any affordance in the twilio api that we could hook into here (correct me if I’m wrong) which means you’d have to do it separately using a library like react-native-torch.

**Comment by mfkrause** [comment]
Got it. Will do so then. Thanks!
