### ISSUE TITLE
Enabling `isDominantSpeakerEnabled` but is a getter only

### ISSUE THREAD

**Issue by quachsimon** [blackuy/react-native-twilio-video-webrtc#257]
I'm going through the Twilio [docs](https://www.twilio.com/docs/video/detecting-dominant-speaker) on enabling `isDominantSpeakerEnabled`.

However, when I try to I get an error: `No setter method 'setIsDominantSpeakerEnabled:' for assignment to property`

Upon digging into the property I see that is it only a `getter` property.

I'm on the latest 2.10.x version. 

Am I missing something to implement this for a react native project?

**Comment by slycoder** [comment]
I've never tried this myself, but if you throw up a PR I can try to take a look (and help get that into master!)

**Comment by Saumyadip-Pramanik** [comment]
@quachsimon you are right "isDominantSpeakerEnabled" is not implemented in the files yet as described in the following link: 
https://www.twilio.com/docs/video/detecting-dominant-speaker
I have checked the methods and adding the method in the following file (for iOS):
https://github.com/blackuy/react-native-twilio-video-webrtc/blob/master/ios/RCTTWVideoModule.m
Line No. 385 will get the job done I guess.

**Comment by hmolotsi** [comment]
> I've never tried this myself, but if you throw up a PR I can try to take a look (and help get that into master!)

@slycoder, will you be adding a dominantSpeakerChanged property to TwilioVideo?

**Comment by slycoder** [comment]
Unfortunately I've got too much on my plate to do it myself, but as always PRs are welcome.

**Comment by remigijusbalc** [comment]
hey, I created pr for this feature https://github.com/blackuy/react-native-twilio-video-webrtc/pull/440
