### ISSUE TITLE
Is this library still actively maintained?

### ISSUE THREAD

**Issue by JamieCorkhill** [blackuy/react-native-twilio-video-webrtc#258]
Hello.

I'm just wondering if this library will be actively maintained and updated to reflect the official Twilio Video latest API changes.

Thanks.

**Comment by slycoder** [comment]
Hi,I don't know if this directly answers your question but I actively use this library in my day-job project, so it behooves me to keep this project working smoothly.  That being said, my bandwidth is limited in terms of adding all the latest and greatest to this library so any help from the community is welcome!

**Comment by JamieCorkhill** [comment]
Thanks @slycoder, that helps.

I'm looking to use it in production as well, which was why I asked.

I'd be happy to help maintain if you need it.

**Comment by JamieCorkhill** [comment]
@slycoder Do you officially support TypeScript usage?

**Comment by slycoder** [comment]
There's no explicit support for typescript in the repo.  That being said, if you wanna add typings that would be super welcome =).

**Comment by JamieCorkhill** [comment]
I'll put together a PR when/if I can find the time, @slycoder. Thanks.
