### ISSUE TITLE
regarding the roooms id

### ISSUE THREAD

**Issue by CVRamana** [blackuy/react-native-twilio-video-webrtc#264]
ERROR:  {"reason": "", "roomName": "AC924e739cb03295e47ecc2d47cb905716", "roomSid": ""}

**Comment by slycoder** [comment]
Hi, did you have an issue?  If so could you follow the issue template and fill out some of the reproduction details?

**Comment by CVRamana** [comment]
it is showing the following error in  _onRoomDidFailToConnect  fuction-

ERROR:  {"error": "Invalid Access Token", "roomName": "Raman", "roomSid": ""}
i have given the roomname="Raman"
and token="My_auth_token",
