### ISSUE TITLE
When building for Android I get an Error

### ISSUE THREAD

**Issue by vvillait88** [blackuy/react-native-twilio-video-webrtc#27]
### Steps to reproduce
1. Follow integration steps for Android
2. Run react-native run-android in terminal
3. Spits out this error:
`error: package com.twiliorn.library does not exist
import com.twiliorn.library.TwilioPackage;`

### Environment
- **Node.js version**: 6.9.1
- **React Native version**: 0.46.4
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: "master"

**Comment by bilby91** [comment]
Hello @vvillait88 !

Have you followed the installation instructions in the README ?

If that is the case maybe we are missing something @slycoder

**Comment by vvillait88** [comment]
@bilby91 Yeah step by step.  Works fine on iOS but for some reason on Android it throws this error.

**Comment by bilby91** [comment]
@vvillait88 Good, let's wait for some comments from @slycoder since he is in charge of the android native code.

**Comment by slycoder** [comment]
@vvillait88 Out of curiosity do you see react-native-twilio-video-webrtc listed in the project view of android studio?

**Comment by ceyhuno** [comment]
Edit `android/app/build.gradle`

Add `react-native-twilio-video-webrtc` in `dependencies` like this:

```
dependencies {
    .....
    .....
    .....
    compile project(':react-native-twilio-video-webrtc')
}
```

**Comment by slycoder** [comment]
Oh yeah, I must've forgotten to add that into the docs.  Lemme do that tout suite

**Comment by slycoder** [comment]
@vvillait88  Can you confirm that that solves the problem for you?

**Comment by vvillait88** [comment]
@slycoder it worked but I also had to add some code to gradle, not sure if its related.

**Error:**
Duplicate files copied in APK META-INF/rxjava.properties

**Add to gradle:**
packagingOptions {
    exclude 'META-INF/rxjava.properties'
}

**Comment by slycoder** [comment]
Ah oops, turns out those are from a dependency that isn't even needed any more.  I'll remove those and that should get rid of the error without any packagingOption hacks.

**Comment by vvillait88** [comment]
@slycoder sounds good, just ping me when we are good to go.  Appreciate all your help!

**Comment by slycoder** [comment]
This is now merged to master.
