### ISSUE TITLE
how to upgrade twilio video to 5.1.2?

### ISSUE THREAD

**Issue by theothersideofgod** [blackuy/react-native-twilio-video-webrtc#271]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Environment
- **Node.js version**:
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: npm version or "master"

**Comment by slycoder** [comment]
We are on the 4.x version of the android api.  I don't think it would be challenging to migrate but I haven't gotten around to it.  If you wanna submit a PR it would be very welcome.

**Comment by slycoder** [comment]
We are on 5.x right now and 6.x is in the works.
