### ISSUE TITLE
remote view very laggy  (video not smoothly) on iphone 

### ISSUE THREAD

**Issue by theothersideofgod** [blackuy/react-native-twilio-video-webrtc#272]
### Steps to reproduce
1. 
2.
3.

### Expected behaviour
video should be smoothly on ios

### Actual behaviour
remote video view very laggy and non smoothly, but audio is ok

### Environment
- **Node.js version**: 
- **React Native version**: 0.61.5
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: npm version or "master"
master

**Comment by slycoder** [comment]
Do you have a little more information you could give?  What connection are you running on? Is it happening consistently? If you adjust the video quality settings does it improve things?

**Comment by theothersideofgod** [comment]
Hi, Jonathan,
Thank you for your reply.
I try to upgrade the code to 2.10.2 to set the "simulcast" (
https://support.twilio.com/hc/en-us/articles/115007485348-Bandwidth-consumption-and-usage-with-Twilio-Programmable-Video-)
look like better than before, but i don't know if it is root cause.
What "connection" you talk about here? and where can i set the video quality? on twilio console or in react native code? thanks

**Comment by slycoder** [comment]
Unfortunately you'll have to dive into the code to change the video constraints (it's on the todo list to make this settable from the JS api). 

https://github.com/blackuy/react-native-twilio-video-webrtc/blob/master/ios/RCTTWVideoModule.m#L325
