### ISSUE TITLE
After providing room name and access token app failed to connect to the room

### ISSUE THREAD

**Issue by wasiquehaider** [blackuy/react-native-twilio-video-webrtc#288]
### Steps to reproduce
1.install example app
2.run react-native run-android
3. provided data 
` this.refs.twilioVideo.connect({
      roomName: this.state.roomName,
      accessToken: this.state.token,
    });`
4. on connect button pressed the screen closes

### Expected behaviour

It should connect to a room after providing valid parameters.

### Actual behaviour

The TwilioVideo component returns a failed response and the _onRoomDidFailToConnect method's error parameter results in:
`{
  reason:'',
  roomSid:'',
  roomName:'DailyStandup'
}`

### Environment
- **Node.js version**:10.16.3
- **React Native version**:0.59.9
- **React Native platform + platform version**: iOS 9.0 + android version : 9 

### react-native-twilio-video-webrtc
**Version**: npm version or "master"

**Comment by stevelizcano** [comment]
Did you generate your token according to the Twilio docs? I.e. a rest call to a backend using that information will return a signed token that you use to connect.

**Comment by wasiquehaider** [comment]
@stevelizcano yeah it has been fixed. I needed to create the access token from the tools option. I am closing this issue. :)
