### ISSUE TITLE
Android onParticipantAddedVideoTrack is undefined

### ISSUE THREAD

**Issue by timmeh-m** [blackuy/react-native-twilio-video-webrtc#29]
I'm having some trouble connecting two devices (one android, one iOS) together into the same room. The iOS device has details on the android participant when it joins a room, but the Android device reports back undefined for details on the iOS device, but it does recognise that their is a participant as the function is called. Is there something I have missed?

**Comment by slycoder** [comment]
The Android version doesn't have all the functionality of the iOS version quite yet; this particular callback may not be up to snuff yet.  

We're totally open to PRs if you wanna take a stab at supporting this; otherwise I might have time to work on this in the next few days as well.

**Comment by slycoder** [comment]
Do you mind letting me know what fields in particular you're looking for?

**Comment by ttlpta** [comment]
Same issue with android connect to android..

**Comment by timmeh-m** [comment]
Sorry the late response.

_onParticipantAddedVideoTrack = ({participant, track}) => {
 //participant and track contain values on iOS, but on android; both fields are undefined
}

I actually got around this issue, the Android version in the example you've done is able to display the remote video feed from whatever platform (not sure how that works given it's not being set in react-native unlike the iOS counterpart which does, perhaps that's something you've done under the hood), but for my project as long as the functions are being called what they contain is irrelevant.

**Comment by bilby91** [comment]
Hello @timmeh-m !

I just reviewed a little bit the Android version and it seems to be implemented so you should be receiving the track and participant when a videoTrack is added. 

If you are not getting this information on Android I guess that we probably have a bug. Can you confirm my assumptions @slycoder ?

**Comment by slycoder** [comment]
It's a bug in the library ... fix is on its way.

**Comment by bilby91** [comment]
@timmeh-m @ttlpta Can you try master branch ?

**Comment by ttlpta** [comment]
<img width="282" alt="screen shot 2017-08-09 at 3 03 50 pm" src="https://user-images.githubusercontent.com/9917124/29111318-054d354e-7d14-11e7-898a-e0f04350c8b6.png">
I pulled code at master so i have met this bug when test android connect to android. IOS is still OK

**Comment by slycoder** [comment]
Ruh roh, looks like update hotspot issue again.   Do you have some sample code you can share which reproduces the issue?

**Comment by ttlpta** [comment]
Sorry, I have clone and run agains. It's fine. When I try to join many participant to the conversation like IOS. It has this bug. Android dont allow to do that?
![20750900_1136328649802652_1674792855_n](https://user-images.githubusercontent.com/9917124/29164195-e59a5148-7de8-11e7-9fa8-40b96f011573.jpg)

**Comment by slycoder** [comment]
What does your onParticipantAddedVideoTrack handler look like?

**Comment by slycoder** [comment]
Yes, android currently does not support multiple (i.e > 2) participants.

**Comment by ttlpta** [comment]
Thank you very much

**Comment by mousikosk** [comment]
@slycoder Thanks for the library. Any chance supporting multiple participants on android is in the pipeline?

**Comment by bilby91** [comment]
We have an open PR for that :)

**Comment by AkshayBarad** [comment]
I'm having some trouble. when participant join room only audio track work.
participant video track not load.
CustomTwilioVideoView.java
```
if (participant.getVideoTracks().size() > 0) {
            Log.i("CustomTwilioVideoView", "Participant DOES HAVE VIDEO TRACKS");
            addParticipantVideo(
                    participant,
                    participant.getVideoTracks().get(0)
            );
        } else {
            Log.i("CustomTwilioVideoView", "Participant DOES NOT HAVE VIDEO TRACKS");

        }
```
In this case i everytime see "Participant DOES NOT HAVE VIDEO TRACKS".

**Comment by auggernaut** [comment]
I'm noticing this too @AkshayBarad. Participant Audio works. No video.

react-native: 0.50.4
react-native-twilio-video-webrtc: 1.0.2
Between devices: Pixel 1 and iPhone 6

**Comment by thanhnvpk01168** [comment]
hi @slycoder  @timmeh-m @auggernaut @AkshayBarad @bilby91 
Can you help me?
I have the same problem: Android device camera cannot be tracked by onParticipantAdded/RemovedVideoTrack
