### ISSUE TITLE
Android onRoomDidFailToConnect error reason ist empty ("")

### ISSUE THREAD

**Issue by DanielJanke** [blackuy/react-native-twilio-video-webrtc#290]
### Steps to reproduce
1.  Do anything to call the onRoomDidFailToConnect method

### Expected behaviour
I expect that the SDK is give me the reason why connecting failed in order to show the user an proper error message.

### Actual behaviour
The method throw me this object

```
{
    reason: ""
    roomSid: ""
    roomName: "RoomName"
}
```
On iOS it gives me a correct error message

### Environment
- **Node.js version**:
- **React Native version**: 62
- **React Native platform + platform version**: Android 10

### react-native-twilio-video-webrtc
**Version**: master

**Comment by slycoder** [comment]
We just pass back the exception that twilio provides, so it's weird that it's giving you a blank explanation.  It's also quite weird that you have a blank roomSid since that would indicate that the connection didn't get very far.  How did you create the room?

**Comment by ravik2015** [comment]
Hi Slycoder! 
I am also facing the same issue.

I have created the room using the testingTools provided by the Twillio in the programmable video section.
Please let me know what I am missing?

**Comment by slycoder** [comment]
Can you share how you're calling `connect`?  Perhaps instead of `accessToken` you're passing in the room?

**Comment by DanielJanke** [comment]
@slycoder 

`this.twilioVideoRef.current.connect({
       roomName: tokenDecoded.grants.video.room,
        accessToken: this.props.token,
  });
`

My calls are working as expected, only thing which doesn't work are these error messages.

**Comment by slycoder** [comment]
Can you try changing `getExplanation()` on this line: https://github.com/blackuy/react-native-twilio-video-webrtc/blob/master/android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java#L731 to `message` and see if that fixes the issue?

**Comment by DanielJanke** [comment]
@slycoder 

Yes it's working! :)

But one thing to fix is that android gives me:

`{roomSid: "", reason: "Access Token expired or expiration date invalid", roomName: "2020-05-06T14:00:00.000Z"}`

and iOS:

`{roomSid: "", error: "Access Token expired or expiration date invalid", roomName: "2020-05-06T14:00:00.000Z"}`

The key is not the same (`error` & `reason`)

**Comment by slycoder** [comment]
Gah, of course.  I'll make it consistent with iOS.

**Comment by slycoder** [comment]
#302
