### ISSUE TITLE
[iOS] audio cuts out when app in background

### ISSUE THREAD

**Issue by raphaelrk** [blackuy/react-native-twilio-video-webrtc#292]
### Steps to reproduce
1. Use below code, make a release build (seems to work in debug for me)
2. Go to home screen without closing the app, audio will cut out
3. Reopen the app, audio is still cut out

Using the code below, although with an app around it (that also has `react-native-callkeep`, `react-native-incall-manager`, and `react-native-voip-push-notification` installed, audio background mode is enabled), so hopefully it reproduces -- maybe I have to tweak e.g. how I do RNCallKeep.startCall and things will start working. I also think at some point I wasn't having this issue, so I wonder if there's some way that changing the below code fixes this issue.

```
import React, { useEffect, useRef, useState } from 'react';
import { StyleSheet, View } from 'react-native';
import { useSelector } from "react-redux";
import { TwilioVideo, TwilioVideoLocalView, TwilioVideoParticipantView } from "react-native-twilio-video-webrtc";
import { useDimensions } from "react-native-hooks";

export default function CallScreen() {
  const { window } = useDimensions();

  const uuid = "...";
  const access_token = "...";

  const twilioVideo = useRef();
  const [videoTracks, setVideoTracks] = useState([]);

  useEffect(() => {
    twilioVideo.current.connect({ roomName: uuid, accessToken: my_access_token });
    return () => {
      twilioVideo.current.disconnect();
    };
  }, []);

  return (
    <View style={styles.container}>

      <View style={StyleSheet.absoluteFill}>
        {videoTracks.map(({ track, participant }) => (
          <View key={track.trackSid} style={{ flex: 1, width: window.width }}>
            <TwilioVideoParticipantView
              style={{
                minWidth: window.width,
                minHeight: 30,
                flex: 1,
                backgroundColor: '#333',
              }}
              key={track.trackSid}
              trackIdentifier={{
                participantSid: participant.sid,
                videoTrackSid: track.trackSid,
              }}
            />
          </View>
        ))}

        <TwilioVideoLocalView enabled={true} style={styles.myVideo}/>
      </View>

      <TwilioVideo
        ref={twilioVideo}
        onParticipantAddedVideoTrack={({ participant, track }) => {
          setVideoTracks(prevTracks => [...prevTracks, { participant, track }]);
        }}
        onParticipantRemovedVideoTrack={({ participant, track }) => {
          setVideoTracks(prevTracks => [...prevTracks].filter(t => t.track.trackSid !== track.trackSid));
        }}
      />
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  myVideo: {
    position: 'absolute',
    bottom: 120,
    right: 20,
    width: 120,
    height: 120 * 16/9,
    backgroundColor: '#e0e0e0',
    borderRadius: 12,
    overflow: 'hidden',
  },
});
```

### Expected behaviour
When my app goes to the background the audio should keep playing

### Actual behaviour
The audio stops, and when I reopen the app I can't get it to start again without restarting the app

### Environment
Using expo bare workflow, so `expo diagnostics` outputs:
```
  Expo CLI 3.17.23 environment info:
    System:
      OS: macOS 10.15.4
      Shell: Unknown - /usr/local/bin/fish
    Binaries:
      Node: 13.11.0 - /usr/local/bin/node
      Yarn: 1.22.4 - /usr/local/bin/yarn
      npm: 6.13.7 - /usr/local/bin/npm
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5199772
      Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
    npmPackages:
      expo: ~37.0.3 => 37.0.7 
      react: ~16.9.0 => 16.9.0 
      react-native: ~0.61.5 => 0.61.5 
    npmGlobalPackages:
      expo-cli: 3.8.0
```
I'm testing with two phones, an iPhone 7 on 13.4 and an iPhone Xs on 13.3.1, and the issue only occurs on the iPhone 7 which is also low on storage / memory, and is the one starting the call, while the Xs is none of those.

### react-native-twilio-video-webrtc
**Version**: master (1.0.2-1)

**Comment by slycoder** [comment]
On the iPhone 7 is the app getting killed in the background?

**Comment by raphaelrk** [comment]
I don't think so. It can happen even just pulling the notification tray down a bit or when going into the task switcher. Seems to happen on the Xs sometimes too, but less often. Sometimes the audio still works though, which may point to e.g. memory being the issue -- but haven't run into the same issue trying out other video calling apps, so maybe it's not that

**Comment by slycoder** [comment]
Can you try pulling master?   The latest version has better events for interruptions; logging those may help give a clue as to what's going on.

**Comment by raphaelrk** [comment]
Oh wow, the new master looks sweet!

It seems like I *might* have just fixed it. The two changes I most recently made:
- made sure I was only telling RNCallKeep to display the incoming call once, on the native side. Previously I also had code on the js side that would try displaying it.
- Added this code in my "Root.js" that uses `react-native-audio-session`:

```
useEffect(() => {
    AudioSession.setCategoryAndMode('PlayAndRecord', 'VideoChat', 'MixWithOthers').then(() => {
      console.log('Success!')
    }).catch(error => {
      console.log('Error!')
    });
  });
```

If I run into problems again, will update the thread. Thank you @slycoder 😊

**Comment by callmemonky** [comment]
@raphaelrk Hey!
When my app is in background, audio and video stops working altogether. When I open the app in the foreground, it starts working again. Any idea how to make mic persist in the background? 
@slycoder

**Comment by ryantando** [comment]
> @raphaelrk Hey! When my app is in background, audio and video stops working altogether. When I open the app in the foreground, it starts working again. Any idea how to make mic persist in the background? @slycoder

@callmemonky hi, did you find any solution on this?
