### ISSUE TITLE
local view is mirrored on iOS in latest update

### ISSUE THREAD

**Issue by raphaelrk** [blackuy/react-native-twilio-video-webrtc#297]
### Steps to reproduce
1. use latest master
2. local view is mirrored

### Expected behaviour
When I move my finger left, should move left in the preview

### Actual behaviour
Moves right

Could either change this default back or make the mirroring an option. In the meanwhile can also use `transform: [{ scaleX: -1 }]` to re-mirror

### react-native-twilio-video-webrtc
**Version**: master

**Comment by slycoder** [comment]
Strange, the code should be mirroring things.  Could you set a breakpoint here:

https://github.com/blackuy/react-native-twilio-video-webrtc/blob/master/ios/RCTTWVideoModule.m#L111

And lemme know if the camera is being identified as a front camera and whether this code path is being called?

**Comment by brianhiss** [comment]
@slycoder I am having the same issue as @raphaelrk, the new Master (#5b8c610) for iOS 3.2.x is not mirrored properly.

I've set a breakpoint and `NSlog()` at https://github.com/blackuy/react-native-twilio-video-webrtc/blob/master/ios/RCTTWVideoModule.m#L111, it never gets there.

I am on iOS 13.3.1, iPhone 7 Plus, RN 0.61.5.

Let me know how I can help diagnose further.

**Comment by slycoder** [comment]
That's really strange.  Are you using the example app or did you roll your own (if the latter is there any code you can share)?  I dunno how you'd even render a local previous without hitting that function.

**Comment by brianhiss** [comment]
@slycoder Rolled own, can't share that specific code, but it's literally almost a carbon copy of your example.

It hits the function, it just doesn't go into: `if (self.camera && self.camera.device.position == AVCaptureDevicePositionFront)`, if that clears it up some.

**Comment by slycoder** [comment]
Ah ok, I misunderstood then. If you've got the logging handy, can you check if self.camera has a reasonable value in there?  One thing just occurred to me --- if this thing gets mounted *before* the camera gets turned on then we won't know whether or not we need to mirror.

**Comment by brianhiss** [comment]
@slycoder Hope you had a nice Memorial Day Weekend.

I haven't been able to test that since I'm back now as I had reverted to code to 2.x for additional tests. I will try to get back to 3.x soon.

**Comment by slycoder** [comment]
@brianhiss You too.  No worries, there's a fix on master now for 3.x; if you run into any issues lemme know.
