### ISSUE TITLE
Is Expo supported?

### ISSUE THREAD

**Issue by cristhian-net** [blackuy/react-native-twilio-video-webrtc#298]
As it is the default option for React Native new projects, I want to know if you support Expo to do video call. I couldn't make it work and that is why I am asking. There is an error when I try to use this package's components:
![image](https://user-images.githubusercontent.com/12214429/81180322-39b5f280-8f81-11ea-9ae3-5f8f1da330b6.png)

Should I eject? Thanks!

**Comment by slycoder** [comment]
I don't use expo, but based on my limited understanding you'll have to eject / use expo bare.

**Comment by cristhian-net** [comment]
Ok, thanks @slycoder. I will give it a try. Cheers.
