### ISSUE TITLE
ios Pods Unable to satisfy the following requirements

### ISSUE THREAD

**Issue by ShadeIsaac** [blackuy/react-native-twilio-video-webrtc#30]
### Steps to reproduce
1. Follow integration steps for iOS
2. Run pod install
3. Error : 

    [!] Unable to satisfy the following requirements:
    - `TwilioVideo (>= 1.0.1)` required by `react-native-twilio-video-webrtc (1.0.2)`
    Specs satisfying the `TwilioVideo (>= 1.0.1)` dependency were found, but they required a higher minimum deployment target.

### Environment
- Node 8.1.4
- React Native 0.47.1
- iOS 9.0

**Comment by ShadeIsaac** [comment]
Ok I corrected it, I just had to add these two lines at the top of my Podfile :

    platform :ios, '9.0'
    use_frameworks!

Factually not related to the module itself, sorry for thi issue, hope it'll help people in the future !

**Comment by bilby91** [comment]
@ShadeIsaac Sorry for the late reply! Great that you have it running! Closing this one
