### ISSUE TITLE
Update Installation steps for iOS

### ISSUE THREAD

**Issue by RatebSeirawan** [blackuy/react-native-twilio-video-webrtc#304]
Latest update changes the podspec file to point to platform=11 for ios
had to change my Podfile from version 8 to 11 to make it work.

**Comment by steelbrain** [comment]
Fyi requirement of iOS 11 comes straight from Twilio: https://www.twilio.com/docs/video/ios#prerequisites

**Comment by RatebSeirawan** [comment]
> Fyi requirement of iOS 11 comes straight from Twilio: https://www.twilio.com/docs/video/ios#prerequisites

yes, I get you, I am just suggesting to update the docs so people don't wander too much.

**Comment by steelbrain** [comment]
Requesting your thoughts @ https://github.com/blackuy/react-native-twilio-video-webrtc/pull/305
Feel free to recommend better wording if mine isn't clear
