### ISSUE TITLE
Invalid Access Token

### ISSUE THREAD

**Issue by shareef-dweikat** [blackuy/react-native-twilio-video-webrtc#306]
### Expected behaviour
After i call 
this.refs.twilioVideo.connect({ roomName: this.state.roomName, accessToken: this.state.token })
App is supposed to start a video chat.

### Actual behaviour
i get this error in the console {"error": "Invalid Access Token", "roomName": "DailyStandup", "roomSid": ""}

### Environment
- **Node.js version**: v13.13.0
- **React Native version**: 0.62.2
- **React Native platform **:  Android 

### react-native-twilio-video-webrtc
npm version: 6.14.4

**Comment by slycoder** [comment]
How are you generating your access token?

**Comment by slycoder** [comment]
Does the same access token work on other platforms?

**Comment by RatebSeirawan** [comment]
same here, it was working perfectly until I updating to latest package version

**Comment by RatebSeirawan** [comment]
UPDATE:

I used the old version of react-native-twilio-video-webrtc that used to work for me, and it shows the same error, its quite suspicious, and I hope this information helps. I am also testing to generate tokens from different accounts to makes sure that all is working well besides I am using twilio-chat and the token is working there so!

**Comment by slycoder** [comment]
Are you passing in both the roomName and the accessToken?  If so, can you try just passing in the accessToken?

**Comment by RatebSeirawan** [comment]
> Are you passing in both the roomName and the accessToken? If so, can you try just passing in the accessToken?

I tried passing the accessToken only and got this error

```
error:Signaling connection error
```

**Comment by LiatheHNaj** [comment]
I am getting the same error just using the example index code in my application. is there necessary editing i need to do?

**Comment by slycoder** [comment]
So you generally shouldn't be putting the roomName into the call to connect.  I'll update the example code to reflect this.

@RatebSeirawan I suspect the signaling connection error is a different issue.  A quick google finds a few other cases of this happening:

https://github.com/twilio/video-quickstart-ios/issues/252
https://github.com/twilio/video-quickstart-ios/issues/35

Can you dig through the debug logs and see if it matches either of these cases?

**Comment by LiatheHNaj** [comment]
let me know when you update it

**Comment by LiatheHNaj** [comment]
Any update?

**Comment by LiatheHNaj** [comment]
> same here, it was working perfectly until I updated to latest package version.
> Btw I am testing on iOS

how are you generating the access tokens

**Comment by slycoder** [comment]
@LiatheHNaj You should generate access tokens following the instructions in the twilio documentation: https://www.twilio.com/docs/video/tutorials/user-identity-access-tokens#generating-access-tokens

**Comment by slycoder** [comment]
I've gone ahead and updated the example.
