### ISSUE TITLE
Getting Error with Tokens Using the Example code

### ISSUE THREAD

**Issue by LiatheHNaj** [blackuy/react-native-twilio-video-webrtc#311]
Using the example code that was given. same problem on android and ios

### Expected behaviour
Once i press connect it should load the video chat

### Actual behaviour
it loads the video chat i can see my self for a second and gives an ERROR:  {"error": "Invalid Access Token", "roomName": "", "roomSid": ""}

### Environment
- **Node.js 14.2.0**:
- **React Native 0.61.5**:
- **React Native platform + platform version**: Android

### react-native-twilio-video-webrtc
**Version**: npm 6.14.4

**Comment by LiatheHNaj** [comment]
Where do i put my twilio access tokens at

**Comment by slycoder** [comment]
I don't quite understand the question.  Once you have the room access token you should be able to place it into the example app.
