### ISSUE TITLE
Requesting to maintain versioning.

### ISSUE THREAD

**Issue by Ashwani-WCC** [blackuy/react-native-twilio-video-webrtc#316]
The package must have versioning, so that the code does not break with every npm install.
The users of the package must have a way to stick to a particular release.

Currently the way to install this package is as below:
npm install https://github.com/blackuy/react-native-twilio-video-webrtc --save
 
IMO, this not a good practice to refer to a library like the above. There should a shorthand like npm install react-native-twilio-video-webrtc.

Initially we were targeting iOS 10.0 but due to regular updates in this library we had to move to iOS 11.0, since the library is dependent on the latest version of TwiliioVideo which supports minimum 11.0.

Please check this out for semantic versioning in npm repo:
https://docs.npmjs.com/about-semantic-versioning

**Comment by slycoder** [comment]
So if you want to install the package from github, I *strongly* recommend that you peg it to a commit sha to prevent exactly the issue you're having.

I would love to get releases of the form 'npm install react-native-twilio-video-webrtc'.  Unfortunately, that package already exists on npm and I don't have access to that account.
