### ISSUE TITLE
The development server returned response error code: 500

### ISSUE THREAD

**Issue by pixsolution** [blackuy/react-native-twilio-video-webrtc#317]
### Steps to reproduce
1. I installed it following your steps by npm install https://github.com/blackuy/react-native-twilio-video-webrtc --save
2. Tried to run the app by console
3. It show "the development server returned response error code: 500"

### Expected behaviour
Should run/open the app. As it does without the package, before installing the package my app opened perfect

### Actual behaviour
![Captura de Pantalla 2020-05-29 a la(s) 9 15 03 a  m](https://user-images.githubusercontent.com/47191848/83273025-43bbc180-a1cc-11ea-88ec-6600208c89ec.png)

### Environment
- **Node.js version**: 12.16.0
- **React Native version**: 0.60.5
- **React Native platform + platform version**: Android

### react-native-twilio-video-webrtc
**Version**: attached capture how it show the version
![Captura de Pantalla 2020-05-27 a la(s) 12 01 04 p  m  (1)](https://user-images.githubusercontent.com/47191848/83273616-fd1a9700-a1cc-11ea-964e-98b89052ef75.png)

**Comment by slycoder** [comment]
Based on the trace above, it looks like you're also depending on the twilio rest library.  If you want to use that library you'll probably need a polyfill of some sort.
