### ISSUE TITLE
Not found in project ':react-native-twilio-video-webrtc

### ISSUE THREAD

**Issue by pixsolution** [blackuy/react-native-twilio-video-webrtc#318]
How did I fail trying this way that I indicate here https://github.com/blackuy/react-native-twilio-video-webrtc/issues/317 I tried the following also:
### Steps to reproduce
1. I installed it by `npm i react-native-twilio-video-webrtc` following this https://www.npmjs.com/package/react-native-twilio-video-webrtc
2. I include in dependencies `implementation project(':react-native-twilio-video-webrtc')`
3. When I run I get this error **not found in project ':react-native-twilio-video-webrtc** but I saw it in node modules

### Expected behaviour
It should open/run the app

### Actual behaviour
When I run I get this error **not found in project ':react-native-twilio-video-webrtc** but I saw it in node modules

### Environment
- **Node.js version**: 12.16.0
- **React Native version**: 0.60.5
- **React Native platform + platform version**: Android

### react-native-twilio-video-webrtc
**Version**: ^1.0.1

**Comment by slycoder** [comment]
Did you follow the other steps in the guide given for Android setup?  Unless you do it's not going to work.

**Comment by MrSerWin** [comment]
in RN from version 0.60 should work autolinking. 
so try run your project like this `npx react-native run-android`
