### ISSUE TITLE
status is always connecting, onRoomDidconnect does not fire

### ISSUE THREAD

**Issue by shareef-dweikat** [blackuy/react-native-twilio-video-webrtc#320]
### Steps to reproduce
1. install react-native-twilio-video-webrtc in your project
2. get your access token and roam name from your API, or from Twilio's online Testing Tools.
3. call Twilio's function connect({accessToken, roomName})

### Expected behaviour
I think i should get a connected status, and a video call.

### Actual behaviour
status styes connecting

### Environment
- **Node.js version**:v13.13.0
- **React Native version**:0.62.2
- **React Native platform + platform version**:  Android 10

**Comment by slycoder** [comment]
Do you have some example code you could share?

**Comment by WilliamBlais** [comment]
Same issue here, with the latest commit, and RN 0.61.5 on iOS.

The README and Example/index.js contradict themselves, should twilioVideo.connect() takes the roomName?

**Comment by Balasnest** [comment]
@WilliamBlais In readme code, `_onDidRoomConnect` method is missed. Did you add the method in your code?? If not check [this PR.](https://github.com/blackuy/react-native-twilio-video-webrtc/pull/321/files)

**Comment by slycoder** [comment]
The Example is correct.  I'll update the readme to match that.

**Comment by WilliamBlais** [comment]
@slycoder Could you explain why the roomName option is gone? Is it optional?

**Comment by slycoder** [comment]
roomName is no longer needed since the room is uniquely identified from the access token.

**Comment by ReeturajThakur7** [comment]
Any help regarding this issue how did you guys resolved this?
