### ISSUE TITLE
iPhone gets heated up while on call 

### ISSUE THREAD

**Issue by Balasnest** [blackuy/react-native-twilio-video-webrtc#323]
### Steps to reproduce
1. Install the app in iOS
2. Initiate the very first call for 5 mins. We can identify heat slightly.
3. Do second call for more than 3 mins. we can drastically feel the heat surrounding to the back camera area.

### Expected behaviour
Phone gets heated up while on call (more than 3 mins)

### Actual behaviour
Phone should not get heated up.

**call went for 10 mins:**
- The Caller runs on this library - 47% on call start and 39% on call end. **8% DRAINED**
- The receiver runs on ios native code - 44% on call start and 37% on call end. **7% DRAINED**
Anyway, there is no much difference in the platform. but why its consuming 7-8% in a single call?

Did anybody gone through or notice this? Is it an expected behaviour?

### Environment
React Native Environment Info:
    Binaries:
      Node: 10.16.1 - /usr/local/bin/node
      npm: 6.9.0 - /usr/local/bin/npm
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.9 => 0.59.9
    npmGlobalPackages:
      react-native-cli: 2.0.1
### react-native-twilio-video-webrtc
**Version**: master

**Comment by Balasnest** [comment]
@slycoder I need your help. Let me know your thoughts.

**Comment by slycoder** [comment]
Is this using the example?  Is there code you can share?  Or alternatively, is there any profiling information you can share?  If it's happening inside the twilio library itself our options may be limited, but if it's happening due to some way in which we're rending the views, there may be some optimization opportunities.

**Comment by Yarkhan** [comment]
I have this happening on an iPhone 7.
It is an empty screen with nothing on it, just a <TwilioVideo /> component connecting to a room and receiving audio from a single participant.

**Comment by Balasnest** [comment]
@slycoder Hi can you review [this PR ](https://github.com/blackuy/react-native-twilio-video-webrtc/pull/329)

**Comment by slycoder** [comment]
Will do, thanks for the thorough investigation.
