### ISSUE TITLE
Other parties can hear only noise when connecting with earphone on android

### ISSUE THREAD

**Issue by Balasnest** [blackuy/react-native-twilio-video-webrtc#327]
### Steps to reproduce
1. Connect with earphone in android device.
2. Initiate call
3. Voice is not audible / clear to other parties
4. when plug earphone in-between while in call, audio is still on phone speaker. Not changed to default one.

### Expected behaviour
Other parties should hear voice when using earphones on android. 
Whenever earphone is plugged, audio should switch from speaker to earphone by default. 

### Actual behaviour
Only noise is coming to other parties when using earphone on android.
Whenever earphone is plugged, audio is not switched from speaker to earphone by default. 

### react-native-twilio-video-webrtc
**Version**: "master"

**Comment by Balasnest** [comment]
Is anybody facing this issue?

**Comment by Balasnest** [comment]
Related to #285

**Comment by slycoder** [comment]
When you mention that only noise is being sent across, does that mean that neither the earphone nor the speakerphone are picking up audio?

**Comment by Balasnest** [comment]
OMG. Sorry. My oneplusone device's microphone is not working when connect with earphone or bluetooth. I just did a quick check with OKAY google and mic didn't work.

Thanks for your help @slycoder
