### ISSUE TITLE
When disable/enable video onParticipantDisabledVideoTrack and onParticipantEnabledVideoTrack not triggered

### ISSUE THREAD

**Issue by diegomichell** [blackuy/react-native-twilio-video-webrtc#330]
### Steps to reproduce
1. Join a call from 2 mobile clients disable/enable video call on one of them

### Expected behaviour
Video should be disabled for the other participants and onParticipantEnabledVideoTrack and onParticipantDisabledVideoTrack should be called.

### Actual behaviour
Currently when video is disable/enable onParticipantRemovedVideoTrack and onParticipantAddedVideoTrack are getting call, the reason is that unpublish and publish track methods are being call from android toggleVideo and ios setVideoEnabled methods, that shouldn't happend, also we don't need to create a new LocalVideoTrack instance.

### Environment
- **Node.js version**: v12.16.1
- **React Native version**: 0.62.2
- **React Native platform + platform version**: 4.9.0, iOS 13.5 and Android 10

### react-native-twilio-video-webrtc
**Version**:  "master"

**Comment by diegomichell** [comment]
I fixed on my fork by removing some changes, not perfect, will submit a PR so it can be improved upon.

**Comment by slycoder** [comment]
Thank you @diegomichell !
