### ISSUE TITLE
Rotate Upside Down Video stream 

### ISSUE THREAD

**Issue by theothersideofgod** [blackuy/react-native-twilio-video-webrtc#333]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
We have a situation that we need the phone upside down when video calling but other participant will see upside down video stream, is there any way to make participant see the right side up stream while the phone upside down? 

### Actual behaviour
Tell us what happens instead

### Environment
- **Node.js version**:
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: npm version or "master"

**Comment by slycoder** [comment]
Can you just apply a transform on the view on the receiver side?

**Comment by theothersideofgod** [comment]
Hi, @slycoder 

Yeah, I tried that like you say but how about the recording video?

recording video will upside down...

**Comment by slycoder** [comment]
I don't have any other ideas but you might want to reach out to the twilio team and see if they have any ideas.
