### ISSUE TITLE
Android compilation Error

### ISSUE THREAD

**Issue by ShadeIsaac** [blackuy/react-native-twilio-video-webrtc#34]
When configuring it on Android, I follow the steps given in the documentation and I get this error on buid (using react-native run-android).

> node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/TwilioPackage.java:27:
> error: method does not override or implement a method from a supertype
> 
>     @Override
>     ^

> Note: node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java uses or overrides a deprecated API

>1 error :react-native-twilio-video-webrtc:compileReleaseJavaWithJavac FAILED

> FAILURE: Build failed with an exception.

It's kinda blocking me from doing what I have to. If you have any solution, I would love it

  [1]: https://github.com/blackuy/react-native-twilio-video-webrtc

**Comment by slycoder** [comment]
Ah, I think the latest version of RN changed the interface a bit.  Should be a quick change, I'll get it out later today.

**Comment by ShadeIsaac** [comment]
Thanks man ! 👍

**Comment by bilby91** [comment]
Can we close this one with #35 merged ?

**Comment by slycoder** [comment]
Yup.  @ShadeIsaac feel free to re-open if this is still causing trouble for you.
