### ISSUE TITLE
No video on iOS, only sound. Running example project

### ISSUE THREAD

**Issue by gazedash** [blackuy/react-native-twilio-video-webrtc#348]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Environment
- **Node.js version**:
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: npm version or "master"

**Comment by slycoder** [comment]
Can you give a little more detail?  What is the other party in this case?

**Comment by gazedash** [comment]
Latest RN, iOS 13.5, I used twilio testing tools room

I gave permission for mic and camera for example app

**Comment by gazedash** [comment]
I tried everything, except adding the style to  `TwilioVideoParticipantView` and it worked

```
       <TwilioVideoParticipantView
                style={styles.remoteVideo}
                key={trackSid}
                trackIdentifier={trackIdentifier}
              />

```

```
  remoteVideo: {
    width: '100%',
    height: '100%',
  },
```

I am very sorry, how could I lose this prop I have no idea
