### ISSUE TITLE
[iOS] Crash after last commit

### ISSUE THREAD

**Issue by eresid** [blackuy/react-native-twilio-video-webrtc#349]
### Steps to reproduce
1. Try to connect with last master on iOS (199585e2fd2fda399c539f65333949c553e6b520)
![зображення](https://user-images.githubusercontent.com/3881790/87301117-af0ce900-c517-11ea-8120-181d07c156cc.png)

### Expected behaviour
The video call will be started

### Actual behaviour
The crash has happened

### Environment
- **Node.js version**: v13.9.0
- **React Native version**: 0.62.2
- **React Native platform + platform version**: iOS 13.0

### react-native-twilio-video-webrtc
**Version**: "master"

**Comment by Balasnest** [comment]
It's working fine for me in master. Could you please check whether the node_module or iOS code updated properly? Clean build and try again.
