### ISSUE TITLE
Unfortunately, App has stopped.

### ISSUE THREAD

**Issue by zuhairnaqi** [blackuy/react-native-twilio-video-webrtc#355]
### Steps to reproduce
I'm using react-hooks
1. App crash on render TwilioVideo
`<TwilioVideo
          ref={ref => {
            if (ref) {
              twilioRef = ref;
            }
          }}
          onRoomDidConnect={_onRoomDidConnect}
          onRoomDidDisconnect={_onRoomDidDisconnect}
          onRoomDidFailToConnect={_onRoomDidFailToConnect}
          onParticipantAddedVideoTrack={_onParticipantAddedVideoTrack}
          onParticipantRemovedVideoTrack={_onParticipantRemovedVideoTrack}
        />`

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Environment
-"react": "16.11.0",
-"react-native": "0.62.2",
-"react-native-twilio-video-webrtc": "git+https://github.com/blackuy/react-native-twilio-video-webrtc.git",

**Comment by slycoder** [comment]
Do you have a little more information you can share?  Code perhaps or even just a more complete log or stack trace?

**Comment by zuhairnaqi** [comment]
> stack

There is no error is shown in console and i copied the same code and paste that in hooks.
App is crashing without any error.

**Comment by zuhairnaqi** [comment]
This answer fixed my solution [`answer`](https://github.com/twilio/video-quickstart-android/issues/430#issuecomment-529443489)
