### ISSUE TITLE
Question(Android): EGL handler - NoSuchFieldException

### ISSUE THREAD

**Issue by chinloongtan** [blackuy/react-native-twilio-video-webrtc#358]
Needed some advice for adding take snapshot feature on Android.

`react-native-view-shot` works for iOS but not Android.

After quite some reading and browsing the native source code, there are example of how to do that in https://github.com/twilio/video-quickstart-android
So I started to piece it together.

I have managed to get bitmap of a frame. However only when it's YUV frame.
Having issue when getting from texture. (depend on device)

Refer https://github.com/aaalaniz/video-quickstart-android/blob/9ee09e7acba1a26e04bdfb294ae7ba5520fd6c7b/exampleMultipartyVideo/src/main/java/com/twilio/examplemultipartyvideo/SnapshotVideoRenderer.java#L59

Initially getting crash for certain device that run `captureBitmapFromTexture `

After debugging, the log was `java.lang.RuntimeException: glCreateShader() failed. GLES20 error: 0`

I have found a workaround from the author of the `video-quickstart-android`. 
Basically to get the active EGL handler and proceed.

https://github.com/aaalaniz/video-quickstart-android/commit/9ee09e7acba1a26e04bdfb294ae7ba5520fd6c7b

So the current issue is `getEglHandler` running into `NoSuchFieldException`. 

Would like to get advice on this matter. 
On how can I get it to work or what is the issue about.

My implementation in the forked repo. (Initially the take snapshot code in `renderFrame` works for `PatchedVideoView`, right now I am creating a `SnapshotVideoRenderer` and trying things out. Same error occurred)

https://github.com/chinloongtan/react-native-twilio-video-webrtc/blob/8ec7b0b6e26a985e4dc55eab80cbbe72eee01bd6/android/src/main/java/com/twiliorn/library/SnapshotVideoRenderer.java#L152

The gist I found.
https://gist.github.com/aaalaniz/bfbc4891c98ef3b23558ff2260cbcc8e#gistcomment-3216076

Any advice or help in pointing the right direction will be very much appreciated.

Thanks in advance.

**Comment by slycoder** [comment]
Wow, you've made it a lot farther than I ever have!  Kudos to you for the progress you've made.  If you want to contribute your fork back, it would be most welcome and maybe someone else from the community will be able to use where you've gotten to as a jumping off point to help you further debug.  

Just taking a quick look, it seems like the workaround is trying to get to a private method on the class which is inevitably going to be subject to change.  Would it be possible instead to use getBitmap?

**Comment by chinloongtan** [comment]
Hey @slycoder , thanks for getting back on this issue. 
As you have suggested, I am actually having success with `getBitmap`! 😃

Give me some time to test with a few more devices and wrap this up. 
I am happy to contribute back. 
Will get back to this.
