### ISSUE TITLE
Screen sleeps on video mode

### ISSUE THREAD

**Issue by zuhairnaqi** [blackuy/react-native-twilio-video-webrtc#359]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Environment
- **Node.js version**:
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: npm version or "master"

**Comment by ahmadtech2** [comment]
Install react-native-keep-awake, very straight forward you can enable awake when connected and stop it on disconnect / page unmounted 
[https://github.com/corbt/react-native-keep-awake](url)
function changeKeepAwake(shouldBeAwake) {
  if (shouldBeAwake) {
    KeepAwake.activate();
  } else {
    KeepAwake.deactivate();
  }
}

//usage:
changeKeepAwake(false);
changeKeepAwake(true);

**Comment by zuhairnaqi** [comment]
> https://github.com/corbt/react-native-keep-awake

There are using NativeModules.KCKeepAwake.activate(), unfortunately this is removed from NativeModules

**Comment by zuhairnaqi** [comment]
@ahmadtech2 mentioned library is working
