### ISSUE TITLE
Unsupported top level event type - OnFrameDimensionsChanged

### ISSUE THREAD

**Issue by Balasnest** [blackuy/react-native-twilio-video-webrtc#361]
### Steps to reproduce
when I render `TwilioVideoParticipantView` with particular width and height style, getting this error.

1. First showing the remote video as thumbnail view.
2. Once check on the thumbnail view changing it to full screen.

Failing at first step itslf. Getting an error after a remote video is rendered, (fully stretched). Not fit with thumbnail view port.

![Screenshot_20200803-190749](https://user-images.githubusercontent.com/6050520/89189772-17526600-d5be-11ea-92a9-097c63eaea82.png)

### Expected behaviour
It's should render based on given layout style.

### Actual behaviour
Its throw `onFrameDimensionsChanged`  error. Happening only in **android**.

### react-native-twilio-video-webrtc
**Version**: master

**Comment by Balasnest** [comment]
@danielr18 @slycoder Can you please help here.

**Comment by slycoder** [comment]
Thanks for the details.  Can you try changing this function in src/TwilioVideoParticipantView.android.js:

```
 buildNativeEventWrappers () {
     return [
       'onFrameDimensionsChanged'
     ].reduce((wrappedEvents, eventName) => {
         return {
           ...wrappedEvents,
           [eventName]: data => this.props[eventName] ? this.props[eventName](data.nativeEvent) : {}
         }
       return wrappedEvents
     }, {})
   }
```

**Comment by Balasnest** [comment]
@slycoder sure will try and test it out this week.

**Comment by rjillason** [comment]
> Thanks for the details. Can you try changing this function in src/TwilioVideoParticipantView.android.js:
> 
> ```
>  buildNativeEventWrappers () {
>      return [
>        'onFrameDimensionsChanged'
>      ].reduce((wrappedEvents, eventName) => {
>          return {
>            ...wrappedEvents,
>            [eventName]: data => this.props[eventName] ? this.props[eventName](data.nativeEvent) : {}
>          }
>        return wrappedEvents
>      }, {})
>    }
> ```

Hi ~ @slycoder I already tried this solution but no help.

**Comment by slycoder** [comment]
Googling around another idea might be that it's a race condition.  Can you add a delay before creating the component and see if that helps?

**Comment by luukschipperheyn** [comment]
I'm consistently running into the same problem with my app. I made a fix that gets rid of the error. PR on the way
