### ISSUE TITLE
ANDROID | Camera / Video view blank (most likely transparent)

### ISSUE THREAD

**Issue by RZulfikri** [blackuy/react-native-twilio-video-webrtc#362]
Hi, I'l like to share an Android issue. I'm trying to implement this library the IOS side seems ok, but android feels weird.
IOS side can see video from Android side. But Android side cannot see anything it just a transparent view (I can see prev screen) even if it just showing local video / camera.

### Steps to reproduce
1. Open screen that implement TwilioVideoLocalView.

### Expected behavior
Android can see Local and Remote Video.

### Actual behavior
Android cannot see Local & Remote Video. Video blank / transparent.

### Environment
"react-native": "0.61.2",
Android: R

### react-native-twilio-video-webrtc
"version": "1.0.2-1", (master)

**Comment by osaro-imohe** [comment]
Have the same issue for iOS, have you figured something out?

**Comment by rekha-emids** [comment]
Have the same issue in IOS

**Comment by nichthinkof30** [comment]
hello @eduedix and @slycoder is there anything we can do about it?

**Comment by RZulfikri** [comment]
@osaro-imohe @rekha-emids which version did you use? is android working?

**Comment by slycoder** [comment]
A few questions:

* Does it show the local preview correctly?
* Could you share some of the logs (i.e. from logcat)?
* Is this happening with the example app?  If not do you have a snippet you could share?

**Comment by RZulfikri** [comment]
Hi @slycoder, 
* local preview not showing in android
* there is no error in logcat
* I haven't started the example yet, but I do follow the example.

After checking the code. I found out, probably the issue related to "createLocalVideo" function, why this function called in "connectToRoomWrapper"? 
https://github.com/blackuy/react-native-twilio-video-webrtc/blob/ab92a8b06301f18fea1a29f49f544ccc62f62c1b/android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java#L385

I think in my cases "TwilioVideoLocalView" called before connect function called. So there is no CameraCapturer & LocalVideo instance. 

Then, I try to modify few code to called "createLocalVideo" onCreate. And the video show, but I have tried to start called yet, I'll update you again.

Oh ya, Thanks for your response.

**Comment by slycoder** [comment]
Currently createLocalVideo is called once you connect to the room; are you trying to show the local preview before connecting to the room?  There is another ticket which brought up that issue.

**Comment by RZulfikri** [comment]
is there any reason why we need to call that function on connect? I also check the twilio android native example it also prepare the CameraCapturer & LocalVideo onCreate

**Comment by RZulfikri** [comment]
Ah, finally I found the issue. I'm not sure, but the issue because I'm using this library https://github.com/software-mansion/react-native-screens, so weird.

if I use that library (react-native-screen) the screen with Twilio implementation only shown if registered screen as First / Initial Screen, else Camera not rendered.

Thanks.

**Comment by owenadley** [comment]
@RZulfikri Why would react-native-screens introduce this issue? Having the same problem but am not using that package.
