### ISSUE TITLE
linked command failed with existing code 1

### ISSUE THREAD

**Issue by rekha-emids** [blackuy/react-native-twilio-video-webrtc#364]
release build giving below Error. But debug is working fine.

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TVICameraCapturer", referenced from:
      objc-class-ref in libreact-native-twilio-video-webrtc.a(RCTTWVideoModule.o)
  "_OBJC_CLASS_$_TVIScreenCapturer", referenced from:
      objc-class-ref in libreact-native-twilio-video-webrtc.a(RCTTWVideoModule.o)
  "_OBJC_CLASS_$_TVIVideoConstraints", referenced from:
      objc-class-ref in libreact-native-twilio-video-webrtc.a(RCTTWVideoModule.o)
  "_OBJC_CLASS_$_TwilioVideo", referenced from:
      objc-class-ref in libreact-native-twilio-video-webrtc.a(RCTTWVideoModule.o)
  "_TVIAspectRatio16x9", referenced from:
      ___36-[RCTTWVideoModule videoConstraints]_block_invoke in libreact-native-twilio-video-webrtc.a(RCTTWVideoModule.o)
  "_TVIVideoConstraintsFrameRateNone", referenced from:
      ___36-[RCTTWVideoModule videoConstraints]_block_invoke in libreact-native-twilio-video-webrtc.a(RCTTWVideoModule.o)
  "_TVIVideoConstraintsSize1280x720", referenced from:
      ___36-[RCTTWVideoModule videoConstraints]_block_invoke in libreact-native-twilio-video-webrtc.a(RCTTWVideoModule.o)
  "_TVIVideoConstraintsSize960x540", referenced from:
      ___36-[RCTTWVideoModule videoConstraints]_block_invoke in libreact-native-twilio-video-webrtc.a(RCTTWVideoModule.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Environment
- **Node.js version**: 10.13.0
- **React Native version**: 0.61.0
- **React Native platform + platform version**: iOS 11.0

**Comment by slycoder** [comment]
Hi, can you provide a little more info?  Is this happening with the Example app?
