### ISSUE TITLE
A few questions regarding the package

### ISSUE THREAD

**Issue by marqroldan** [blackuy/react-native-twilio-video-webrtc#368]
Hi, I have a few questions regarding this package.
1. Is this officially backed by Twilio?
   - I think the answer here is no, but this is just my assumption as it's not in their docs
2. Are there future plans regarding "unification of code" between the Android and iOS Platform?
   - Currently I find the code a lot different from one another.
3. Are there plans to support the current react-native versions?
   - Please let me know if there's a team working on this, as I would like to contribute too to speed up things

**Comment by slycoder** [comment]
Hi and sorry for the delay in replying.

1.) It is not officially backed by Twilio.  This is a separate volunteer project.
2.) Hopefully the interfaces between Android and iOS are reasonably close now, but there are unfortunately a few places where they diverge.  If you'd like to help (or even just point out the most annoying departures for you), let me know.
3.) I haven't actively worked on it, but there's a branch here which supports RN 0.60+ (release/v2.0).  You can work on that branch to add more modern support.  We'll figure out a release plan at some point!
