### ISSUE TITLE
Issue facing for collaboration video mood

### ISSUE THREAD

**Issue by moiz-i-am** [blackuy/react-native-twilio-video-webrtc#369]
### Steps to reproduce
1. No collaboration mode in video conferencing.

### Expected behaviour
There should be a  video collaboration mood in this react-native-twilio-video-webrtc  like main twilio api.

### Actual behaviour
-There is no video collaboration mood in this react-native-twilio-video-webrtc?
-In actual twilio api this is a collaboration mood.

Environment
- Node.js version: 12.18.3
- React Native version: 0.63
- React Native platform + platform version: iOS 11.0

**Comment by slycoder** [comment]
Hi, can you describe in a little more detail what features you'd need for a "collaboration mode"?

**Comment by moiz-i-am** [comment]
@slycoder i need a feature for collaboration mood which allows one person to present (i.e lecture) and multiple users can join the room. But with the User Interface the person which is presenting the lecture his screen must be bigger than others in every device.

There is a feature of collaboration mood in main twilio api but its not here.

**Comment by slycoder** [comment]
You can control the placement/sizing of the local and participant views using standard RN styling, so as long as you know who is presenting it shouldn't be hard to get the UI you want.  Is there some feature in the library (or lack thereof) which is preventing you from doing so?
