### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by davisuga** [blackuy/react-native-twilio-video-webrtc#370]
### Steps to reproduce
1. Clone the repo
2. cd Example
3. react-native run-android

### Expected behaviour
The Example should work

### Actual behaviour
Execution failed for task ':app:mergeDebugResources'.
> This project uses AndroidX dependencies, but the 'android.useAndroidX' property is not enabled. Set this property to true in the gradle.properties file and retry.
  The following AndroidX dependencies are detected: androidx.annotation:annotation:1.1.0

### Environment
- **Node 12.18**:
- **0.59.9**:
- **Linux Ubuntu 20.0.4**: Android 10

### react-native-twilio-video-webrtc
"master"

**Comment by slycoder** [comment]
If you add 

```
android.useAndroidX=true
```

to `Example/android/gradle.properties` does it work?  If so I'll get that change in.

**Comment by davisuga** [comment]
It worked! Thanks!
