### ISSUE TITLE
Video is freezing on other participant if more than 10 to 15 minutes of call on IOS

### ISSUE THREAD

**Issue by patrickleemsantos** [blackuy/react-native-twilio-video-webrtc#371]
### Steps to reproduce
1. Initiate a video call on both participant.
2. Continue calling around 10 to 15 minutes or more.
3. Wait until 1 of the participant freezes.

### Expected behaviour
Video will run smoothly without freezing.

### Actual behaviour
The video/camera of 1 of the participant freezes, but the audio/voice was still there. (Note: our internet connection is ok around 25-50mbps). I notice also before it freezes that the quality of the video was starting to become low and then 1 of the participant will already stop. (IOS only)

### Environment
- **Node.js version**: 12.18.2
- **React Native version**: 0.62.2
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: 1.0.2-1

**Comment by slycoder** [comment]
Are both parties using iOS?

**Comment by slycoder** [comment]
So I don't have any good ideas off the top of my head.  One thing we might try is upgrading to a newer version of the library (you can just edit the Podfile accordingly).  Otherwise, you might need to spin up a thread on the underlying twilio library itself to see if they can help.

**Comment by patrickleemsantos** [comment]
> Are both parties using iOS?
Yes, we are both using IOS

**Comment by patrickleemsantos** [comment]
@slycoder Additional info, I noticed it happening on lower version of iPhone like iPhone 6 with IOS 12

**Comment by slycoder** [comment]
Did you get any feedback from the twilio folks yet?
