### ISSUE TITLE
uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [org.webrtc:google-webrtc:1.0.32006]

### ISSUE THREAD

**Issue by grodriguez1983** [blackuy/react-native-twilio-video-webrtc#372]
### Steps to reproduce
1. try to compile the app for android if your min sdk version its less than 21
### Expected behaviour
the app should compile

### Actual behaviour
```
 Task :app:processDebugManifest FAILED
/Users/****/****/******/my-app/android/app/src/debug/AndroidManifest.xml Error:
        uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [org.webrtc:google-webrtc:1.0.32006] /Users/gabo/.gradle/caches/transforms-1/files-1.1/jetified-google-webrtc-1.0.32006.aar/d1fdc6b2acfaae98594cda8f80f46a10/AndroidManifest.xml as the library might be using APIs not available in 16
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 21,
                or use tools:overrideLibrary="org.webrtc" to force usage (may lead to runtime failures)

```
### react-native-twilio-video-webrtc
**Version**: npm version or "master"

**Comment by grodriguez1983** [comment]
I found the solution, the library https://bintray.com/google/webrtc/google-webrtc was updated Updated Aug 27, 2020 and now this one require minSdk version to at least 21, to fix it I've changed the file `node_modules/react-native-twilio-video-webrtc/android/build.gradle`  in the line 'org.webrtc:google-webrtc:1.0.+'  by the last version that accepts sdkmin 21 'org.webrtc:google-webrtc:1.0.30039'

**Comment by slycoder** [comment]
Cool, if you wanna submit a PR, I'd be happy to merge it in!

**Comment by Balasnest** [comment]
[image: Screenshot 2020-08-30 at 8.55.16 AM.png]
For quick fix, cmd + click_link -> change minSDKVersion from 21 to 19. It
should work!

**Comment by Balasnest** [comment]
![Image](https://user-images.githubusercontent.com/6050520/91650586-161e3700-ea9f-11ea-882d-3543391bb128.png)

For quick fix, cmd + click_link -> change minSDKVersion from 21 to 19. It
should work!

**Comment by jirawatp** [comment]
I just create PR for fix this : [https://github.com/blackuy/react-native-twilio-video-webrtc/pull/373](https://github.com/blackuy/react-native-twilio-video-webrtc/pull/373)
