### ISSUE TITLE
Support for iOS 14 with Twilio Video 3.7.0

### ISSUE THREAD

**Issue by ceaglest** [blackuy/react-native-twilio-video-webrtc#376]
### Steps to reproduce

Alice is using iOS 14 and Bob is on iOS 13.

Alice and Bob are on the same private network (broadly speaking, the same Wifi, VPN, or Cellular Access Point).

1. Alice connects to a Peer-to-Peer Room.
2. Bob connects to a Peer-to-Peer Room.
3. Wait for media to begin.

### Expected behaviour

Alice and Bob can establish a media connection. Alice is not prompted for local network permissions.

### Actual behaviour

1. Alice receives a prompt requesting local network permissions.
2. If Alice declines, Alice's Room fails with `TVIErrorMediaConnectionError`.

### Environment

- Any node and react-native version.
- iOS 14.0 beta7

### react-native-twilio-video-webrtc

"master"

The podfile currently matches patch versions 3.2.3+. Requiring Twilio Video 3.7.0 or newer will resolve this compatibility issue with iOS 14.

```
# Twilio Video uses semantic versioning, pinning to patch versions is not recommended.
s.dependency 'TwilioVideo', '~> 3.7'
```

- https://github.com/twilio/twilio-video-ios/issues/119

**Comment by slycoder** [comment]
Thanks for the clear report and identifying the solution.  The PR has been merged; I'll close this out. Feel free to re-open if I missed something.

**Comment by ceaglest** [comment]
Thank you! Everything looks good from my side.
