### ISSUE TITLE
TwilioVideoLocalView , TwilioVideo is not working on iOS after PR #347

### ISSUE THREAD

**Issue by RadiaTechs-Gaganesh** [blackuy/react-native-twilio-video-webrtc#381]
### Steps to reproduce

```
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  TextInput,
  View,
  Button,
  PermissionsAndroid,
  Platform,
  TouchableOpacity,
  Dimensions
} from 'react-native';

import {
  TwilioVideoLocalView,
  TwilioVideoParticipantView,
  TwilioVideo
} from 'react-native-twilio-video-webrtc'

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white'
  },
  callContainer: {
    flex: 1,
    position: "absolute",
    bottom: 0,
    top: 0,
    left: 0,
    right: 0
  },
  welcome: {
    fontSize: 30,
    textAlign: 'center',
    paddingTop: 40
  },
  input: {
    height: 50,
    borderWidth: 1,
    marginRight: 70,
    marginLeft: 70,
    marginTop: 50,
    textAlign: 'center',
    backgroundColor: 'white'
  },
  button: {
    marginTop: 100
  },
  localVideo: {
    flex: 1,
    width: 150,
    height: 250,
    position: "absolute",
    right: 10,
    bottom: 10
  },
  remoteGrid: {
    flex: 1,
    flexDirection: "row",
    flexWrap: 'wrap'
  },
  remoteVideo: {
    marginTop: 20,
    marginLeft: 10,
    marginRight: 10,
    width: 100,
    height: 120,
  },
  optionsContainer: {
    position: "absolute",
    left: 0,
    bottom: 0,
    right: 0,
    height: 100,
    backgroundColor: 'blue',
    flexDirection: "row",
    alignItems: "center"
  },
  optionButton: {
    width: 60,
    height: 60,
    marginLeft: 10,
    marginRight: 10,
    borderRadius: 100 / 2,
    backgroundColor: 'grey',
    justifyContent: 'center',
    alignItems: "center"
  }
});

export default class VideoConference extends Component {
  state = {
    isAudioEnabled: true,
    isVideoEnabled: true,
    status: 'disconnected',
    participants: new Map(),
    videoTracks: new Map(),
    token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImN0eSI6InR3aWxpby1mcGE7dj0xIn0.eyJqdGkiOiJTSzA1OGYxYWU3YTMxOGYzNjY0NjFmZTlkNTUzZTk0MTI5LTE2MDAwOTE4OTkiLCJncmFudHMiOnsiaWRlbnRpdHkiOiI1ZjQ4YTI4MWJkZThiZDU4YjcyYzU3YmIjVGFudS5EaG9vdCIsInZpZGVvIjp7InJvb20iOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKcFpDSTZJalZtTkRoaE1qZ3hZbVJsT0dKa05UaGlOekpqTlRkaVlpSXNJbWxoZENJNk1UWXdNREE1TVRnMU5pd2laWGh3SWpveE5qQTFNamMxT0RVMmZRLldUUmd4OC1FY1cxVS1UaW1NR24tVHJFcU0wMjllaU5sYVJmWlRuck1RNEUifX0sImlhdCI6MTYwMDA5MTg5OSwiZXhwIjoxNjAwMDk1NDk5LCJpc3MiOiJTSzA1OGYxYWU3YTMxOGYzNjY0NjFmZTlkNTUzZTk0MTI5Iiwic3ViIjoiQUNiMGNhZDI1Nzk2NjQ5ZDJkZGFjMjE2MGZhOTQ5ODI0MiJ9.V4MRubMKcZ9Jt5pkgekYZs8V-SoY2mKXV4gAWaeQD-U'
  }

  _onConnectButtonPress = async () => {
    if (Platform.OS === 'android') {
      await this._requestAudioPermission()
      await this._requestCameraPermission()
    }
    this.refs.twilioVideo.connect({ accessToken: this.state.token })
    this.setState({status: 'connecting'})
  }

  _onEndButtonPress = () => {
    this.refs.twilioVideo.disconnect()
  }

  _onMuteButtonPress = () => {
    this.refs.twilioVideo.setLocalAudioEnabled(!this.state.isAudioEnabled)
      .then(isEnabled => this.setState({isAudioEnabled: isEnabled}))
  }

  _onFlipButtonPress = () => {
    this.refs.twilioVideo.flipCamera()
  }

  _onRoomDidConnect = () => {
    this.setState({status: 'connected'})
  }

  _onRoomDidDisconnect = ({error}) => {
    console.log("ERROR: ", error)

    this.setState({status: 'disconnected'})
  }

  _onRoomDidFailToConnect = (error) => {
    console.log("ERROR: ", error)

    this.setState({status: 'disconnected'})
  }

  _onParticipantAddedVideoTrack = ({participant, track}) => {
    console.log("onParticipantAddedVideoTrack: ", participant, track)

    this.setState({
      videoTracks: new Map([
        ...this.state.videoTracks,
        [track.trackSid, { participantSid: participant.sid, videoTrackSid: track.trackSid }]
      ]),
    });
  }

  _onParticipantRemovedVideoTrack = ({participant, track}) => {
    console.log("onParticipantRemovedVideoTrack: ", participant, track)

    const videoTracks = this.state.videoTracks
    videoTracks.delete(track.trackSid)

    this.setState({ videoTracks: new Map([ ...videoTracks ]) });
  }

  _requestAudioPermission =  () => {
    return PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.RECORD_AUDIO,
      {
        title: "Need permission to access microphone",
        message:
          "To run this demo we need permission to access your microphone",
        buttonNegative: "Cancel",
        buttonPositive: "OK"
      }
    );
  }

  _requestCameraPermission =  () => {
    return PermissionsAndroid.request(
     PermissionsAndroid.PERMISSIONS.CAMERA,
      {
        title: "Need permission to access camera",
        message:
          "To run this demo we need permission to access your camera",
        buttonNegative: "Cancel",
        buttonPositive: "OK"
      }
    );
  }

  render() {
    return (
      <View style={styles.container}>
        {
          this.state.status === 'disconnected' &&
          <View>
            <Text style={styles.welcome}>
              React Native Twilio Video
            </Text>
            <TextInput
              style={styles.input}
              autoCapitalize='none'
              value={this.state.token}
              onChangeText={(text) => this.setState({token: text})}>
            </TextInput>
            <Button
              title="Connect"
              style={styles.button}
              onPress={this._onConnectButtonPress}>
            </Button>
          </View>
        }

        {
          (this.state.status === 'connected' || this.state.status === 'connecting') &&
            <View style={styles.callContainer}>
            {
              this.state.status === 'connected' &&
              <View style={styles.remoteGrid}>
                {
                  Array.from(this.state.videoTracks, ([trackSid, trackIdentifier]) => {
                    return (
                      <TwilioVideoParticipantView
                        style={styles.remoteVideo}
                        key={trackSid}
                        trackIdentifier={trackIdentifier}
                      />
                    )
                  })
                }
              </View>
            }
          <View
              style={styles.optionsContainer}>
              <TouchableOpacity
                style={styles.optionButton}
                onPress={this._onEndButtonPress}>
                <Text style={{fontSize: 12}}>End</Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={styles.optionButton}
                onPress={this._onMuteButtonPress}>
                <Text style={{fontSize: 12}}>{ this.state.isAudioEnabled ? "Mute" : "Unmute" }</Text>
              </TouchableOpacity>
              <TouchableOpacity
                style={styles.optionButton}
                onPress={this._onFlipButtonPress}>
                <Text style={{fontSize: 12}}>Flip</Text>
              </TouchableOpacity>
              <TwilioVideoLocalView
                enabled={true}
                style={styles.localVideo}
              />
            </View>
          </View>
        }

        <TwilioVideo
          ref="twilioVideo"
          onRoomDidConnect={ this._onRoomDidConnect }
          onRoomDidDisconnect={ this._onRoomDidDisconnect }
          onRoomDidFailToConnect= { this._onRoomDidFailToConnect }
          onParticipantAddedVideoTrack={ this._onParticipantAddedVideoTrack }
          onParticipantRemovedVideoTrack= { this._onParticipantRemovedVideoTrack }
        />
      </View>
    );
  }
}
```

### Expected behaviour
TwilioVideoLocalView should be visible with camera screen. 

### Actual behaviour
It is showing background image of view.

### Environment
- **Node.js version**:
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: npm version or "master"

**Comment by lidia-saf** [comment]
I experience the same issue after updating to version 3.7.0 of Twilio Video for iOS according to this [helpdesk article](https://support.twilio.com/hc/en-us/articles/360053909533-Important-Changes-in-iOS-14-for-Twilio-Video-P2P-Rooms).

All is the same, platform version is iOS 11.0

**Comment by RadiaTechs-Gaganesh** [comment]
@lidia-saf , before updating to version 3.7.0 was it working fine on both platform (iOS & Android) ? .

**Comment by lidia-saf** [comment]
Sorry, cannot say about Android, but, yes, iOS was working

**Comment by lidia-saf** [comment]
It seems that the local video stopped working for me on this pull request: https://github.com/blackuy/react-native-twilio-video-webrtc/pull/347. When I install library with pull request 346 all works well, on 347 it stops working.

**Comment by RadiaTechs-Gaganesh** [comment]
This weird problem is on android only, iOS is working fine. 
The problem is LocalVideoView is overlapping by it's underneath screen in stack. When there are no screens in stack , only the TwilioExampleScreen is mounted on stack then it works fine but if there are any screen below this TwilioExampleScreen then it's LocalVideoView is overlapped by it's underneath screen ui.

**Comment by slycoder** [comment]
So the ordering of the views is kind of hardcoded on Android.  If you pull down the branch in #375 , that adds a prop called applyZOrder.  Set that to true to make that view appear on top of other twilio views (assuming the others are set to false).

**Comment by RadiaTechs-Gaganesh** [comment]
I have run below command to update .

npm install https://github.com/blackuy/react-native-twilio-video-webrtc#pull/375/head --save

Apart from this i update my code with     applyZOrder={true} as below.

import React, { Component } from "react";
import {
  StyleSheet,
  Text,
  TextInput,
  View,
  Button,
  TouchableOpacity,
  Platform, PermissionsAndroid
} from "react-native";

import {
  TwilioVideoLocalView,
  TwilioVideoParticipantView,
  TwilioVideo
} from "react-native-twilio-video-webrtc";

export default class VideoConference extends Component {
    constructor(props){
      super(props)
	  this.state = {
		isAudioEnabled: true,
		isVideoEnabled: true,
		status: "disconnected",
		participants: new Map(),
		videoTracks: new Map(),
		roomName: "Room 1", //added new
    // token: props.route.params.token,
    token:"fsdfdsdsfsfj"
	}
    }
    _requestAudioPermission = () => {
      return PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.RECORD_AUDIO,
        {
          title: "Need permission to access microphone",
          message:
            "To do this call we need permission to access your microphone",
          buttonNegative: "Cancel",
          buttonPositive: "OK"
        }
      );
    }
  
    _requestCameraPermission = () => {
      return PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.CAMERA,
        {
          title: "Need permission to access camera",
          message:
            "Camera permission is needed so that you can talk to your vet",
          buttonPositive: "OK"
        }
      );
    }
  
    _requestExternalStoragePermission = () => {
      return PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE
      );
    }
    async componentDidMount() {
      if (Platform.OS === 'android') {
        await this._requestCameraPermission()
        await this._requestAudioPermission()
        await this._requestExternalStoragePermission()
      }
    }
    _onConnectButtonPress = () => {
      try {
        this.twilioRef.connect({
          roomName: this.state.roomName,
          accessToken: this.state.token
        });
      } catch (error) {
        console.log(error);
      }
  
      this.setState({ status: "connecting" });
    };
  
    _onEndButtonPress = () => {
      this.twilioRef.disconnect();
    };
  
    _onMuteButtonPress = () => {
      this.twilioRef
        .setLocalAudioEnabled(!this.state.isAudioEnabled)
        .then(isEnabled => this.setState({ isAudioEnabled: isEnabled }));
    };
  
    _onFlipButtonPress = () => {
      this.twilioRef.flipCamera();
    };
  
    _onRoomDidConnect = () => {
      this.setState({ status: "connected" });
    };
  
    _onRoomDidDisconnect = ({ roomName, error }) => {
      console.log("ERROR: ", error);
  
      this.setState({ status: "disconnected" });
    };
  
    _onRoomDidFailToConnect = error => {
      console.log("ERROR: ", error);
  
      this.setState({ status: "disconnected" });
    };
  
    _onParticipantAddedVideoTrack = ({ participant, track }) => {
      console.log("onParticipantAddedVideoTrack: ", participant, track);
  
      this.setState({
        videoTracks: new Map([
          ...this.state.videoTracks,
          [
            track.trackSid,
            { participantSid: participant.sid, videoTrackSid: track.trackSid }
          ]
        ])
      });
    };
  
    _onParticipantRemovedVideoTrack = ({ participant, track }) => {
      console.log("onParticipantRemovedVideoTrack: ", participant, track);
  
      const videoTracks = this.state.videoTracks;
      videoTracks.delete(track.trackSid);
  
      this.setState({ videoTracks: new Map([...videoTracks]) });
    };
  
    setTwilioRef = ref => {
      this.twilioRef = ref;
    };
    _camStarted=()=>{
      console.log("Camera started : ")
    }
    render() {
      return (
        <View style={styles.container}>
          {this.state.status === "disconnected" && (
            <View>
              <Text style={styles.welcome}>React Native Twilio Webrtc</Text>
              <TextInput
                style={styles.input}
                autoCapitalize="none"
                value={this.state.roomName}
                onChangeText={text => this.setState({ roomName: text })}
              ></TextInput>
              <TextInput
                style={styles.input}
                autoCapitalize="none"
                value={this.state.token}
                onChangeText={text => this.setState({ token: text })}
              ></TextInput>
              <Button
                title="Connect"
                style={styles.button}
                onPress={this._onConnectButtonPress}
              ></Button>
            </View>
          )}
  
          {this.state.status === "connected" ||
          this.state.status === "connecting" ? (
            <View style={styles.callContainer}>
              {this.state.status === "connected" && (
                <View style={styles.remoteGrid}>
                  {Array.from(
                    this.state.videoTracks,
                    ([trackSid, trackIdentifier]) => {
                      return (
                        <TwilioVideoParticipantView
                          style={styles.remoteVideo}
                          key={trackSid}
                          trackIdentifier={trackIdentifier}
                          applyZOrder={true}
                        />
                      );
                    }
                  )}
                </View>
              )}
              <View style={styles.optionsContainer}>
                <TouchableOpacity
                  style={styles.optionButton}
                  onPress={this._onEndButtonPress}
                >
                  <Text style={{ fontSize: 12 }}>End</Text>
                </TouchableOpacity>
                <TouchableOpacity
                  style={styles.optionButton}
                  onPress={this._onMuteButtonPress}
                >
                  <Text style={{ fontSize: 12 }}>
                    {this.state.isAudioEnabled ? "Mute" : "Unmute"}
                  </Text>
                </TouchableOpacity>
                <TouchableOpacity
                  style={styles.optionButton}
                  onPress={this._onFlipButtonPress}
                >
                  <Text style={{ fontSize: 12 }}>Flip</Text>
                </TouchableOpacity>
                <TwilioVideoLocalView applyZOrder={true} enabled={true} style={styles.localVideo}/>
                <View />
              </View>
            </View>
          ) : null}
  
          <TwilioVideo
            ref={this.setTwilioRef}
            onRoomDidConnect={this._onRoomDidConnect}
            onRoomDidDisconnect={this._onRoomDidDisconnect}
            onRoomDidFailToConnect={this._onRoomDidFailToConnect}
            onParticipantAddedVideoTrack={this._onParticipantAddedVideoTrack}
            onParticipantRemovedVideoTrack={this._onParticipantRemovedVideoTrack}
            onCameraDidStart={this._camStarted}
          />
        </View>
      );
    }
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    // backgroundColor: "white",
  },
  callContainer: {
    flex: 1,
    position: "absolute",
    bottom: 0,
    top: 0,
    left: 0,
    right: 0,
  },
  welcome: {
    fontSize: 30,
    textAlign: "center",
    paddingTop: 40
  },
  input: {
    height: 50,
    borderWidth: 1,
    marginRight: 70,
    marginLeft: 70,
    marginTop: 50,
    textAlign: "center",
    backgroundColor: "white"
  },
  button: {
    marginTop: 100
  },
  localVideo: {
    flex: 1,
    width: 125,
    height: 200,
    position: "absolute",
    right: 10,
    bottom: 300,
    borderRadius: 2,
    borderColor: '#4e4e4e',
    borderWidth:2,
  },
  remoteGrid: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap"
  },
  remoteVideo: {
    width: '100%',
    height: '100%'
  },
  optionsContainer: {
    position: "absolute",
    left: 0,
    bottom: 0,
    right: 0,
    height: 100,
    backgroundColor: "blue",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: 'center'
  },
  optionButton: {
    width: 60,
    height: 60,
    marginLeft: 10,
    marginRight: 10,
    borderRadius: 100 / 2,
    backgroundColor: "grey",
    justifyContent: "center",
    alignItems: "center"
  }
});


But still the issue is there.

**Comment by lidia-saf** [comment]
Really? Then I must be doing something wrong. Could you please take a quick look at my code, maybe, you something will strike you as off? I also have the twilio-chat on the same screen, but I removed parts referring to it.

```
const VideoScreen: React.FC<VideoScreenProps> = ({ navigation }) => {
  const { state } = useContext(ClientContext);
  const { client } = state;
  const username = client?.username;
  const [status, setStatus] = useState<ConnectionStates>("disconnected");
  const [videoTracks, setVideoTracks] = useState(new Map());
  const [isVideoEnabled, setIsVideoEnabled] = useState(true);
  const [isAudioEnabled, setIsAudioEnabled] = useState(true);
  const [getToken, token, isLoading, error] = useToken();
  const [getRoom, room] = useRoom();

  const twilioVideoRef = React.createRef<TwilioVideo>();

  useEffect(() => {
    getToken();
    getRoom();
    // need to get permission on android, iOS handles permissions automatically
    if (Platform.OS === "android") {
      const _checkPermissions = async () => {
        if (
          (await PermissionsAndroid.check(
            PermissionsAndroid.PERMISSIONS.CAMERA
          )) == false
        ) {
          requestCameraPermission();
        }
        if (
          (await PermissionsAndroid.check(
            PermissionsAndroid.PERMISSIONS.RECORD_AUDIO
          )) == false
        ) {
          requestRecordAudioPermission();
        }
        await _checkPermissions();
      };
    }
  }, []);

  useEffect(() => {
    if (token) {
      // need connect is async, need to wrap it to use in useEffect
      const _connect = async () => await connect();
      _connect();
      return disconnect;
    }
  }, [token]);

  useEffect(() => {
    if (error) {
      console.log("error, disconnecting..", error);
      disconnect();
    }
  }, [error]);

  const connect = async () => {
    twilioVideoRef.current?.connect({
      accessToken: token
    });
    setStatus("connecting");
  };

  const disconnect = () => {
    twilioVideoRef.current?.disconnect();
    navigation.navigate(Routes.HOME);
  };

  const onEndButtonPress = () => {
    disconnect();
  };

  const onRoomDidConnect = () => {
     setStatus("connected");
  };

  const onRoomDidDisconnect = ({ error }) => {
    if (error) {
      console.log("ERROR: ", error);
    }
    setStatus("disconnected");
    navigation.navigate(Routes.HOME);
  };

  const onRoomDidFailToConnect = (error) => {
    console.log("ERROR: ", error);
    setStatus("disconnected");
    navigation.navigate(Routes.HOME);
  };

  const onParticipantAddedVideoTrack = ({ participant, track }) => {
    console.log("onParticipantAddedVideoTrack: ", participant, track);

    setVideoTracks(
      new Map([
        ...videoTracks,
        [
          track.trackSid,
          { participantSid: participant.sid, videoTrackSid: track.trackSid }
        ]
      ])
    );
  };

  const onParticipantRemovedVideoTrack = ({ participant, track }) => {
    console.log("onParticipantRemovedVideoTrack: ", participant, track);

    const tempVideoTracks = videoTracks;
    tempVideoTracks.delete(track.trackSid);

    setVideoTracks(new Map([...tempVideoTracks]));
    if (tempVideoTracks.size === 0) {
      disconnect();
    }
  };

  const onVolumeMuteButtonPress = () => {
    twilioVideoRef.current
      .setLocalAudioEnabled(!isAudioEnabled)
      .then(() => setIsAudioEnabled(!isAudioEnabled));
  };

  const onVideoMuteButtonPress = () => {
    twilioVideoRef.current
      .setLocalVideoEnabled(!isVideoEnabled)
      .then(() => setIsVideoEnabled(!isVideoEnabled));
  };

  return (
    <KeyboardAvoidingView
      style={styles.container}
      contentContainerStyle={styles.container}
      behavior="position"
      keyboardVerticalOffset={80}
    >
      <TouchableWithoutFeedback onPress={Keyboard.dismiss}>
        <View style={styles.container}>
          {(status === "disconnected" || isLoading) && (
            <ActivityIndicator
              size="large"
              color={Colors.orange}
              style={styles.loader}
            />
          )}

          {status === "connected" && (
            <View style={styles.remoteVideoContainer}>
              {Array.from(videoTracks, ([trackSid, trackIdentifier]) => {
                return (
                  <TwilioVideoParticipantView
                    style={
                      styles.remoteVideo
                    }
                    key={trackSid}
                    trackIdentifier={trackIdentifier}
                  />
                );
              })}
            </View>
          )}
          <View
            style={
              styles.bottomContainer
            }
          >
            <View style={styles.toolbar}>
              <TouchableOpacity
                style={styles.button}
                onPress={onEndButtonPress}
              >
                <MaterialCommunityIcons
                  name="phone-hangup"
                  color={Colors.white}
                  size={24}
                />
              </TouchableOpacity>
              <TouchableOpacity
                style={styles.button}
                onPress={onVolumeMuteButtonPress}
              >
                <MaterialCommunityIcons
                  name={isAudioEnabled ? "volume-mute" : "volume-plus"}
                  color={isAudioEnabled ? Colors.white : Colors.red700}
                  size={24}
                />
              </TouchableOpacity>
              <TouchableOpacity
                style={styles.button}
                onPress={onVideoMuteButtonPress}
              >
                <MaterialCommunityIcons
                  name={isVideoEnabled ? "video-off" : "video"}
                  color={isVideoEnabled ? Colors.white : Colors.red700}
                  size={24}
                />
              </TouchableOpacity>
            </View>
          </View>
          <TwilioVideoLocalView
            enabled={true}
            style={styles.localVideo}
          />
          <TwilioVideo
            ref={twilioVideoRef}
            onRoomDidConnect={onRoomDidConnect}
            onRoomDidDisconnect={onRoomDidDisconnect}
            onRoomDidFailToConnect={onRoomDidFailToConnect}
            onParticipantAddedVideoTrack={onParticipantAddedVideoTrack}
            onParticipantRemovedVideoTrack={onParticipantRemovedVideoTrack}
          />
        </View>
      </TouchableWithoutFeedback>
    </KeyboardAvoidingView>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  loader: {
    ...Spacing.mt24,
    ...Spacing.mxAuto
  },
  remoteVideoContainer: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap"
  },
  remoteVideo: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0
  },
  localVideo: {
    position: "absolute",
    bottom: 120,
    left: 20,
    width: 88,
    height: 140,
    borderRadius: 20,
    overflow: "hidden"
  },
  bottomContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 280
    //transform: [{ translateY: 180 }]
  },
  toolbar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 100,
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "#00000099"
  },
  button: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: "space-around",
    alignItems: "center",
    backgroundColor: "#FFFFFF33"
  },
  icon: {
    color: Colors.white
  },
  _remoteVideo: {
    marginTop: 20,
    marginLeft: 10,
    marginRight: 10,
    width: 100,
    height: 120
  }
});
```

iOS minimum deployment target: 11;
react-native-video-webrtc version: commit #377

**Comment by RadiaTechs-Gaganesh** [comment]
@lidia-saf  , Please  implement this check for status {(status == "connected" || status == "connecting") }  instead of  {(status == "connected"}. It might be that your room is not connected that's why the view is not displaying.

**Comment by RadiaTechs-Gaganesh** [comment]
Guys, Finally i have concluded that this lib works only stand alone app. If there are any screens ui in stack beneath it the local video camera view will not work until you remove all screens from stack before going to twilio Video view screen.

**Comment by innergap** [comment]
Any updates on this? TwilioVideoLocalView is not working for me on the latest TwilioVideo, react-native-twilio-video-webrtc and iOS 14.0

**Comment by carlmagumpara** [comment]
same here TwilioVideoLocalView not working in ios, 

`  - react-native-twilio-video-webrtc (1.0.2-1):
    - React
    - TwilioVideo (~> 3.7)`

**Comment by labarilem** [comment]
Same issue on iOS.

Versions:

```
- react-native-twilio-video-webrtc (1.0.2-1):
    - React	    
    - TwilioVideo (~> 3.7)

- TwilioVideo (3.7.0)
```

**Comment by labarilem** [comment]
Just found a workaround. Downgrade the `react-native-twilio-video-webrtc` package:

1. `yarn add blackuy/react-native-twilio-video-webrtc#pull/346/head`
2. `cd ios && pod install`

**Comment by slycoder** [comment]
Thanks everyone, I'll rename this so it's clear this is the iOS issue related to #347.  I'll try to get a fix out and post it here.

**Comment by slycoder** [comment]
Hi, if anyone was experiencing this issue on master, would they mind being a guinea pig and trying #403 to see if it fixes the problem?

**Comment by kangaroo5383** [comment]
@slycoder nice timing on this,  just tried the PR, works, please merge!

**Comment by slycoder** [comment]
Thank you for the feedback, will merge!
