### ISSUE TITLE
how can i use network quality api with this?

### ISSUE THREAD

**Issue by carlmagumpara** [blackuy/react-native-twilio-video-webrtc#383]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Environment
- **Node.js version**:
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: npm version or "master"

**Comment by slycoder** [comment]
There are unfortunately currently no bindings between this library and the underlying twilio library.  I don't have time to add this but if you want to do so, a PR would be welcome!

**Comment by blindgaenger** [comment]
Looks like there is a PR now which may be what you're looking for: https://github.com/blackuy/react-native-twilio-video-webrtc/pull/406
