### ISSUE TITLE
Task :react-native-twilio-video-webrtc:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by cheunjm** [blackuy/react-native-twilio-video-webrtc#389]
### Steps to reproduce
1. Follow steps outlined in README
2. react-native run-android from the project root

### Expected behaviour
Tell us what should happen

Expect compile to run successfully

### Actual behaviour
Tell us what happens instead

Compiling fails for android with errors such as:
1. react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/TwilioRemotePreviewManager.java:10: error: package android.support.annotation does not exist

2. 
node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/RNVideoViewGroup.java:13: error: package android.support.annotation does not exist

3. node_modules/react-native-twilio-video-webrtc/android/src/main/java/com/twiliorn/library/RNVideoViewGroup.java:39: error: cannot find symbol

Works fine on iOS

### Environment
- **Node.js version**: 12.4
- **React Native version**: 0.63.3

These are my settings for android:

- build.gradle
        buildToolsVersion = "29.0.2"
        minSdkVersion = 24
        compileSdkVersion = 29
        targetSdkVersion = 29
    classpath("com.android.tools.build:gradle:3.5.3")

- gradle.properties
android.useAndroidX=true
android.enableJetifier=true

- gradle-wrapper.properties
distributionUrl=https\://services.gradle.org/distributions/gradle-6.2-all.zip

**Comment by slycoder** [comment]
For newer versions of RN that use androidX you'll need to either:

* Pull from the release/v2.0 branch here: https://github.com/blackuy/react-native-twilio-video-webrtc/tree/release/v2.0
* Run jettifier

**Comment by cheunjm** [comment]
@slycoder So just figured out why it wasn't working. I have a monorepo structure using yarn workspaces and lerna, and the project looks like this:

Root
--packages
|    |_____mobile
|    |_____web 
---node_modules

 and because all packages including the react-native-twilio-video-webrtc are hoisted at the root level, Jetifier didn't forward any files to jetify. Thanks!
