### ISSUE TITLE
Question: Twilio Video WebRTC Go, is it possible? 

### ISSUE THREAD

**Issue by rcroots** [blackuy/react-native-twilio-video-webrtc#390]
Hello, I have a question: is it possible to use weRTC Go with the currently react-native-twilio-video-webrtc architecture? With the recent Twilio free feature?

**Comment by slycoder** [comment]
I have not tried it so take it with a grain of salt but I believe it is possible; webrtc go is entirely a function of room creation (which this library does not manage).

**Comment by a7urag** [comment]
Yes, its working
