### ISSUE TITLE
Not able to see my local video on ios

### ISSUE THREAD

**Issue by urjasheth** [blackuy/react-native-twilio-video-webrtc#392]
### Steps to reproduce
1.Receive the call
2.try to enable the remote video

### Expected behaviour
When enable the remote video you can able to see your local video while press enable video track button

### Actual behaviour
You have to press twice to see yourself.

### Environment
- **Node.js version**:12.14.1
- **React Native version**:0.60.5
- **React Native platform + platform version**: iOS 11.0

Please check video attached:
[videocambutton.mp4.zip](https://github.com/blackuy/react-native-twilio-video-webrtc/files/5354882/videocambutton.mp4.zip)

### react-native-twilio-video-webrtc
**Version**: "master"

**Comment by slycoder** [comment]
Could you pull the branch in #403  and see if that addresses the issue?

**Comment by urjasheth** [comment]
After pull I am not able to see local video view.(not even after multiple time I click on video button).

**Comment by slycoder** [comment]
So it looks like in your video that the view for the local video isn't even being rendered until multiple presses have occurred (the initialization issue addressed in the PR would've shown a black screen for the local preview).  This to me indicates there may be an issue with the way you are updating react state in your application.  Do you have any code you could share?

**Comment by devWaleed** [comment]
@slycoder here's what i did...I put localVideoView without any conditions so it renders all the time...now when i start app and make a call, works fine, i disconnect call, goes back to previous screen, then call again and localVideoView is gone, its not showing...if I kill the app and start again and make call its there for first time only

**Comment by slycoder** [comment]
Can you see if #435 helps at all?

**Comment by slycoder** [comment]
I'm assuming that this was solved with the aforementioned PR.
