### ISSUE TITLE
Is there a way to check the tracks of remote participant?

### ISSUE THREAD

**Issue by gabrielgc** [blackuy/react-native-twilio-video-webrtc#393]
### Steps to reproduce
1. In a room, the remote participant is connected and with the microphone disabled
2. When the local user connects, I want to check if the remote participant has the audio enabled/disabled

### Expected behaviour
Connect to a room and be able to check if the remote participant has their audio enabled/disabled

### Actual behaviour
I can track the remote participant changes once the local user is connected and the remote user toggle their audio

**Comment by slycoder** [comment]
There are callbacks for onParticipantAdded/RemovedAudioTrack.  There are also callbacks for onParticipantEnabled/DisabledAudioTrack.  Do those suffice?

**Comment by gabrielgc** [comment]
Yes, `onRemoteParticipantAddedAudioTrack `did the trick to get the current settings right after the local participant joined the room.
It's just confusing because when the remote participant toggles their audio the onRemoteParticipantRemovedAudioTrack isn't getting triggered, what's triggered is `onParticipantEnabled/DisabledAudioTrack`.

Thanks
