### ISSUE TITLE
Camera indicator (green dot) after disconnect()

### ISSUE THREAD

**Issue by sshvaiko** [blackuy/react-native-twilio-video-webrtc#396]
Hello, I was wondering if someone has a problem with iOS 14 when the green dot appears even after the video ended by using the `disconnect()` method?

**Comment by Balasnest** [comment]
Yes. Its happening even for audio. Any workaround for this?

**Comment by sshvaiko** [comment]
@Balasnest I did not.

**Comment by Balasnest** [comment]
Mine is 3.2.3 did you try with `TwilioVideo - 3.7.1` latest?

**Comment by sshvaiko** [comment]
I have 3.2.5, will try to update

**Comment by Balasnest** [comment]
It's still happening with `3.7.1` Not sure exactly what would be the issue.

**Comment by paynerc** [comment]
@sshvaiko @Balasnest,

The green dot is active anytime the camera is still capturing video, regardless if the room is connected or not. Be sure to call the `stopCapture` method of the `TVICameraSource` as well when you are no longer capturing video.

Ryan

**Comment by Balasnest** [comment]
@paynerc Thanks mate! It worked perfectly.

@sshvaiko Replace this disconnect method in native. Will raise PR for this soon.
```
RCT_EXPORT_METHOD(disconnect) {
  // We are done with camera
  if (self.camera) {
      [self.camera stopCapture];
      self.camera = nil;
  }
  [self.room disconnect];
}
```

**Comment by sshvaiko** [comment]
@Balasnest @paynerc  thanks guys!

**Comment by Balasnest** [comment]
PR: #399
