### ISSUE TITLE
Ability to change audio mode on Android

### ISSUE THREAD

**Issue by reinhardholl** [blackuy/react-native-twilio-video-webrtc#397]
Is there a way to set the Audio mode on Android? Currently the default behaviour is to go into `Call` mode.

Our app has other sounds that are required to play as well and combining the calling SDK forces all audio through the earpiece. 

Thanks!

**Comment by slycoder** [comment]
Hi, @reinhardholl .  Unfortunately there's no out of the box way to do this with the library currently.  As you've identified with the other PR, you'd have to muck around with the java implementation to make that configurable.  If you do get something working, I'd love to incorporate those changes via a PR into the master.

**Comment by reinhardholl** [comment]
Cool thanks @slycoder
