### ISSUE TITLE
Undefined values in onParticipantAddedVideoTrack callback

### ISSUE THREAD

**Issue by aauffray** [blackuy/react-native-twilio-video-webrtc#40]
### Steps to reproduce
1. Install the module on Android
2. Run it and connect 2 users to a room

### Expected behaviour
Should run smoothly. Actually it doesn't impair he Twilio connection since I can Esc this error and see it works well, but having undefined values here is not so good

### Actual behaviour
Logs :
    08-14 12:41:29.689 10957 10988 I ReactNativeJS: 'onParticipantAddedVideoTrack: ', undefined, undefined
    08-14 12:41:29.689 10957 10988 E ReactNativeJS: undefined is not an object (evaluating 'track.trackId')
    08-14 12:41:29.751 10957 10988 W ReactNativeJS: Unable to symbolicate stack trace: The stack is null

<img width="343" alt="capture d ecran 2017-08-14 a 12 42 36" src="https://user-images.githubusercontent.com/12177107/29268717-548ebb2c-80ee-11e7-86e9-851efa09b347.png">

### Environment
- **Node.js version**: 8.1.4
- **React Native version**: 0.43.1
- **React Native platform + platform version**: Android 25

### react-native-twilio-video-webrtc
**Version**: master

**Comment by slycoder** [comment]
Can you share the relevant part of your onParticipantAddedVideoTrack?  And also what (if anything is getting passed to it, without destructuring)?

**Comment by ShadeIsaac** [comment]
It's exactly the same as in the example given on the Github page : 

_onParticipantAddedVideoTrack = ({participant, track}) => {
        console.log("onParticipantAddedVideoTrack: ", participant, track)
        this.setState({videoTracks: { ...this.state.videoTracks, [track.trackId]: { ...participant, ...track }}})
  }

and both participant and track are undefined

**Comment by bilby91** [comment]
@ShadeIsaac Could it be related to this one https://github.com/blackuy/react-native-twilio-video-webrtc/pull/41 ?

**Comment by ShadeIsaac** [comment]
I think so

**Comment by daominhsangvn** [comment]
@ShadeIsaac Try this
```
_onParticipantAddedVideoTrack = (event) => {
let {participant, track} = event;
if(Platform.OS === 'android'){
   participant = event.nativeEvent.participant;
   track= event.nativeEvent.track;
}
console.log("onParticipantAddedVideoTrack: ", participant, track)
this.setState({videoTracks: { ...this.state.videoTracks, [track.trackId]: { ...participant, ...track }}})
}
```

**Comment by bilby91** [comment]
I'm not sure if we can unify the js implementation. If so I think that should be the ultimate solution for this kind of problems.

**Comment by slycoder** [comment]
I thought I fixed this on master.  Let me check...

**Comment by ShadeIsaac** [comment]
We're good ! Thanks

**Comment by slycoder** [comment]
Just circling back; I'm a bit perplexed as to why this isn't working for you.
Did you wind up solving the problem without different js implementations on each platform?  

Just so I don't go crazy, can you double check that the version you have installed has this change in it: https://github.com/blackuy/react-native-twilio-video-webrtc/commit/a00c8b4871c702ada988068cd03660fa372e89f1#diff-f55da380eff80d4c5134c5ed77f29da2

**Comment by bilby91** [comment]
@ShadeIsaac Have you solved your issue ?

**Comment by aauffray** [comment]
Still here on the right version, I just disabled this part of code so I don't have the red screen anymore but I no longer manage the participants this way

**Comment by slycoder** [comment]
Sounds like this is kind of working?  I'll close out but feel free to re-open if you're still running into issues.

**Comment by sohamsuthar** [comment]
Facing issue :
