### ISSUE TITLE
Instruction about data track

### ISSUE THREAD

**Issue by Z5135099** [blackuy/react-native-twilio-video-webrtc#404]
Hi, 
Is data track supported now? I read in issue #268 that the support is added, but there is not any instruction. Is there any instruction about how to use data track? like a example?
Thank you

**Comment by slycoder** [comment]
Yeah, sorry there really isn't good documentation here.  I personally haven't used this feature but it looks like the data track is automatically created and you can just call `twilioVideo.sendString` to send a message to the other party.  You can also set `onDataTrackMessageReceived` to listen for received messages.

**Comment by Z5135099** [comment]
Thank you, they works.
