### ISSUE TITLE
Library not found for -lreact-native-twilio-video-webrtc

### ISSUE THREAD

**Issue by vicky123saini** [blackuy/react-native-twilio-video-webrtc#410]
### Steps to reproduce
1. pod 'react-native-twilio-video-webrtc', path: '../node_modules/react-native-twilio-video-webrtc'
2. build ios for ARMV7 devoice 

### Expected behaviour
Twilio video webrtc is working fine in android also it is working fine with particular device like 'iphone-8, iphone-11 iphone 11 pror' etc. but when i am building it for ARMV7 device it is showing an error that library not found
![WhatsApp Image 2020-10-31 at 5 24 49 PM](https://user-images.githubusercontent.com/2674996/97959978-7ea6ce80-1dd6-11eb-8a11-4cd8ecbaec0e.jpeg)

**Comment by slycoder** [comment]
Based on the twilio documentation here: https://www.twilio.com/docs/video/ios#xcode-and-ios-version-support it looks like the current version of twilio programmable video does not support armv7.

**Comment by vicky123saini** [comment]
I there any solution. can i remove armv7 device from build face or can i downgrade twilio framework?

**Comment by slycoder** [comment]
Just make sure to set your deployment target to ios11 or higher.

**Comment by vicky123saini** [comment]
I is working fine now... Thanks bro.
