### ISSUE TITLE
Android APK size doubled after integrating the library

### ISSUE THREAD

**Issue by anooshcnayak** [blackuy/react-native-twilio-video-webrtc#414]
### Steps to reproduce
1. I have created a Plain React Native App (Android) with this library integrated. The size of the apk was about ~ 70MB 
2. I have an existing App (Android), Apk size is about ~ 30 MB. Adding this library, size increased to ~ 70 MB. 

### Expected behaviour
Minimal size increase in the APK

### Actual behaviour
Size doubles to 70 MB

### Environment
- **Node.js version**: v13.5.0
- **React Native version**: 0.61.5
- **React Native platform + platform version**: Android 9 (28)

### react-native-twilio-video-webrtc
**Version**: "master"

**Comment by slycoder** [comment]
How are you bundling the apk?  If you're targeting all of the ABIs then this is within the expected range.  Here's the documentation on apk sizes:

https://www.twilio.com/docs/video/changelog-twilio-video-android

**Comment by anooshcnayak** [comment]
Thanks a lot. Im making a universal bundle. Twilio Universal bundle (debug apk android) takes about 35 MB.
