### ISSUE TITLE
libRNTwilioVideoWebRTC.a file not found

### ISSUE THREAD

**Issue by abhisheknfx** [blackuy/react-native-twilio-video-webrtc#415]
1 I am trying to add manual via cocoapod and linking, but could not found libRNTwilioVideoWebRTC.a file in as given location in doc

**Comment by slycoder** [comment]
What do you see? Do you see the following?

<img width="453" alt="截屏2020-11-22 21 41 35" src="https://user-images.githubusercontent.com/524989/99933188-24cb6180-2d0f-11eb-8297-5f783a415f46.png">
<img width="421" alt="截屏2020-11-22 21 41 58" src="https://user-images.githubusercontent.com/524989/99933190-26952500-2d0f-11eb-9fde-566c89f50cd4.png">
