### ISSUE TITLE
AAPT: error: resource attr/overlaySurface not found

### ISSUE THREAD

**Issue by Onibenjo** [blackuy/react-native-twilio-video-webrtc#417]
### Steps to reproduce
1. gradlew assembleRelease

### Expected behaviour
Buils successful

### Actual behaviour
AAPT: error: resource attr/overlaySurface (aka com.twiliorn.library:attr/overlaySurface) not found

### Environment
- **Node.js version**:12
- **React Native version**:0.63.3
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: v2 release branch

**Comment by slycoder** [comment]
From this it looks like we need to upgrade the android dependency: https://github.com/twilio/video-quickstart-android/issues/479

**Comment by slycoder** [comment]
Can you see if #419 fixes it for you?

**Comment by mathieupetrini** [comment]
Add implementation in android/app/build.gradle fixed for me

Before 

```
implementation project(':react-native-twilio-video-webrtc')
```

After

```
implementation "com.twilio:video-android:5.10.1"
implementation project(':react-native-twilio-video-webrtc')
```

**Comment by Onibenjo** [comment]
Fixed....
