### ISSUE TITLE
IOS Sending wrong packet of  video while converting call from Audio to Video 

### ISSUE THREAD

**Issue by mehdirajani5** [blackuy/react-native-twilio-video-webrtc#432]
When starting an Audio call it informs the participant that a video call is enabled. It was working fine in the previous release but when we update it to the latest one, it causes the error.

Whereas it works fine on Android devices. 

We are in a hurry we have to deploy the updates ASAP. 

Packets received when we make an Audio call.
![image (1)](https://user-images.githubusercontent.com/17649381/103441988-e44af600-4c73-11eb-9267-df1e62fdac7d.png)

**Comment by zuhairnaqi** [comment]
Also facing the same issue.

Two issues.
1. On audio call start, it trigger the **onParticipantEnabledVideoTrack**` with track.enable true on IOS and false on android.
2. When toggleCamera from audio to video call, it showing black screen instead of video.

**Comment by slycoder** [comment]
Hey, so I've created a PR #435 to try to address the issue.  Haven't given it much testing but if you could give it a whirl that would be great.

**Comment by mehdirajani5** [comment]
@slycoder 
Yeah, it works...
Do merge the PR ASAP. 
Thank you.

**Comment by slycoder** [comment]
Ok, the fix has been merged to master.
