### ISSUE TITLE
Audio echo and record itself

### ISSUE THREAD

**Issue by daominhsangvn** [blackuy/react-native-twilio-video-webrtc#44]
### Steps to reproduce
1. Install module in 2 devices
2. Both join to the same room

### Expected behaviour
The audio normal

### Actual behaviour
The audio recording itself and get bigger and bigger loud

### Environment
- **React Native version**: 0.44.0
- **React Native platform + platform version**: iOS 10.0

### react-native-twilio-video-webrtc
**Version**: 1.0.2

Here the video for the issue
https://www.youtube.com/watch?v=1rLcQmvLRYs

**Comment by bilby91** [comment]
Hi @daominhsangvn !

It only happens when the two devices are near ?

**Comment by daominhsangvn** [comment]
Yes bilby91, i think that cause the issue. i will close it.

**Comment by Andriiklymiuk** [comment]
Same issue on iPad 4 with latest dependency version. Have anyone found the solution?
