### ISSUE TITLE
Wrong events coming up & Participant view not showing on Android

### ISSUE THREAD

**Issue by devWaleed** [blackuy/react-native-twilio-video-webrtc#442]
### Actual Behavior
I have setlocalVideoEnabled to false on roomDidConnect and on other end I have Toasts to show if video track is removed or added. When I join a room which is max 2 users only i.e caller and reciever. 

On receiver end which is Android:
I first get video added taost, then I get removed then I get added toast again. Later on caller end (iOS) If I try to switch localVideoEnabled by a button click I do not get these events again on receiver end.

On caller end which is iOS:
I only get video add track, If I toggle setLocalVideoEnabled from Android end I do not get remove or add events again.

RemoteParticipantView:
On Android I am not able to see video relayed from iOS device but on iOS I am able to see video relayed from Android device. However both localViews show local video correctly.

### Expected behaviour
Should give me events for each toggle and show remote participant views with proper stream.

### Environment
- **React Native version**: 0.60.3
- **React Native platform + platform version**: iOS 13+ and Android 7+

### react-native-twilio-video-webrtc
**Version**: https://github.com/blackuy/react-native-twilio-video-webrtc/commit/22d303c7de1a36efdce2d2cda32337abcf171af7

**Comment by devWaleed** [comment]
Check the following logs please from ADB Logcat: [https://gist.github.com/devWaleed/3ff5bb457ce75acb0ce23e2e27aed3f0](https://gist.github.com/devWaleed/3ff5bb457ce75acb0ce23e2e27aed3f0)

**Comment by devWaleed** [comment]
Ok here are some updates...

The issue of blackscreen is only showing on Android devices and mostly for receiver. And we have a system in which we can see whole call recording after its completed. So in our dashboard we can verify that both cameras were working and that Twilio is showing both videos in the call recording but during the call only of the participant was able to see other's video. 

I first thought that it could be a zindex issue or something related to that but I also checked it by completely removing all other UI components and only putting the participant view with highest zindex, still complete black screen.

**Comment by slycoder** [comment]
I just came across this bug https://github.com/twilio/twilio-video-ios/issues/34 and wondering if that might reflect the issue you're seeing where participant events might not appear after the chat has started.  If you set the video enabled upon connection does the error ever show up?

**Comment by markui** [comment]
@devWaleed  Were you able to fix this issue? cc @slycoder

**Comment by devWaleed** [comment]
@markui I upgraded to the latest version I think that solved my issue.

**Comment by AireshBhat** [comment]
@devWaleed Did you install a particular PR/branch or the normal installation steps as given in the documentation?
