### ISSUE TITLE
is there any way to create Video in background without UI involvement? 

### ISSUE THREAD

**Issue by Mandy-1989** [blackuy/react-native-twilio-video-webrtc#443]
**What is the requirement?**

1. Mobile App is Killed/background and in lock mode.
2. Receive room Id from Server through Notification.
3. Connect to Twilio Video and share your video.
 
**Is there any possibility to achieve this?**

**Comment by Mandy-1989** [comment]
What is the requirement?

1. Mobile App is Killed/background and in lock mode.
2. Receive room Id from Server through Notification.
2. Connect to Twilio Video and share your video.


Is there any possibility to achieve this?

**Comment by slycoder** [comment]
If you look through the other issues, you'll see that other users have provided pointers for using callkit to do something along those lines.

**Comment by Mandy-1989** [comment]
Resolve this issue by using Invoking App from Background to foreground.

Thanks
