### ISSUE TITLE
Audio not coming and going at first time calling on device

### ISSUE THREAD

**Issue by zuhairnaqi** [blackuy/react-native-twilio-video-webrtc#458]
### Steps to reproduce
1. First time call on device

### Environment
- **Node.js version**:
- **React Native: 0.62.2**:
- **React Native platform + platform version**: Both

### react-native-twilio-video-webrtc
**    "react-native-twilio-video-webrtc": "https://github.com/blackuy/react-native-twilio-video-webrtc",

**Comment by slycoder** [comment]
Do you have a little more detail?  If this is just the first time on the device could it be a permissions issue?

**Comment by zuhairnaqi** [comment]
Yes the issue we're facing on first time after installing apk, afterwards it is working fine.
We're taking permission at very first so no permission issue.

**Comment by zuhairnaqi** [comment]
@slycoder sorry the issue is only on iOS

**Comment by slycoder** [comment]
Do you have a repro you could share?  Is this also happening with the example app?

**Comment by zuhairnaqi** [comment]
**Fixed Issue**

The issue was facing on iOS at receiving side only. Updated podFile flipperVersion fixed my issue.

React Native: 0.62.2
Updated podFile

**FROM**
`versions['Flipper'] ||= '~> 0.33.1'`

**TO**
`versions['Flipper'] ||= '~> 0.78.0'`
