### ISSUE TITLE
Wrong values emitted for `onCameraSwitched` on Android

### ISSUE THREAD

**Issue by marqroldan** [blackuy/react-native-twilio-video-webrtc#460]
### Steps to reproduce
1. Trigger `flipCamera()` on an Android device

### Expected behaviour
- `isBackCamera` should return `true` if back camera is being shown

### Actual behaviour
- requires triggering twice to flip the camera
- isBackCamera is _inverted_,  it shows false even though it's showing the back camera

### Environment
- **Node.js version**: 14.15.3
- **React Native version**: 0.63.3
- **React Native platform + platform version**: Android API 19 and Android API 29

### react-native-twilio-video-webrtc
**Version**: master

-------------

There was a similar issue here: https://github.com/twilio/video-quickstart-android/issues/548

I tried bumping version of tiwlio video from 5.10.1 to 5.10.2, cleaned the android folder and rebuilt again, but the issue is still there

So I'm planning to implement the `CameraCapturerCompat` found here: https://github.com/twilio/video-quickstart-android/blob/master/quickstart/src/main/java/com/twilio/video/quickstart/util/CameraCapturerCompat.java

But before doing that I would just like to know if anyone else is experiencing the same issue.

I've also added the iOS equivalent event on my fork, which I guess I'd bundle it with when I open a Pull Request

**Comment by slycoder** [comment]
You might wanna give #452 a try which upgrades to a new version of the android library and reworks the way camera selection works.

**Comment by marqroldan** [comment]
Hi, apologies if I was only able to check it now

Unfortunately it's still the same, but the camera switches properly (no more double triggering required)

I added logging under `isCurrentCameraSourceBackFacing()`
```
        Log.i("isCurrentCameraSourceBackFacing cameraid", cameraCapturer.getCameraId());
        Log.i("isCurrentCameraSourceBackFacing backFacingDevice", backFacingDevice);
```

I'm using Flipper (v0.69.0) to check the logs

1. Once connected to the room, I received these which I think is correct
```
15:32:35.410	isCurrentCameraSourceBackFacing cameraid		        Camera 3, Facing front, Orientation 270
15:32:35.410	isCurrentCameraSourceBackFacing backFacingDevice		Camera 2, Facing back, Orientation 90
```

2. Once I triggered the switching of camera
```
15:32:50.397	isCurrentCameraSourceBackFacing cameraid		        Camera 3, Facing front, Orientation 270
15:32:50.397	isCurrentCameraSourceBackFacing backFacingDevice		Camera 2, Facing back, Orientation 90
15:32:50.410	isCurrentCameraSourceBackFacing cameraid		        Camera 3, Facing front, Orientation 270
15:32:50.410	isCurrentCameraSourceBackFacing backFacingDevice		Camera 2, Facing back, Orientation 90
15:32:50.856	isCurrentCameraSourceBackFacing cameraid		        Camera 2, Facing back, Orientation 90
15:32:50.857	isCurrentCameraSourceBackFacing backFacingDevice		Camera 2, Facing back, Orientation 90
```

but the js event was sent at an earlier time
```
15:32:50.208	client_log		TwilioComponent TwilioEvent: onCameraSwitched __ {"isBackCamera":false}
```

------------

I'm on debug mode (react-native run-android) 
Android 11
SM-A715F

**Comment by marqroldan** [comment]
Ok I just moved the following code from `switchCamera()` to `createCameraCaputer()@onCameraSwitched()`

```
  WritableMap event = new WritableNativeMap();
  event.putBoolean("isBackCamera", isCurrentCameraSourceBackFacing());
  pushEvent(CustomTwilioVideoView.this, ON_CAMERA_SWITCHED, event);
```

And now it sends the correct values

**Comment by slycoder** [comment]
@marqroldan Makes sense!  I'll make that change and merge in #452
