### ISSUE TITLE
Question about conference layout

### ISSUE THREAD

**Issue by remigijusbalc** [blackuy/react-native-twilio-video-webrtc#462]
Hey, this is more like a question than issue. Was wondering how you handle conference video layouts? I mean how you measure dynamic width/height sizes of video boxes? I tried an approach of brute-forcing to find best box size but that's pretty expensive to do

**Comment by slycoder** [comment]
What do you mean by layouts?  Is the issue laying out the boxes for a variable number of participants?  Can you describe how you want them to be laid out?

**Comment by remigijusbalc** [comment]
Currently I get participants count, screen width and height, aspectRatio and measure the best possible layout for screen size, but that measuremt happens on every participant count change so I was wondering are there any better approach. There's no issue, I am just wondering how others manage video layouts with multiple participant streams
