### ISSUE TITLE
componentWillMount has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by Bertley** [blackuy/react-native-twilio-video-webrtc#467]
### Steps to reproduce
1. This issue is caused by using the `TwilioVideo` on iOS

### Expected behaviour
We would like to get rid of the Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details. 

### Actual behaviour
We currently have that warning and from debugging i can the issue is coming from `react-native-twilio-video-webrtc/src/TwilioVideo.ios.js`
```
  componentWillMount () {
    this._registerEvents()
    this._startLocalAudio()
  }
```
This lifecycle is going to be deprecated and the side effect codes should be moved to 
```
  componentDidMount () {
    this._registerEvents()
    this._startLocalAudio()
  }
```

### Environment
- **Node.js version**: 15.12.0
- **React Native version**: 0.63.1 
- **React Native platform + platform version**: iOS 14.0

**Version**: https://github.com/blackuy/react-native-twilio-video-webrtc#4d401bf

**Comment by slycoder** [comment]
Thanks and you're totally right.  This is a great starter task for anyone wanting to dip their toes into contributing in the repo!

**Comment by DanielMenke** [comment]
@slycoder 
Opened a PR for this issue.
https://github.com/blackuy/react-native-twilio-video-webrtc/pull/475
Can't link it though
