### ISSUE TITLE
Can't see my local video on iOS

### ISSUE THREAD

**Issue by aauffray** [blackuy/react-native-twilio-video-webrtc#48]
### Steps to reproduce
1. Install on iOS following the tutorial
2. Launch the app

### Expected behaviour
I should be able to see my local Video

### Actual behaviour
I don't see my local Video

### Environment
- **Node.js version**: 8.4.0
- **React Native version**: 0.42
- **React Native platform + platform version**: iOS 9.2

![img_0028](https://user-images.githubusercontent.com/12177107/29882497-78a48bec-8dad-11e7-9d0c-e7b3f8e0812d.PNG)

Works very fine on Android. Twilio Component is the same as in the tutorial in this Github's readme, I just changed the buttons styling
The big video is a remote one

**Comment by bilby91** [comment]
Have you granted the correct permissions to access the camera ?

**Comment by ShadeIsaac** [comment]
Yes, I know at first this was the issue but even after permissions were granted, local video doesn't always show up

**Comment by bilby91** [comment]
Hey @ShadeIsaac were you able to solve the issue ?

**Comment by aauffray** [comment]
Nope, still here

**Comment by cipriancaba** [comment]
I have the same problem on iOS, using TwilioVideo 1.3.7, iOS 11.0.3, RN 0.50.1

**Comment by cipriancaba** [comment]
@bilby91 Might this be related to the fact that the screen I am using is part of a react-navigation transition? How does the main TwilioVideo component know how to render inside the TwilioVideoLocalView ? I've split the definitions into 3 different files:
```
RootView (contains TwilioVideo)
---> ChildView1 (contains TwilioLocalView)
---> ChildView2,3,4 (contains TwilioVideoParticipantView which works as expected)
```

**Comment by cipriancaba** [comment]
Sorry for the spam, but I've managed to find a solution to only enabling the localView once the server is connected and it seems to be working fine..

**Comment by bilby91** [comment]
Hey. Good to know that you got it working!

**Comment by ibash** [comment]
I'm hitting this as well, @cipriancaba thanks for the solution!
@bilby91 I think this is a bug - so IMO the issue should remain open so it can get fixed.

I did some digging and I think the problem is that if you just set `enabled={true}` then   `[self.localVideoTrack addRenderer:view];` before the view is mounted.
I tested this by setting `enabled={this.state.isMounted}` and then calling `setState({isMounted: true})` in `componentDidMount` and it fixes it.

So - a fix would be to make sure `addLocalView` is only called after mounting.

**Comment by urjasheth** [comment]
@ibash , can you please share your code if possible? I am facing same issue. 
https://github.com/blackuy/react-native-twilio-video-webrtc/issues/392

**Comment by ibash** [comment]
@urjasheth sure thing, this code is from a while ago, so not sure if this is the bug you're facing, but essentially:

```
export default class RoundActiveScreen extends Component {
  constructor () {
    super()
    this._twilioVideo = new TwilioVideo()
    this.state = {hasMounted: false}
  }

  componentDidMount () {
    this._twilioVideo.start()
    this._twilioVideo.connect({
      roomName: core.state.room.sid,
      accessToken: core.state.room.accessToken
    })
    this._twilioVideo.setLocalVideoEnabled(true)
    this._twilioVideo.setLocalAudioEnabled(true)
    // NOTE(ibash) we set hasMounted and pass it to TwilioVideoLocalView.enabled
    // because there's a bug in the react native twilio video module.
    // ref: https://github.com/blackuy/react-native-twilio-video-webrtc/issues/48
    this.setState({hasMounted: true})
  }

// ...

  render () {

    return (
      <View style={styles.container}>
// ...
            <TwilioVideoLocalView
              enabled={this.state.hasMounted}
              style={styles.video}
            />
// ...
```
