### ISSUE TITLE
How to disconnect particular participant

### ISSUE THREAD

**Issue by mitjnextt** [blackuy/react-native-twilio-video-webrtc#483]
Hey there @blackuy, 

Is there any way we can remove particular participant from videoTracks. For example if we want to remove current participant we can write `twilioVideo.current.disconnect();` So if we have multiple participants how can we remove particular one.

I have implemented code where if any participant disconnects, all user get disconnected. But I want to implement if there are 2 users both should get disconnect when someone press disconnect. How when there are more than 2 users. Only particular participant should get disconnected.

Help would be appreciated. Thanks!

**Comment by slycoder** [comment]
I'm not 100% sure what you're asking, but if you want to respond to another participant leaving the room, you can use the `onRoomParticipantDidDisconnect` callback to listen for other participants leaving and then disconnect accordingly.
