### ISSUE TITLE
How to get total number of participants connected right now?

### ISSUE THREAD

**Issue by mitjnextt** [blackuy/react-native-twilio-video-webrtc#484]
Hey anyone please tell me...

 **How to get total number of participants connected right now?**
 
 I have done code in onRoomConnect but it is getting only when current user get connected and it is not proper.
 
 ```
const _onRoomDidConnect = (connect) => {
    console.log('connect ====> ', connect);
    setTotalParticipants(connect.participants.length)
    setStatus("connected");
  };
```

**Comment by slycoder** [comment]
As participants connect, `onRoomParticipantDidConnect` will be called.  Your app can, in this way, keep an internal count of the participants.
