### ISSUE TITLE
Screen capture doesn't reconnect when ipad is put to sleep

### ISSUE THREAD

**Issue by tyleralves** [blackuy/react-native-twilio-video-webrtc#49]
### Steps to reproduce
1. Connect to room
2. Click 'power/ sleep' button to put ipad to sleep
3. Wait for room connection to drop
4. Click 'power/ sleep' button to wake ipad and log in with passcode

### Expected behaviour
Room should re-establish connection, or some event should fire. (onRoomDidDisconnect?) 

### Actual behaviour
The app functions normally, but screen sharing seems to crash/ not reconnect.
Error in xCode:
> 2017-09-05 13:31:06.428 HappyOnboarding[3853:1297844] ERROR:TwilioVideo:[Signaling]:RESIP::TRANSPORT: Socket was closed (due to backgrounding or handover), deleting connection ...
> 2017-09-05 13:31:06.435 HappyOnboarding[3853:1297844] ERROR:TwilioVideo:[Signaling]:RESIP::TRANSPORT: Socket was closed, reopening ...
> 2017-09-05 13:31:06.445 HappyOnboarding[3853:1297873] ERROR:TwilioVideo:[Core]:I/O error connecting to sdkgw.us1.twilio.com:443, I/O error.
> 

Interestingly it sends the `onRoomDidDisconnect` event if you just background the app (go to home screen), wait for the connection to drop then bring up the app again. This behavior is perfect for me.

### Environment
- **Node.js version**: v8.4.0
- **React Native version**: 0.42.0
- **React Native platform + platform version**: iOS 9.3.4 on Ipad Mini 2

### react-native-twilio-video-webrtc
**Version**: "master"

**Comment by bilby91** [comment]
@tyleralves Can you put a breakpoint inside the native code and verify that the native TwilioVideo library is sending the event ?

**Comment by tyleralves** [comment]
@bilby91 I'd love to, but I'm not sure where to put a breakpoint. I'm much more experienced on the React-Native side than the Native side. Let me know how I can help.

**Comment by tyleralves** [comment]
I solved this for my particular case by watching AppState, almost exactly like the official docs.
https://facebook.github.io/react-native/docs/appstate.html

I still get the errors, but they don't seem to cause any negative issues with the app.

**Comment by bilby91** [comment]
@tyleralves Awesome that you could fix your problem!

I just found this in the TwilioVideo iOS changelog:

```
Known issues

- Participant disconnect event can take up to 120 seconds to occur. #99
- AVPlayer audio content does not mix properly with Room audio. #62
- TVIAudioSinks added to a TVILocalAudioTrack do not raise any callbacks. #104
```

**Comment by tyleralves** [comment]
@bilby91 I have no problem with the disconnect delay, it is more that it didn't reconnect nor send any event that indicated that a disconnect occurred. 
In any case it seems like more of an issue with the Twilio sdk and it is an ideal use case for AppState. Closing.

**Comment by bilby91** [comment]
@tyleralves Just to verify that I understood correctly. If you disconnect (for example turn off wifi) and you wait 120 seconds, you don't get the event ? If you put the device at sleep it's more tricky because the AppState will change obviously as you mentioned.

**Comment by tyleralves** [comment]
@bilby91 
Turning off wifi or backgrounding the app works as expected. 
The issue was only when I sleep the ipad (for more than 120 seconds), then re-enter the app. It doesn't reconnect, and it also doesn't provide any indication that the connection was (previously) dropped. However, using AppState really makes this a non-issue.
