### ISSUE TITLE
Is there a previous version that supports iOS 10?

### ISSUE THREAD

**Issue by tylerssn** [blackuy/react-native-twilio-video-webrtc#499]
### Steps to reproduce
1. Cannot reproduce. General question.

### Expected behaviour
If I install an older version of react-native-twilio-video-webrtc, I can support iOS 10.0

### Actual behaviour
I seem to be locked into iOS 11.0

### Environment
- **Node.js version**:
- **React Native version**:
- **React Native platform + platform version**: iOS 10.0

### react-native-twilio-video-webrtc
**Version**: master

**Comment by slycoder** [comment]
You'd need to pull an old version of the library which uses twilio video 2.x. (I believe that'd be commit 005926f)
