### ISSUE TITLE
beta5 and beta6 changes to TVIVideoCapturer

### ISSUE THREAD

**Issue by stueynet** [blackuy/react-native-twilio-video-webrtc#5]
Trying to upgrade to TwilioVideo beta5 or beta6. We get an exception

Noting in the Twilio Video docs that the changelog sates:

Added a new video frame class TVIVideoFrame, which replaces the TVII420Frame class for rendering and the TVIVideoFrame struct for capturing. TVIVideoFrame can be created using a CVImageBufferRef . TVIVideoRenderer and TVIVideoCaptureConsumer have been updated to use this class.

We are trying to figure out the issue ourselves but thought I would run it by you to see if you know a solution.

Also SO ticket here:
http://stackoverflow.com/questions/42075289/capturer-iphone-camera-not-provided-to-tvivideocapturer-for-twiliovideo-ios-sd

**Comment by bilby91** [comment]
It should be working for 1.0.1 or later now.
