### ISSUE TITLE
iOS TwilioVideo events are not firing

### ISSUE THREAD

**Issue by tylerssn** [blackuy/react-native-twilio-video-webrtc#503]
### Steps to reproduce
1. `yarn add git+https://github.com/blackuy/react-native-twilio-video-webrtc/#005926f77e13cf60672895a3d318ee52cefeead9` -- I was told this is the latest version that supports iOS 10
2. `pod install` (auto link)
3. `yarn start`
4. `react-native run-ios`

### Expected behavior
When a proper token is provided, `onRoomDidConnect` should fire on the `TwilioVideo` component.

**ExpectedAndroid**: `<TwilioVideo onRoomDidConnect={() => console.log('connected')} />` --> `"Connected"`
**Expected IOS**: `<TwilioVideo onRoomDidConnect={() => console.log('connected')} />` --> `"Connected`

### Actual behavior
When a proper token is provided, `onRoomDidConnect` should fire on the `TwilioVideo` component.

**Actual Android**: `<TwilioVideo onRoomDidConnect={() => console.log('connected')} />` --> `"Connected"`
**Actual IOS**: `<TwilioVideo onRoomDidConnect={() => console.log('connected')} />` --> Event not fired. Nothing logged

### Environment
- **Node.js version**: 14.17.0
- **React Native version**: 5.0.1-alpha.2
- **React Native platform + platform version**: iOS 10.0 & iOS 11.0

### react-native-twilio-video-webrtc
**Version**: `"react-native-twilio-video-webrtc": "git+https://github.com/blackuy/react-native-twilio-video-webrtc/#005926f77e13cf60672895a3d318ee52cefeead9",`

**Comment by tylerssn** [comment]
The docs for this version appear to be pretty much the same as the latest version. And, given that Android works, I'm not sure what I am missing. Perhaps something with the iOS setup?

https://github.com/blackuy/react-native-twilio-video-webrtc/tree/005926f77e13cf60672895a3d318ee52cefeead9

**Comment by slycoder** [comment]
Does it appear connected to the other party?  AFAIK the old version of the twilio library isn't really maintained any more so there's possibly some weirdness there.

**Comment by tylerssn** [comment]
Closing because of the older version of the twilio library I was forced to use should not be a concern for the maintainers of this repo.
