### ISSUE TITLE
How to change codec?

### ISSUE THREAD

**Issue by dangolbeeker** [blackuy/react-native-twilio-video-webrtc#506]
How can I change the codec format? I want all streams to be VP8 or H.264.

**Comment by slycoder** [comment]
On iOS, the `enableH264Codec` flag can be used to prefer H264 over VP8.  There's no explicit flag available for Android right now, although it should be easy to add (there's more information about codec negotiation here: https://www.twilio.com/docs/video/managing-codecs).
