### ISSUE TITLE
Dominant Speaker Changed event not exposed

### ISSUE THREAD

**Issue by workprotocol** [blackuy/react-native-twilio-video-webrtc#507]
Dominant Speaker changed event  seems not supported in the latest version.
Could you verify if it is supported, if not, how soon it may be available? 

### Environment
- **Node.js version**: 12+
- **React Native version**: 0.60+
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: 2.0

**Comment by slycoder** [comment]
This feature was added in #440
