### ISSUE TITLE
On iOS, I cannot join a room after Twilio has been called in another component

### ISSUE THREAD

**Issue by tylerssn** [blackuy/react-native-twilio-video-webrtc#515]
### Steps to reproduce
1. Implement a video previewer component. This is to allow the user to preview their video prior to joining a room.
 ```
const NativeLocalVideo = ({micEnabled, mobileFrontCam, videoEnabled, style}) => {
  const twilioNativeVideo = useRef();
  const [ready, setReady] = useState(false)

  useEffect(() => {

    // Currently IOS throws an error that the access token is crap
    Platform.OS ==='android'
      && twilioNativeVideo.current?.connect({ accessToken: null });
    
    setReady(true)
  }, [])

  useEffect(() => {
    if(!ready) return
    twilioNativeVideo.current?.flipCamera();
  }, [mobileFrontCam, ready])

  useEffect(() => {
    if(!ready) return
    twilioNativeVideo.current?.setLocalAudioEnabled(micEnabled)
  }, [micEnabled, ready])

  useEffect(() => {
    if(!ready) return
    twilioNativeVideo.current?.setLocalVideoEnabled(videoEnabled)
  }, [videoEnabled, ready])

  return <>
    <TwilioVideoLocalView enabled={true} scaleType={"fill"} style={style}/>
    <TwilioVideo ref={twilioNativeVideo}
                 onRoomDidConnect={() => {console.log('Previewer connected')}}
                 onRoomDidFailToConnect={() => {console.log('Previewer failed to connect. Normal without a token.')}}
                 onCameraDidStart={() => {console.log('Camera Started')}}
    />
  </>
}
```
2. Load the room component that implements it's own twilio ref, TwilioVideo, and TwilioVideoLocalView.

### Expected behaviour
iOS should connect to the room

### Actual behaviour
The onRoomConnected event never broadcasts. No errors are thrown.

### Environment
- **Node.js version**: 14.17.0
- **React Native version**: 5.0.1-alpha.2
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: `git+https://github.com/blackuy/react-native-twilio-video-webrtc#005926f77e13cf60672895a3d318ee52cefeead9`

**Comment by slycoder** [comment]
Are you simultaneously mounting multiple instances of TwilioVideo (e.g. by placing each screen in a stacknavigator?).  If so that will almost certainly be unsupported -- twiliovideo needs to be a singleton instance.

**Comment by tylerssn** [comment]
It's been a while since i fixed this but I'm pretty sure that's exactly what was happening
