### ISSUE TITLE
build fails because of minSdk declared in library

### ISSUE THREAD

**Issue by AurimasG12** [blackuy/react-native-twilio-video-webrtc#516]
After updating react native to 0.64 build always fails with error:  `uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library`

### Expected behaviour
it should build properly.
### Actual behaviour
Errors appeared.

### Environment
- **Node.js version**: v14.17.0
- **React Native version**: 0.64
- **React Native platform + platform version**: android api 30
### react-native-twilio-video-webrtc
**Version**: npm version or "master" version "1.0.2-1"

**Comment by slycoder** [comment]
Can you share the sdk settings you have in your build.gradle and android manifest?

**Comment by AurimasG12** [comment]
```
   ext {
        buildToolsVersion = "29.0.3"
        minSdkVersion = 21
        compileSdkVersion = 29
        targetSdkVersion = 29
        ndkVersion = "20.1.5948944"
    }
...
 defaultConfig {
        applicationId "com.example.app"
        minSdkVersion rootProject.ext.minSdkVersion
```

The problem is thath, the library have hardcoded minSdkVersion to 16, tried to change lines in lib and everything works fine.

**Comment by AurimasG12** [comment]
`minSdkVersion rootProject.hasProperty('minSdkVersion') ? rootProject.minSdkVersion : DEFAULT_MIN_SDK_VERSION` in library should be like this I guess
