### ISSUE TITLE
Change log level -- iOS (in particular)

### ISSUE THREAD

**Issue by josefpohl** [blackuy/react-native-twilio-video-webrtc#522]
More of a question.  I am trying to debug an ephemeral room connection failure.  Is there a way to change the log level per the Twilio documentation: [here](https://www.twilio.com/docs/video/ios#enabling-debug-logging)?

Thanks,
Josef

**Comment by slycoder** [comment]
That command isn't exposed to the js api in any way right now.

**Comment by josefpohl** [comment]
Thanks @slycoder
