### ISSUE TITLE
Upgrade to support H264 codec

### ISSUE THREAD

**Issue by bsiddiqui** [blackuy/react-native-twilio-video-webrtc#53]
Twilio's [video-quickstart-swift](https://github.com/twilio/video-quickstart-swift/issues/88#issuecomment-332315142) support H264 in the 2.0.0-preview release.

Will this lib support that or will their need to be an update to the API to support it?

**Comment by bilby91** [comment]
@bsiddiqui haven't review the CHANGELOG but I would assume that we will have some breaking changes. Highly likely that some changes will need to be done.

**Comment by ceaglest** [comment]
Hello,

I work on Twilio's iOS Video SDK. Yes, there are definitely some breaking changes in the 2.0.0-preview releases compared to 1.x. We expect that the APIs are will have less churn as we get closer to beta but I can't make any guarantees that we are done at this point. Our iOS and Android teams are planning on making some additive changes to support selective subscriptions in Group Rooms, and raising additional error callbacks before we are ready to cut a 2.0.0-beta1 release.

Best,
Chris Eagleston

**Comment by bilby91** [comment]
Hi @ceaglest !

Thanks for the update! I guess we will wait a little bit more before we can start trying the next version.

**Comment by slycoder** [comment]
2.x is on master.
