### ISSUE TITLE
Twilio ref functions link flipcamera , togglevideo , toggleaudio doesnt work properly

### ISSUE THREAD

**Issue by pranavaccion** [blackuy/react-native-twilio-video-webrtc#538]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
on toggle local audio function click : audio should be disabled or enabled.
on toggle local video function click : video should be disabled or enabled.
on flip camera function click :camera should flip between back and front.

### Actual behaviour
these all functions mentioned above works sometimes doesn't works . this is giving unexpected experience and really hard to debug as it dont show any error.

### Environment
- **Node.js version**:12.18.3
- **React Native version**:0.64.0
- **React Native platform + platform version**: iOS 11.0

### react-native-twilio-video-webrtc
**Version**: npm version or "master"

**Comment by pranavaccion** [comment]
closing the issue as it was a ref error

**Comment by hardikcc** [comment]
Can you share the name of function to toggle local video? I am not able to find that in document.

**Comment by vikrambombhi** [comment]
@hardikcc this works for me `twilioRef.current.setLocalVideoEnabled(true)`
