### ISSUE TITLE
twilioVideo.current.connect function is not working sometimes

### ISSUE THREAD

**Issue by pranavaccion** [blackuy/react-native-twilio-video-webrtc#540]
### Expected behaviour
twilioVideo.current.connect({
			accessToken: jwt,
			enableNetworkQualityReporting: true,
			dominantSpeakerEnabled: true,
		});
should call onRoomDidConnect function 
### Actual behaviour
twilioVideo.current.connect({
			accessToken: jwt,
			enableNetworkQualityReporting: true,
			dominantSpeakerEnabled: true,
		});
not calling onRoomDidConnect function and room is not connecting
Environment
Node.js version:12.18.3
React Native version:0.64.0
React Native platform + platform version: iOS 11.0

### react-native-twilio-video-webrtc
**Version**: npm version or "master"

**Comment by slycoder** [comment]
Do you have any more info you could provide here?  Does onRoomDidFailToConnect get called?

**Comment by pranavaccion** [comment]
no it does not get called

**Comment by chat2vignesh** [comment]
> Do you have any more info you could provide here? Does onRoomDidFailToConnect get called?

onRoomDidConnect method not give any return values
