### ISSUE TITLE
Release 2.1.0

### ISSUE THREAD

**Issue by slycoder** [blackuy/react-native-twilio-video-webrtc#542]

**Comment by slycoder** [comment]
The hope is to knock out a couple of the nagging bugs that people are experiencing with the current release and push it out to npm.

**Comment by slycoder** [comment]
I don't have a hard timeline on that, but if people feel strongly that they would like this or that feature in the meantime, I am open to more releases.

**Comment by jpodwys** [comment]
Hi, @slycoder I would really appreciate a release to expose the dominant speaker functionality merged in #440. If I understand correctly, this repo's most recent NPM publish was made on December 27 202 and the dominant speaker functionality was merged on Jan 24th 2021. Are you open to making another release to expose these features?

**Comment by slycoder** [comment]
Sorry about that.  This should be done now!  Let me know if it looks ok.
