### ISSUE TITLE
Library Version 2.0.0 - RN 0.65.1 - Gradle 6.9 cant compile on Android

### ISSUE THREAD

**Issue by jhazucha** [blackuy/react-native-twilio-video-webrtc#543]
### Steps to reproduce
1. Init a fresh RN 0.65.1 project
2. Add Modules - yarn add https://github.com/blackuy/react-native-twilio-video-webrtc
3. Perform all steps listed in installation instructions for android
4. run "npx react-native run-android"

### Expected behaviour
It should compile without errors.

### Actual behaviour
I am receiving that it canot find org.webrtc:google-webrtc:
* What went wrong:
   Execution failed for task ':app:checkDebugAarMetadata'.
   > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
    > Could not find org.webrtc:google-webrtc:1.0.30039.
Searched in the following locations:
- https://repo.maven.apache.org/maven2/org/webrtc/google-webrtc/1.0.30039/google-webrtc-1.0.30039.pom
       - file:/Users/my-username/.m2/repository/org/webrtc/google-webrtc/1.0.30039/google-webrtc-1.0.30039.pom
       - file:/Users/my-username/Projects/Tests/Test2/node_modules/react-native/android/org/webrtc/google-webrtc/1.0.30039/google-webrtc-1.0.30039.pom
       - file:/Users/my-username/Projects/Tests/Test2/node_modules/jsc-android/dist/org/webrtc/google-webrtc/1.0.30039/google-webrtc-1.0.30039.pom
       - https://dl.google.com/dl/android/maven2/org/webrtc/google-webrtc/1.0.30039/google-webrtc-1.0.30039.pom
       - https://www.jitpack.io/org/webrtc/google-webrtc/1.0.30039/google-webrtc-1.0.30039.pom
     Required by:
         project :app > project :react-native-twilio-video-webrtc

Also cannot find com.getkeepsafe.relinker:relinker

   > Could not find com.getkeepsafe.relinker:relinker:1.3.1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/getkeepsafe/relinker/relinker/1.3.1/relinker-1.3.1.pom
       - file:/Users/my-username/.m2/repository/com/getkeepsafe/relinker/relinker/1.3.1/relinker-1.3.1.pom
       - file:/Users/my-username/Projects/Tests/Test2/node_modules/react-native/android/com/getkeepsafe/relinker/relinker/1.3.1/relinker-1.3.1.pom
       - file:/Users/my-username/Projects/Tests/Test2/node_modules/jsc-android/dist/com/getkeepsafe/relinker/relinker/1.3.1/relinker-1.3.1.pom
       - https://dl.google.com/dl/android/maven2/com/getkeepsafe/relinker/relinker/1.3.1/relinker-1.3.1.pom
       - https://www.jitpack.io/com/getkeepsafe/relinker/relinker/1.3.1/relinker-1.3.1.pom
     Required by:
         project :app > project :react-native-twilio-video-webrtc > com.twilio:video-android:6.2.1

### Environment
- **Node.js version**: 16.6.2
- **React Native version**: 0.65.1
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: 2.0.0

Also iOS builds and seems to run just fine.

**Comment by wbroek** [comment]
> @jhazucha I found a temporary fix for this was to add jcenter() back into the 2 lists of dependencies in build.gradle. These are deprecated and were removed by default in a recent React Native update, but seem to be required for this version of google-webrtc to resolve.

I would add the specific packages from jCenter so no other conflicts can occur because jCenter does not allow any updates anymore:
```
jcenter() {
    content {
        includeModule("org.webrtc", "google-webrtc")
        includeModule("com.getkeepsafe.relinker", "relinker")
    }
}
```

Also it's not only `google-webrtc` but `relinker` as well, which is a dependency of `com.twilio:video-android` That one should be resolved when `video-android` in this project is updated.

Maybe an idea to update the example app and readme with this because could not find any other release of `google-webrtc` on mavenCentral etc.......

**Comment by erisvaldojunior** [comment]
jcenter() is quite unstable / deprecated for a while. Can't we have this working with mavenCentral() ?

**Comment by hsavit1** [comment]
yeah this repo needs to move off of jcenter() ASAP

**Comment by hpardess** [comment]
faced same error but i solved by adding following piece of code in android/build.gradle
```
        mavenCentral()
        jcenter() {
            content {
                includeModule("org.webrtc", "google-webrtc")
                includeModule("com.getkeepsafe.relinker", "relinker")
            }
        }
```

**Comment by hpardess** [comment]
> > @jhazucha I found a temporary fix for this was to add jcenter() back into the 2 lists of dependencies in build.gradle. These are deprecated and were removed by default in a recent React Native update, but seem to be required for this version of google-webrtc to resolve.
> 
> I would add the specific packages from jCenter so no other conflicts can occur because jCenter does not allow any updates anymore:
> 
> ```
> jcenter() {
>     content {
>         includeModule("org.webrtc", "google-webrtc")
>         includeModule("com.getkeepsafe.relinker", "relinker")
>     }
> }
> ```
> 
> Also it's not only `google-webrtc` but `relinker` as well, which is a dependency of `com.twilio:video-android` That one should be resolved when `video-android` in this project is updated.
> 
> Maybe an idea to update the example app and readme with this because could not find any other release of `google-webrtc` on mavenCentral etc.......

I tried this piece of code but still it fails as jcenter returns 502 BAD GATEWAY

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:lintVitalRelease'.
> Could not resolve all artifacts for configuration ':react-native-community_masked-view:releaseRuntimeClasspath'.
   > Could not resolve com.facebook.react:react-native:+.
     Required by:
         project :react-native-community_masked-view
      > Failed to list versions for com.facebook.react:react-native.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/facebook/react/react-native/maven-metadata.xml'. Received status code 502 from server: Bad Gateway
```

**Comment by neilyoung** [comment]
Last week there was a big outage, making it impossible to download Google Maps, WebRTC and stuff. Today (Jan 17) it seems to be the same shit again. 

https://mvnrepository.com/artifact/org.webrtc/google-webrtc/1.0.32006

> Note: this artifact is located at WebRTC repository (https://dl.bintray.com/google/webrtc/)

The mentioned URL gives 502.

I feel challenged to say "Thanks, JCenter" (or whoever is involved in this mess). 

Historical outage data, which I was privileged to witness last week: https://status.gradle.com/history

No mentioning of yesterday or today, but impossible to work with gradle and webrtc

**Comment by neilyoung** [comment]
BTW: 

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

UPDATE 4/27/2021: We listened to the community and will keep JCenter as a read-only repository indefinitely. Our customers and the community can continue to rely on JCenter as a reliable mirror for Java packages.

**Comment by svkd** [comment]
> > @jhazucha I found a temporary fix for this was to add jcenter() back into the 2 lists of dependencies in build.gradle. These are deprecated and were removed by default in a recent React Native update, but seem to be required for this version of google-webrtc to resolve.
> 
> I would add the specific packages from jCenter so no other conflicts can occur because jCenter does not allow any updates anymore:
> 
> ```
> jcenter() {
>     content {
>         includeModule("org.webrtc", "google-webrtc")
>         includeModule("com.getkeepsafe.relinker", "relinker")
>     }
> }
> ```
> 
> Also it's not only `google-webrtc` but `relinker` as well, which is a dependency of `com.twilio:video-android` That one should be resolved when `video-android` in this project is updated.
> 
> Maybe an idea to update the example app and readme with this because could not find any other release of `google-webrtc` on mavenCentral etc.......

This is working ATM, using jcenter only for google-webrtc, relinker did the trick

**Comment by neilyoung** [comment]
> This is working ATM, using jcenter only for google-webrtc, relinker did the trick

No, can't confirm this ATM, unless you are using a different implementation reference:

I'm using this:

`implementation 'org.webrtc:google-webrtc:1.0.+'``

What is your's?

**Comment by svkd** [comment]
I am using this(default) implementation 'org.webrtc:google-webrtc:1.0.30039'

**Comment by neilyoung** [comment]
'Could not find org.webrtc:google-webrtc:1.0.30039.'

I would suggest to make a clean _ONLINE_ build. You'll see, it doesn't work

**Comment by neilyoung** [comment]
BTW: The latest (and last version) is this: https://mvnrepository.com/artifact/org.webrtc/google-webrtc/1.0.32006

**Comment by neilyoung** [comment]
To be fair: JCenter is back. But the numerous outages let me have some concerns. At least they promised to keep the service read-only once and forever.

**Comment by slycoder** [comment]
Hi all, if anyone wants to submit a PR for a more reliable solution, I'd be happy to push it out with another release.
