### ISSUE TITLE
Unable to build on XCode

### ISSUE THREAD

**Issue by SharonGilmore** [blackuy/react-native-twilio-video-webrtc#547]
### Steps to reproduce
I'm building a project on a new mac mini.  Have previously built it on a different Mac mini with no issues. Pulled code from Git repository, ran npm install and pod install - both appeared to complete successfully. Cleaned build folder.  Attempted to build project.

### Expected behaviour
Project should build - has built in previous versions of XCode on other people's machines

### Actual behaviour
Reaches Twilio part of build and displays the following errors:
Undefined symbol: _OBJC_CLASS_$_TVITrackPublication
Undefined symbol: _OBJC_CLASS_$_TwilioVideoSDK
Undefined symbol: _OBJC_CLASS_$_TVINetworkQualityConfiguration
Undefined symbol: _OBJC_CLASS_$_TVIH264Codec
Undefined symbol: _OBJC_CLASS_$_TVIConnectOptions
Undefined symbol: _OBJC_CLASS_$_TVILocalAudioTrack
Undefined symbol: _OBJC_CLASS_$_TVIParticipant
Undefined symbol: _OBJC_CLASS_$_TVICameraSource
Undefined symbol: _OBJC_CLASS_$_TVIVideoView
Undefined symbol: _OBJC_CLASS_$_TVILocalDataTrack
Undefined symbol: protocol descriptor for Swift.ExpressibleByFloatLiteral
Undefined symbol: associated type descriptor for Swift.ExpressibleByIntegerLiteral.IntegerLiteralType
Undefined symbol: associated conformance descriptor for Swift.ExpressibleByIntegerLiteral.Swift.ExpressibleByIntegerLiteral.IntegerLiteralType: Swift._ExpressibleByBuiltinIntegerLiteral
Undefined symbol: _OBJC_CLASS_$_TVIEncodingParameters
Undefined symbol: __swift_FORCE_LOAD_$_swiftCoreFoundation
Undefined symbol: method descriptor for Swift.ExpressibleByFloatLiteral.init(floatLiteral: A.FloatLiteralType) -> A
Undefined symbol: _OBJC_CLASS_$_TVICameraSourceOptions
Undefined symbol: protocol descriptor for Swift.ExpressibleByIntegerLiteral
Undefined symbol: value witness table for Builtin.Int32
Undefined symbol: _OBJC_CLASS_$_TVILocalVideoTrack
Undefined symbol: __swift_FORCE_LOAD_$_swiftCoreGraphics
Undefined symbol: __swift_FORCE_LOAD_$_swiftCoreImage
Undefined symbol: protocol witness table for Swift.Float : Swift._ExpressibleByBuiltinFloatLiteral in Swift
Undefined symbol: __swift_FORCE_LOAD_$_swiftFoundation
Undefined symbol: _swift_getForeignTypeMetadata
Undefined symbol: method descriptor for Swift.ExpressibleByIntegerLiteral.init(integerLiteral: A.IntegerLiteralType) -> A
Undefined symbol: __swift_FORCE_LOAD_$_swiftObjectiveC
Undefined symbol: protocol witness table for Swift.Int : Swift._ExpressibleByBuiltinIntegerLiteral in Swift
Undefined symbol: associated type descriptor for Swift.ExpressibleByFloatLiteral.FloatLiteralType
Undefined symbol: __swift_FORCE_LOAD_$_swiftQuartzCore
Undefined symbol: __swift_FORCE_LOAD_$_swiftDispatch
Undefined symbol: associated conformance descriptor for Swift.ExpressibleByFloatLiteral.Swift.ExpressibleByFloatLiteral.FloatLiteralType: Swift._ExpressibleByBuiltinFloatLiteral
Undefined symbol: __swift_FORCE_LOAD_$_swiftUIKit
Undefined symbol: __swift_FORCE_LOAD_$_swiftMetal
Undefined symbol: Swift.Float.init(Swift.Double) -> Swift.Float
Undefined symbol: __swift_FORCE_LOAD_$_swiftDarwin

### Environment
- **Node.js version**: 14.17.5
- **React Native version**: 0.64.2
- **React Native platform + platform version**: iOS 9.0 (I think)

### react-native-twilio-video-webrtc
**Version**: 2.0.0

**Comment by slycoder** [comment]
Closing for staleness.  Let me know if this is still an issue and if you have a repro.
