### ISSUE TITLE
How can I fetch the local participant SID?

### ISSUE THREAD

**Issue by tylerssn** [blackuy/react-native-twilio-video-webrtc#548]
### Steps to reproduce
1. For iOS 10 compatibility: `yarn add  git+https://github.com/blackuy/react-native-twilio-video-webrtc#005926f77e13cf60672895a3d318ee52cefeead9`
2. Paste readme.md docs into app to get a working version

### Expected behaviour
I should be able to get the local participant SID via one of the events or by making an SDK call

### Actual behaviour
There doesn't appear to be a documented method of identifying the local participant SID

### Environment
- **Node.js version**: 12.22.3
- **React Native version**: 0.63
- **React Native platform + platform version**: iOS 10.0

### react-native-twilio-video-webrtc
**Version**: https://github.com/blackuy/react-native-twilio-video-webrtc#005926f77e13cf60672895a3d318ee52cefeead9

**Comment by slycoder** [comment]
The local participant is available in the onRoomDidConnect event under the field event["localParticipant"]["sid"].

**Comment by tylerssn** [comment]
The commit that I am using (linked to in the issue description) doesn't return local participant.

However, I see that Twilio Video 4.6 now supports building on iOS 9/10 (with limitations), so I may be able to use a fork of the latest version now \( ﾟヮﾟ)/

**Comment by tylerssn** [comment]
Yep. At long last I can use a current branch 🙂.

I forked the repo, set Twilio Video to 4.6 and was able to set iOS support to 10.

I'm now able to use the latest version of the react events.

**Comment by slycoder** [comment]
Huzzah, if you wanna send a PR to have that change be on master, I'd be happy to take a look!

**Comment by tylerssn** [comment]
https://github.com/blackuy/react-native-twilio-video-webrtc/pull/549
