### ISSUE TITLE
Getting error while trying to make a call 

### ISSUE THREAD

**Issue by devlove1C** [blackuy/react-native-twilio-video-webrtc#563]
### Steps to reproduce
1. Run the project and try to connect the call 
2. Tap on the connect button

**Note:**
I get a token  from Twilio Testing tools  to Make the Call 
I used this token in the given example. But it's giving the Error 

![image](https://user-images.githubusercontent.com/21331129/136420947-d1d94aff-319a-43a9-b803-e9c9eafac4e1.png)
 

### Expected behavior 
The app is supposed to start a video chat.

### Actual behaviour
i get this error in the console  {"error": "Signaling connection error", "roomName": "", "roomSid": ""}

### Environment
- **Node.js version**: -  v14.17.3
- **React Native version**:-  react-native-cli: 2.0.1
- **React Native platform + platform version**: iOS 9.0 :- Android + android version 11

### react-native-twilio-video-webrtc
    **Version**: - "master"
@marqroldan , 
Could you help here ?

**Comment by majorb22** [comment]
I have the same issue. Any solutions?

**Comment by befirst** [comment]
Have the same issue with the previously working access token
