### ISSUE TITLE
Android app must be restarted to acknowledge camera permissions

### ISSUE THREAD

**Issue by tylerssn** [blackuy/react-native-twilio-video-webrtc#564]
### Steps to reproduce
1. Install the latest master branch package
2. Do not attempt to call reat-native-twilio-video-webrtc components _at all_ until permissions have been confirmed

### Expected behaviour
iOS & Android should be ready to use immediately after permissions have been granted

### Actual behaviour
iOS works but the Android app must be restarted

### Environment
- **Node.js version**: 14.18.0
- **React Native version**: `"react-native": "^0.63.2"`
- **React Native platform + platform version**: Android SDK 28

### react-native-twilio-video-webrtc
**Version**: "master" (`"react-native-twilio-video-webrtc": "https://github.com/blackuy/react-native-twilio-video-webrtc"`

**Comment by slycoder** [comment]
Does it suffice to unmount and remount the TwilioVideo component?

**Comment by tylerssn** [comment]
At your prompt, I couldn't imagine how on earth my Twilio components could be called prior to permissions being granted. Apparently, React doesn't care what my imagination is capable of.

That was the issue. While permissions were being checked, React was sneaking past my permissions firewall and making a call to my Twilio components. This did not bug out my app on iOS, once permissions were granted, iOS does its thing and renders the video. However, it seems that if you try to load Twilio when video permissions have not been granted the app must be restarted (hot reloading and refreshing didn't do the trick for me).

The component could never get past [this line of code](https://github.com/blackuy/react-native-twilio-video-webrtc/blob/9f41911b8ec75eb3cdbfa8f0277bb3d6aa03941e/android/src/main/java/com/twiliorn/library/CustomTwilioVideoView.java#L454).

**Comment by Balasnest** [comment]
@slycoder @tylerssn what is the resolution for this issue? It's a blocker until the app is restarted.

**Comment by tylerssn** [comment]
@Balasnest you need to make sure that the component is not called at all until video and mic permissions have been granted.
