### ISSUE TITLE
videoTracks.delete is not a function

### ISSUE THREAD

**Issue by OmkarArote** [blackuy/react-native-twilio-video-webrtc#569]
### Steps to reproduce
1. I start the call
2. Then I end the call

### Expected behavior
The call Should end as usual

### Actual behavior
It shows me following error:
<pre>TypeError: videoTracks.delete is not a function. (In 'videoTracks.delete(track.trackSid)', 'videoTracks.delete' is undefined)</pre>

### Environment
- **Node.js version**: v14.18.1
- **React Native version**: 0.64.3
- **React Native platform + platform version**: API 30

### react-native-twilio-video-webrtc
**Version**: "master"

IMG:
![image](https://user-images.githubusercontent.com/64545577/143535563-2b0bd601-eabf-44c3-bb86-1e9fff87d2c7.png)

**Comment by SumanMaharana** [comment]
I'm Facing the same issue as mentioned by @OmkarArote . 
i tried to find the solution in stackoverflow but I couldn't find anything related to it

**Comment by slycoder** [comment]
Closing for staleness.  Please let me know if this is still an issue on the latest version.
