### ISSUE TITLE
Duplicate and redefinition errors

### ISSUE THREAD

**Issue by moksamedia** [blackuy/react-native-twilio-video-webrtc#57]
When I attempt to use the 1.0.1 version of this package installed with npm, I get a bunch of duplicate symbol errors in XCode when I build it there. Any suggestions on how to fix this? The react native app itself gives the following error: "Native module cannot be null"

    "react": "16.0.0-alpha.12",
    "react-native": "0.47.2",

**Comment by bilby91** [comment]
Hi @moksamedia 

Use the project via git, the npm package is outdated at the moment.

Thanks!
