### ISSUE TITLE
How to help?

### ISSUE THREAD

**Issue by ASrey** [blackuy/react-native-twilio-video-webrtc#571]
Hi all,

I'm kind of a newbie when it comes to gitlab OS.
I would liek to help to improve this project even if it's just a matter of testing and approving some merge request.
However, i really don't know how all of this work.

Is there any contributors willing to guide me/giving some advice? 

(Why would i help here? because of some of theses fix/enhancements ^^') 

Ty all

**Comment by slycoder** [comment]
Hi, I think the best way to help would be to find an enhancement / bugfix that you'd like to work on, and submit a PR.  If you're having trouble getting started on it, lemme know and maybe I can give you a few pointers.
