### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by jpodwys** [blackuy/react-native-twilio-video-webrtc#580]
Hi, @slycoder thanks for all your work! I would really appreciate a release to expose the dominant speaker functionality merged in #440. Are you open to publishing a release to expose this feature?

**Comment by slycoder** [comment]
Hi, sorry for the delay.  I'll try to work on this in the next few days.

**Comment by slycoder** [comment]
c.f. #542

**Comment by jpodwys** [comment]
Thank you! No apology necessary, I know you have a life outside of this project so I really appreciate you making some time for me. I'll follow the linked issue for updates.
