### ISSUE TITLE
Unable to run project after installing this library - Could not find org.webrtc:google-webrtc:1.0.30039

### ISSUE THREAD

**Issue by Purushottam-industrility** [blackuy/react-native-twilio-video-webrtc#593]
### Steps to reproduce
1. yarn add react-native-twilio-video-webrtc
2. react-native link react-native-twilio-video-webrtc
3. react-native run-android

### Expected behaviour
It properly build the project

### Actual behaviour
It is throwing following error while running project:

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.9/userguide/command_line_interface.html#sec:command_line_warnings
30 actionable tasks: 27 executed, 3 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find org.webrtc:google-webrtc:1.0.30039.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/webrtc/google-webrtc/1.0.30039/google-webrtc-1.0.30039.pom

### Environment
- **Node.js version**:
- **React Native version**:0.67.2
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: npm version or "master"

**Comment by slycoder** [comment]
See #543
