### ISSUE TITLE
Can't get dominant speaker to activate

### ISSUE THREAD

**Issue by SharonGilmore** [blackuy/react-native-twilio-video-webrtc#607]
### Steps to reproduce
I have a 2-way video call between a mobile app and a web app which is set up via a group room.  I've set up the video call on mobile as follows:

```
<TwilioVideo
        ref={twilioRef}
        onDominantSpeakerDidChange={_onDominantSpeakerDidChange}
        onRoomDidConnect={_onRoomDidConnect}
        onRoomDidDisconnect={_onRoomDidDisconnect}
        onRoomDidFailToConnect={_onRoomDidFailToConnect}
        onParticipantAddedVideoTrack={_onParticipantAddedVideoTrack}
        onParticipantRemovedVideoTrack={_onParticipantRemovedVideoTrack}
      />
```

where _onDominantSpeakerDidChange is:

```
  const _onDominantSpeakerDidChange = () => {
    console.log('Dominant speaker changed');
  };
```

### Expected behaviour
When I start the call I switch between speakers (web & mobile).  I expected that the dominant speaker would change when one person stopped speaking and the other person started; I thought that this would trigger the console log.

### Actual behaviour
Nothing happens in the console.  I can  put a console log into any of the other functions (onRoomDidConnect etc) and it works, so I know that that aspect is working.

### Environment
- **Node.js version**: 16.13.1
- **React Native version**: 0.64.3
- **React Native platform + platform version**: iOS 14.8.1

### react-native-twilio-video-webrtc
**Version**: npm version

**Comment by slycoder** [comment]
Can you just verify that dominantSpeakerEnabled is being set to true in the call to `connect`?

**Comment by SharonGilmore** [comment]
Found it - I was using enableDominantSpeaker instead of dominantSpeakerEnabled.  My bad!
