### ISSUE TITLE
Not able to connect Twilio video calling from web to mobile app

### ISSUE THREAD

**Issue by sumitk8Chetu** [blackuy/react-native-twilio-video-webrtc#613]
### Steps to reproduce
1.I have followed all the guideline which is given in https://github.com/blackuy/react-native-twilio-video-webrtc doc. We are able to connect mobile to mobile but not able to connect consistently from web to mobile app.
2. In rare case we are able to connect from web to mobile but not getting video from web side.
3. We are not getting any issue only just we are not able to do proper video call communication from web to mobile.
4. Please suggest us what can be the issue are any other way to implement this functionality

### Expected behavior
We are expecting to do proper video call communication and also want's to get the video frame for both side from mobile to web.

### Environment
- **Node.js version**: v16.14.0
- **React Native version**: 0.65.1

**Comment by slycoder** [comment]
Consolidating into #619
