### ISSUE TITLE
onParticipantRemovedVideoTrack never gets called

### ISSUE THREAD

**Issue by cipriancaba** [blackuy/react-native-twilio-video-webrtc#63]
### Steps to reproduce
1. Connect to a room from 2 different iOS devices
2. Disconnect from the second device
3. `onParticipantRemovedVideoTrack` for the first device is not called

### Expected behaviour
`onParticipantRemovedVideoTrack` should be called on the first device that is still connected

### Actual behaviour
No way to tell if a second device has disconnected, which leaves us with a frozen video stream

### Environment
- **Node.js version**: v8.8.1
- **React Native version**: v0.49.3
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: npm version or "master"  version "1.0.2"
Pod dependency `s.dependency 'TwilioVideo', '>= 1.0.1'` which resolves to - `TwilioVideo (1.3.7)`

Might be related to #56

**Comment by bilby91** [comment]
@cipriancaba Have you seen this issue https://github.com/twilio/video-quickstart-swift/issues/99 ? I think it might be related.

**Comment by bilby91** [comment]
Also, https://www.twilio.com/docs/api/video/changelogs/ios#137-october-17-2017

**Comment by bilby91** [comment]
Closing this one since it's a know issue in `TwilioVideo` 1.X

**Comment by moksamedia** [comment]
@bilby91 Is there a work around if this is a known issue?

**Comment by bilby91** [comment]
@moksamedia I'm not aware of any workaround for this problem sadly. This are the issues in the Twilio library:

- https://github.com/twilio/video-quickstart-swift/issues/99
- https://github.com/twilio/video-quickstart-android/issues/80
