### ISSUE TITLE
Looking to install the latest commit in master into my project

### ISSUE THREAD

**Issue by thaddavis** [blackuy/react-native-twilio-video-webrtc#640]
The last commit `ff28b67a6c39a944a8bc2556366d69d0e2746ecd` adds the androidx annotations and I would love to get it into my project...

Is it possible to create a tag on the latest commit: `2.1.1` ?

Cheers!

**Comment by tgoins** [comment]
Use this in your package.json, within the dependencies:
```
"react-native-twilio-video-webrtc": "blackuy/react-native-twilio-video-webrtc#ff28b67a6c39a944a8bc2556366d69d0e2746ecd",
```

**Comment by slycoder** [comment]
Published a new version on npm.
