### ISSUE TITLE
How to listen to onParticipantDisabledVideoTrack. Able to listen to onParticipantAddedVideoTrack but not able to listen to  onParticipantDisabledVideoTrack.

### ISSUE THREAD

**Issue by vipulSoni458** [blackuy/react-native-twilio-video-webrtc#641]
### Steps to reproduce
1. Add two participant A and B in a room.
2. A join the room. Now B join the room without camera. 
3. B is added in DOM for A but onParticipantDisabledVideoTrack is not triggered. So cannot modify UI according to it.

### Expected behaviour
onParticipantDisabledVideoTrack should trigger so that by listening to it we can modify our UI if some participant join without camera. When participant join with camera its working fine but without camera its not triggered.

### Actual behaviour
onParticipantDisabledVideoTrack does not trigger at all. So does not know if new participant added in room or not.

### react-native-twilio-video-webrtc
**Version**: 2.1.0

**Comment by thanhnvpk01168** [comment]
hi @vipulSoni458 
did you resolve issue?

**Comment by slycoder** [comment]
`onParticipantDisabledVideoTrack` is only triggered when the participant disables the track after it has been added.  If you want to know whether or not the track was enabled at connection time, you can look at the `enabled` property on the track.
