### ISSUE TITLE
Could not find org.webrtc:google-webrtc:1.0.32006

### ISSUE THREAD

**Issue by jagamypriera** [blackuy/react-native-twilio-video-webrtc#644]
### Steps to reproduce
1. Remove jcenter
2. Build Android
3. Error `Could not find org.webrtc:google-webrtc:1.0.32006`

### Expected behaviour
`org.webrtc:google-webrtc` should works without `jcenter`

### Actual behaviour
`org.webrtc:google-webrtc:1.0.32006` couldn’t work without jcenter.
From [Google announcement ](https://developer.android.com/studio/build/jcenter-migration), any project should migrate from jcenter. I've found [google-webrtc](https://central.sonatype.dev/artifact/com.infobip/google-webrtc/1.0.35530/versions) on Central Repository from diff org. Is it safe to use that instead?

### Environment
- **Node.js version**: v16.15.0
- **React Native version**: 0.70.1
- **React Native platform + platform version**: Android 12

### react-native-twilio-video-webrtc
**Version**: master

**Comment by rpluniversity** [comment]
I also have a problem here!

**Comment by ChandraveerSingh1** [comment]
I am also facing this issue

**Comment by SmikeForYou** [comment]
same issue

**Comment by slycoder** [comment]
If anyone is up for it, it'd be interesting to try removing the dependency and rejiggering all dependencies to use `tvi.webrtc` in lieu of `org.webrtc`.

**Comment by jagamypriera** [comment]
Thanks @slycoder

**Comment by amitdhakaa** [comment]
Have anyone got solution for this error?

**Comment by maratsct** [comment]
Add this to your settings.gradle
  
maven { url = "https://jcenter.bintray.com" }

**Comment by hossanshamim92** [comment]
Yes I got that solution.

in **settings.gradle**
 repositories {
        ...,
        maven { url "https://raw.githubusercontent.com/alexgreench/google-webrtc/master" }
    }

And in **build.gradle**
implementation 'org.webrtc:google-webrtc:1.0.30039@aar'

**Comment by KozinOleg** [comment]
@hossanshamim92  THX a lot, you saved my time on friday)))
