### ISSUE TITLE
Change audio output

### ISSUE THREAD

**Issue by timmeh-m** [blackuy/react-native-twilio-video-webrtc#66]
Has anyone managed to figure out a way to change the audio output of a video call? On my iPad it's going through speakers since that's all it's got but on the iPhone it diverts through the earpiece. I have tried setting AVAudioSession in the AppDelegate.m to PlayAndRecord as well to send audio to the speaker but no luck. Have not tried on Android yet. Anyone have any ideas?

**Comment by Praxey** [comment]
I figured this out for both Android and IOS. Lets you toggle between speakerphone and normal audio chat audio setup. I'll do a pull request in the next day or so.

**Comment by owenadley** [comment]
@timmeh-m with this patch, should a user be able to receive audio through a bluetooth device during a twilio video? Do you know if there are any pre requisites for this?
