### ISSUE TITLE
Connect Bluetooth Headphone  In Between call Voice not coming from headphone  in android 

### ISSUE THREAD

**Issue by SachinPal8050101** [blackuy/react-native-twilio-video-webrtc#660]
### Steps to reproduce
1.  Connect call without headphone 
2. In between call connect headphone 
3. Voice will not coming through headphone in android 

PR - https://github.com/blackuy/react-native-twilio-video-webrtc/pull/659

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Environment
- **Node.js version**:
- **React Native version**:
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: npm version or "master"

**Comment by gz1992** [comment]
hey, on version 2.1.0 i am having the same problem

**Comment by SachinPal8050101** [comment]
> hey, on version 2.1.0 i am having a similar problem... The sound I receive is not coming to the bluetooth device, on my android

Do the same thing will work

**Comment by SachinPal8050101** [comment]
> > > hey, on version 2.1.0 i am having a similar problem... The sound I receive is not coming to the bluetooth device, on my android
> > 
> > 
> > Do the same thing will work
> 
> sorry, I didnt understand

Do these changes https://github.com/blackuy/react-native-twilio-video-webrtc/pull/659
will work for you

**Comment by gz1992** [comment]
it didnt work ;(

**Comment by SachinPal8050101** [comment]
> it didnt work ;(

We can look at this  together.

**Comment by gz1992** [comment]
i need to focus on other stuff, how can i contact you another time?

**Comment by SachinPal8050101** [comment]
> 

yes ping me at this sachinpal8050101@gmail.com
