### ISSUE TITLE
[Android] When iOS user toggles camera (disables/reenables) participant video doesnt return

### ISSUE THREAD

**Issue by cengizhanhakan** [blackuy/react-native-twilio-video-webrtc#662]
### Steps to reproduce
ANDROID-IOS call
1. Android joins
2.iOS joins
3.iOS disables/unpublishes videoTrack
4.iOS enables/publishes videoTrack
5.Android participant view looks empty.

### Expected behaviour
Video should appear instead of black background.

### Actual behaviour
Black screen appears instead of video

### Environment
- **Node.js version**: 16
- **React Native version**: 0.66.3
- **React Native platform + platform version**: iOS 15.4 / Android 11

### react-native-twilio-video-webrtc
**Version**: npm version or "master"

**Comment by SachinPal8050101** [comment]
You have handle it on your side based on sid Thanks !!

**Comment by cengizhanhakan** [comment]
@SachinPal8050101 that wasnt the case I am afraid. but my issue is resolved after upgrading to version 3.0.0

**Comment by SachinPal8050101** [comment]
Okay That's good ! @cengizhanhakan
