### ISSUE TITLE
Update react-native-twilio-video-webrtc ?

### ISSUE THREAD

**Issue by kasperkberg** [blackuy/react-native-twilio-video-webrtc#671]
3.0.0 is a couple of months old now, and there are changes that have been merged we would like to have in our project, such as this [commit](https://github.com/blackuy/react-native-twilio-video-webrtc/commit/76c8cab685899abe129eec8574696dec12c357a8). 
Any chance the package can be updated soon?

**Comment by slycoder** [comment]
Ok, published 3.1.0
