### ISSUE TITLE
Keep a Changelog and/or track Releases on Github

### ISSUE THREAD

**Issue by cfnelson** [blackuy/react-native-twilio-video-webrtc#72]
I was recently going through the codebase and found it difficult to track the changes, additions, bug fixes & development of this package.

Would you consider maintaining a `CHANGELOG.md` and/or using Releases on [github](https://github.com/blackuy/react-native-twilio-video-webrtc/releases) to help track changes to the package.

If you are interested I would recommend (I have personally used) the [keepachangelog](http://keepachangelog.com/en/1.0.0/) style/template. 🔥 And would be happy to help if you had any questions.

**Comment by bilby91** [comment]
We are going to add this soon!
