### ISSUE TITLE
Why I install package command: "npm i react-native-twilio-video-webrtc --save"

### ISSUE THREAD

**Issue by tiennguyen1293** [blackuy/react-native-twilio-video-webrtc#73]
It looks like the files in node_modules are different from yours
And I get this error: 

> Warning: Native component for "TWVideoPreview" does not exist

**Comment by bilby91** [comment]
@tiennguyen1293 The npm package is not updated. Please use the package via git as in the README.

Thanks!

**Comment by tiennguyen1293** [comment]
@bilby91, Sorry but when i use the package via git as in the README then:
![screenshot_1](https://user-images.githubusercontent.com/26110369/33821007-c09d2fa8-de84-11e7-9887-8b674354afcf.png)

**Comment by bilby91** [comment]
I think you are having some issue with windows. Can you try adding the package name in the package.json ? I just tried the command in the README and is working.
