### ISSUE TITLE
Twilio react-native-twilio-video-webrtc vs twilio official

### ISSUE THREAD

**Issue by poojalivin** [blackuy/react-native-twilio-video-webrtc#736]
Hi,
  This is my doubt rather than an open issue. Our web development team is currently using Twilio paid version for an application. Will it be okay if I use this library along with that for the same application's mobile version. What are the challenges expected on this implementation.

**Comment by gastonmorixe** [comment]
You can use it ofc. This is for react native. It’s open source under MIT.
