### ISSUE TITLE
java.lang.IllegalStateException: A VideoCapturer must provide at least one supported VideoFormat

### ISSUE THREAD

**Issue by Moussawi7** [blackuy/react-native-twilio-video-webrtc#76]
### Steps to reproduce
1.connect to a room.
2.disconnect from a room.
3.connect to another room.

### Expected behaviour
Work fine.

### Actual behaviour
Throw exception and the app close.

### Environment
- **Node.js version**:v8.0
- **React Native version**:0.48.4
- **React Native platform + platform version**: Android 6, Android 7

### react-native-twilio-video-webrtc
**Version**: master

Log:

> 
> VideoTrack.java:44)
> E/AndroidRuntime(24549): 	at com.twiliorn.library.CustomTwilioVideoView.onHostResume(CustomTwilioVideoView.java:196)
> E/AndroidRuntime(24549): 	at com.facebook.react.bridge.ReactContext$1.run(ReactContext.java:153)
> E/AndroidRuntime(24549): 	at android.os.Handler.handleCallback(Handler.java:743)
> E/AndroidRuntime(24549): 	at android.os.Handler.dispatchMessage(Handler.java:95)
> E/AndroidRuntime(24549): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
> E/AndroidRuntime(24549): 	at android.os.Looper.loop(Looper.java:150)
> E/AndroidRuntime(24549): 	at android.app.ActivityThread.main(ActivityThread.java:5621)
> E/AndroidRuntime(24549): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(24549): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
> E/AndroidRuntime(24549): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

and sometimes i find this:

> java.lang.RuntimeException: getParameters failed (empty parameters)
> E/AndroidRuntime( 2940): 	at android.hardware.Camera.native_getParameters(Native Method)
> E/AndroidRuntime( 2940): 	at android.hardware.Camera.getParameters(Camera.java:2272)
> E/AndroidRuntime( 2940): 	at org.webrtc.Camera1Session.create(Camera1Session.java:83)
> E/AndroidRuntime( 2940): 	at org.webrtc.Camera1Capturer.createCameraSession(Camera1Capturer.java:34)
> E/AndroidRuntime( 2940): 	at org.webrtc.CameraCapturer$5.run(CameraCapturer.java:285)
> E/AndroidRuntime( 2940): 	at android.os.Handler.handleCallback(Handler.java:743)
> E/AndroidRuntime( 2940): 	at android.os.Handler.dispatchMessage(Handler.java:95)
> E/AndroidRuntime( 2940): 	at android.os.Looper.loop(Looper.java:150)
> E/AndroidRuntime( 2940): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by bilby91** [comment]
@slycoder Any ideas for this one ?

**Comment by slycoder** [comment]
Thanks for reporting this... looks like there's some cleanup/reinitialization we're not handling correctly.  #74 reworks a lot of the android stuff so let's get that in first and we can see if this issue persists.

**Comment by georgewwindsor** [comment]
@slycoder @bilby91  this should be resolved by #74, although there may be a better resolution.
