### ISSUE TITLE
_react2.PropTypes.func is undefined

### ISSUE THREAD

**Issue by kapilkarda** [blackuy/react-native-twilio-video-webrtc#78]
### Steps to reproduce
1. Create a fresh react app
2. install the plugin as per the readme file and link it via react-native link
3. Just run the application it gives an error

### Expected behaviour
It should run the application on device, I have generated token and set the roomname on a dummy app.

### Actual behaviour
It gives an error snapshot attached

### Environment
- **Node.js version**:  V8.9.3
- **React Native version**:0.51.0
- **React Native platform + platform version**: Android

### react-native-twilio-video-webrtc
**Version**: npm version or "master" - 1.0.1

Demo Source Code : https://github.com/kapilkarda/twilio-video-demo

![screenshot_20171221_155200](https://user-images.githubusercontent.com/4336836/34251916-ab50a702-e667-11e7-984d-3372f9e90b7e.jpg)

Please help me

**Comment by slycoder** [comment]
Ah, we failed to include prop-types as a dependency.  That should be an easy fix.  In the meantime does it work if you add prop-types to your package.json?

**Comment by kapilkarda** [comment]
installed npm install --save prop-types this but having same issue.

**Comment by bilby91** [comment]
@kapilkarda You are using version `1.0.1` ? Can you try master using git ?

**Comment by kapilkarda** [comment]
Hello @bilby91 , thanks for your response, i tried with master that error was remove now but their is new error. please check the snapshot
![screenshot_20171223_091824](https://user-images.githubusercontent.com/4336836/34316717-6ef31644-e7c2-11e7-82fc-0c6dce5c0494.jpg)

**Comment by kapilkarda** [comment]
Hello @bilby91  @slycoder  do you have any solution for this ?

**Comment by kapilkarda** [comment]
is their any help ?

**Comment by slycoder** [comment]
Did you re-run react-native link after updating?

**Comment by slycoder** [comment]
And can you update your demo app repo?  Thanks!

**Comment by ivorscott** [comment]
You cannot import Proptypes from React anymore. install prop-types from npm.
Then replace the import to use it.
import PropsType prop-types

**Comment by jmknoll** [comment]
Adding on the above above answer a little bit:

This library hasn't been updated since PropTypes was removed from React Native and moved into its own library.

So you'll have to `npm install prop-types`

And then in TwilioVideo.js change this:
```
import React, { Component, PropTypes } from 'react'
import {
  NativeModules,
  NativeEventEmitter,
  View,
} from 'react-native';
```

to this:
```
import React, { Component } from 'react'
import {
  NativeModules,
  NativeEventEmitter,
  View,
} from 'react-native';

import { PropTypes } from 'prop-types'
```

This is an ugly way of implementing this fix, but I'm not sure if this library is currently being maintained, so it'll have to work for now.

**Comment by bilby91** [comment]
@jmknoll I'm doing what I can with maintaining, not having a lot of time lately and not using the library at the moment. Can you work on a PR to fix this ? I'll review and merge.

Thanks!

**Comment by slycoder** [comment]
@jmknoll I believe the changes you are suggesting are already on master.  There have been a huge number of changes landed on master since the previous NPM release, so I'd *highly* recommend pulling master into your project.

**Comment by jmknoll** [comment]
@slycoder Thanks for the heads up. It looks like this issue at least is fixed in master. From the looks of it, this fixes a lot of the other open issues on here as well.

Maybe worth adding a line at the top of the docs advising people to install from github rather than npm as a temporary patch until the next release goes out?

**Comment by slycoder** [comment]
Either that or pushing a new version to npm.  @bilby91 what do you think about pushing out a new version?

**Comment by slycoder** [comment]
(I'm not actually sure who has access to push to npm)
