### ISSUE TITLE
Getting the local participant's track ID

### ISSUE THREAD

**Issue by liepauls** [blackuy/react-native-twilio-video-webrtc#79]
Hey, first of all, thanks for the library!

I've created custom logic to workaround the issue with participant disconnecting taking too long time, but to finish it in my project, I need the local participant's video track ID. Is there any way I can get this ID?

Best regards

**Comment by slycoder** [comment]
I believe the all of the participants are included in the `onRoomDidConnect` handler so you could stash it from there.

**Comment by slycoder** [comment]
Closing this out.  Feel free to reopen if you still have any questions.

**Comment by Dharungit** [comment]
> I believe the all of the participants are included in the `onRoomDidConnect` handler so you could stash it from there.

This `onRoomDidConnect` have all the participants but for each participant's identity and sid only available in it.
How to get the track ID for the local participant's?

**Comment by slycoder** [comment]
If you want the tracks you need to listen to the track events, e.g. onParticipantAddedVideoTrack, onParticipantAddedAudioTrack, etc.
