### ISSUE TITLE
Android can't display TwilioVideoParticipantView - black screen

### ISSUE THREAD

**Issue by Robsonwd** [blackuy/react-native-twilio-video-webrtc#86]
### Steps to reproduce
1. Install 0.51.0 version of React Native
2. Connect to Room by react-native-twilio-video-webrtc on android
3. Check if video working from remote track

### Expected behaviour

I want to actually get the video with audio from remote twilio room

### Actual behaviour

Actually when I'm connected to the room, I'm getting the audio, but video sharing only black screen. On iOS both audio and video works well, but on android only audio is working.

### Environment
- **Node.js version**: 8.9.4
- **React Native version**: 0.51.0
- **React Native platform + platform version**: Android 6.0 API 23

**Comment by frankTurtle** [comment]
I'm having the exact same issue. It was working when I tested about a month ago, but when I went back today I'm receiving this issue now too. I thought I was going crazy.

**Comment by slycoder** [comment]
This happened as a result of recent multiparty support --- the interfaces for the iOS and Android versions diverged.  I'll work on getting this patched soon.

cc @georgewwindsor

**Comment by slycoder** [comment]
Ok, I have a branch which fixes the issue I believe.  Lemme know if it works for you guys.

**Comment by Robsonwd** [comment]
@slycoder It works for me 👍Great! 😄 Thank you so much for quick help with this 😄

**Comment by frankTurtle** [comment]
@slycoder Fixed for me. Thanks!

**Comment by sohams89** [comment]
I am facing this issue :

"react": "^16.6.3",
"react-native": "^0.57.7",
"react-native-twilio-video-webrtc": "git+https://github.com/blackuy/react-native-twilio-video-webrtc.git",

**Comment by manchasavalos** [comment]
i have the same error for ios too, i have audio but no video, please help

**Comment by saikiranoptisol** [comment]
@slycoder  can you please respond on this. because most of them including me is getting this issue now. previously it is working fine only.

**Comment by rekha-emids** [comment]
@slycoder  which branch will fix these issues?

**Comment by slycoder** [comment]
A fix for the original issue was merged to master quite a while ago.  It sounds like more recent reporters might be seeing a different issue. 

For those users. is this occurring on the example app?
