### ISSUE TITLE
Rear facing camera

### ISSUE THREAD

**Issue by frankTurtle** [blackuy/react-native-twilio-video-webrtc#89]
This isn't an issue per se, but I've not been able to find anyplace in the documentation to flip to the rear facing camera for the local view. If someone could point me in the right direction, I'd greatly appreciate it. If this is not the correct way to go about this, also kindly let me know and I'll remove and ask there. Thanks!

**Comment by slycoder** [comment]
You can call flipCamera on the twilioVideo ref.  I'll update the example in the README

**Comment by frankTurtle** [comment]
Again, Thank you so much!
