### ISSUE TITLE
Can't build iOS app

### ISSUE THREAD

**Issue by gagamil** [blackuy/react-native-twilio-video-webrtc#92]
### Steps to reproduce
as stated here: https://docs.expo.io/versions/latest/guides/expokit.html
1. create-react-native-app AwesomeProject 
2. yarn eject (choose Expo Kit)
3. pod install
4. yarn add https://github.com/blackuy/react-native-twilio-video-webrtc
5. pod 'TwilioVideo'
6. pod install
Until now everything's seems ok.
7. Add the XCode project to your own XCode project's "Libraries" directory from:
node_modules/react-native-twilio-video-webrtc/ios/RNTwilioVideoWebRTC.xcodeproj
8. Add libRNTwilioVideoWebRTC.a to your XCode project target's "Linked Frameworks and Libraries"

### Expected behaviour
Build app succeed

### Actual behaviour
At step 8 build Fails.

### Environment
- **Node.js version**:v9.4.0
- **React Native version**: https://github.com/expo/react-native/archive/sdk-25.0.0.tar.gz
- **React Native platform + platform version**: iOS 9.0

### react-native-twilio-video-webrtc
**Version**: npm version or "master"

**Comment by slycoder** [comment]
I've only ever built this using the full pod workspace so I'm not sure I can help (does expo preclude one from doing so?).

Anyhow, what error are you seeing on step 8?

**Comment by slycoder** [comment]
Does following the instructions here help:

https://github.com/blackuy/react-native-twilio-video-webrtc/issues/55#issuecomment-393294030

**Comment by graphee-gabriel** [comment]
Hello, I have the same problem using an expo-ejected project.
`'React/UIView+React.h' file not found`
I use `pod 'react-native-twilio-video-webrtc', path: '../node_modules/react-native-twilio-video-webrtc'` in my pod file.
https://github.com/blackuy/react-native-twilio-video-webrtc/issues/55#issuecomment-393294030 did not help sadly. I set the search paths as stated in the doc from the beginning on. 
I manage to integrate the library on a `react-native init` project a few weeks ago, but no luck with this `expo-ejected` project.
Any suggestion ? Or if you need any additional info.

**Comment by graphee-gabriel** [comment]
Found the FIX, had to remove everything stated in those two steps:

> Add the XCode project to your own XCode project's "Libraries" directory from:
> 
> node_modules/react-native-twilio-video-webrtc/ios/RNTwilioVideoWebRTC.xcodeproj
> Add libRNTwilioVideoWebRTC.a to your XCode project target's "Linked Frameworks and Libraries". Update the settings of your project as follows:
> 
> Under Build Settings, find Search Paths.
> Edit BOTH Framework Search Paths and Library Search Paths by adding $(SRCROOT)/../node_modules/react-native-twilio-video-webrtc/ios with recursive.

The documentation is confusing because it states "If you DO use CocoaPods to manage your react native packages do `this`, if you DON'T use CocoaPods do `that`" 
But then right after it says to do `pod install`, which you clearly need to do in both cases, so reading the doc i understand that everything that follows `pod install` is for both cases. 
But the whole part with adding the project to `Libraries` and search paths is only for the case where you DON'T use CocoaPods. Maybe it would help if it'd be clearer in the doc. It a simple mistake, but easy to make and made me lose 4 hours of my day :-D.

**Comment by slycoder** [comment]
Thanks @graphee-gabriel !  I see how the wording is confusing.  If anyone wants to take a crack at improving the readme, PRs would be welcome!

**Comment by JanOwiesniak** [comment]
PR merged. I guess this issue can be for closed now?
