### ISSUE TITLE
Could not resolve all dependencies for configuration ':react-native-twilio-video-webrtc:_debugPublishCopy'. > Could not find com.android.support:support-annotations:26.1.0

### ISSUE THREAD

**Issue by aauffray** [blackuy/react-native-twilio-video-webrtc#96]
I'm not actually sure it's the module's fault since it's a pretty specific Android error but I hope someone knows how to fix that

### Steps to reproduce
1. Try compiling the app, either debug or release

### Expected behaviour
App should compile succesfully

### Actual behaviour
`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-twilio-video-webrtc'.
      > Could not resolve all dependencies for configuration ':react-native-twilio-video-webrtc:_debugPublishCopy'.
         > Could not find com.android.support:support-annotations:26.1.0.
           Searched in the following locations:
               file:/Users/antoine/Library/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/26.1.0/support-annotations-26.1.0.pom
               file:/Users/antoine/Library/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/26.1.0/support-annotations-26.1.0.jar
               file:/Users/antoine/R/medwayapp/android/sdk-manager/com/android/support/support-annotations/26.1.0/support-annotations-26.1.0.jar
           Required by:
               project :react-native-twilio-video-webrtc > com.android.support:appcompat-v7:25.3.1
               project :react-native-twilio-video-webrtc > com.android.support:appcompat-v7:25.3.1 > com.android.support:support-vector-drawable:25.3.1
               project :react-native-twilio-video-webrtc > com.android.support:design:25.3.1 > com.android.support:recyclerview-v7:25.3.1
               project :react-native-twilio-video-webrtc > com.android.support:design:25.3.1 > com.android.support:transition:25.3.1
               project :react-native-twilio-video-webrtc > com.android.support:appcompat-v7:25.3.1 > com.android.support:support-vector-drawable:25.3.1 > com.android.support:support-compat:25.3.1
               project :react-native-twilio-video-webrtc > com.android.support:design:25.3.1 > com.android.support:support-v4:25.3.1 > com.android.support:support-media-compat:25.3.1
               project :react-native-twilio-video-webrtc > com.android.support:design:25.3.1 > com.android.support:support-v4:25.3.1 > com.android.support:support-core-utils:25.3.1
               project :react-native-twilio-video-webrtc > com.android.support:design:25.3.1 > com.android.support:recyclerview-v7:25.3.1 > com.android.support:support-core-ui:25.3.1
         > Could not find com.android.support:support-annotations:26.1.0.
           Searched in the following locations:
               file:/Users/antoine/Library/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/26.1.0/support-annotations-26.1.0.pom
               file:/Users/antoine/Library/Android/sdk/extras/android/m2repository/com/android/support/support-annotations/26.1.0/support-annotations-26.1.0.jar
               file:/Users/antoine/R/medwayapp/android/sdk-manager/com/android/support/support-annotations/26.1.0/support-annotations-26.1.0.jar
           Required by:
               project :react-native-twilio-video-webrtc > com.twilio:video-android:1.3.8

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED`

### Environment
- **Node.js version**: v8.4.0
- **React Native version**: 0.42.0
- **React Native platform + platform version**: Android 7

### react-native-twilio-video-webrtc
**Version**: master

**Comment by aauffray** [comment]
My theory: 1.0.2 version of the module is causing this, but I can't find a way to use the 1.0.1 version I used previously

`error Couldn't find match for "1.0.1" in "master,v2" for "https://github.com/blackuy/react-native-twilio-video-webrtc".`

Am I right ?

**Comment by aauffray** [comment]
Fixed ! Turned out my modules now had a dependency to `com.android.support:support-annotations` (due to this module new version ? I don't know for sure) and that none of the repositories I was fetching packages from had it. I had to add `maven { url "https://maven.google.com" }` to my top-levem `build.gradle`repositories to make it work.

**Comment by ttebify** [comment]
You can add the "https://maven.google.com/" repository to the top-level build.gradle file of your project by following these steps:

Open the top-level build.gradle file in your project. This is typically located in the root directory of your project, and it should be named "build.gradle"

In the build.gradle file, look for the "allprojects" section. This section should contain a block of code that starts with "allprojects {".

Inside the "allprojects" block, you should find a "repositories" block. This block should contain a list of repositories that the project is currently configured to fetch packages from.

Inside the "repositories" block, add the following line:

```maven { url "https://maven.google.com" }```

This line tells gradle to look for packages in the "https://maven.google.com/" repository.

Save the build.gradle file and run the command "./gradlew clean" to clean the build and then run your app again.
Your build.gradle file should look like this:

```
allprojects {
    repositories {
        ...
        maven { url "https://maven.google.com" }
    }
}
```

**Comment by abdulbasit34310** [comment]
I think we should add this:

maven {
            url 'https://maven.google.com'
        }
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
}
