### ISSUE TITLE
Can't archive iOS app

### ISSUE THREAD

**Issue by ythecombinator** [blackuy/react-native-twilio-video-webrtc#98]
> Possibly related to #92.

### Steps to reproduce
1. yarn add https://github.com/blackuy/react-native-twilio-video-webrtc
1. pod 'TwilioVideo'
1. pod install
1. Add the XCode project to your own XCode project's "Libraries" directory from:
node_modules/react-native-twilio-video-webrtc/ios/RNTwilioVideoWebRTC.xcodeproj
1. Add libRNTwilioVideoWebRTC.a to your XCode project target's "Linked Frameworks and Libraries"
1. Product > Archive

### Expected behaviour
I should be able to archive the app and then submit to App Store.

### Actual behaviour
Building and running goes okay but I get an archive-time error:

```sh
Argument list too long: recursive header expansion failed at /Users/mabrasil/Documents/Dev/beakyn/projects/Dogology/dogology-mobile/node_modules/react-native-twilio-video-webrtc/ios/../../../ios/Pods/BoringSSL/crypto/lhash.
```

### Environment
- **Node.js version**: v8.9.0
- **React Native version**: 0.54.3
- **React Native platform + platform version**: iOS 11.2.5

### react-native-twilio-video-webrtc
**Version**: npm version or "master"

**Comment by slycoder** [comment]
Interesting.  Googling around it seems like lots of projects have this issue and that it might be potentially resolved by paring down the search paths.

Can you try updating the project's search paths to only look at TwilioVideo, i.e.,

change

```
$(PROJECT_DIR)/../../../ios/Pods/**
```

to

```
$(PROJECT_DIR)/../../../ios/Pods/TwilioVideo/**
```

or if you've found some other solution in the meantime.  Thanks!

**Comment by slycoder** [comment]
Closing out but feel free to reopen if you're still having trouble.
